/**
 * Hero reel — the motion in the home-page hero.
 *
 * Why this and not a video file: a video of our own work would have to be
 * re-recorded every time one of the products changes, it ships megabytes to
 * every visitor, and it crops badly into the 4:3 hero frame. This reel uses
 * the same image pipeline that powers the showcase cards (`demoPreview`), so
 * the hero shows the products *as they are right now* — regenerated by
 * `npm run demo:shots` — for zero extra bytes beyond images the CDN already
 * caches. Until a screenshot has been committed for a product, the reel shows
 * that product's illustrated cover and says so in the alt text.
 *
 * Slide 1 is deliberately the real team photo: it stays the LCP element (local,
 * optimised, priority) so the speed work in the performance pass is not undone,
 * and it keeps the hero's "one accountable team" promise literally true before
 * the reel moves on to what that team shipped.
 *
 * Every line of product copy below is a fact that is visible on the live site
 * it describes. No client names, revenue or outcome claims — same bar as
 * /products.
 */
import { demoPreview } from "@/lib/demo-shots";
import { getShowcase } from "@/lib/demos";
import { media } from "@/lib/media";

export type HeroSlide = {
  id: string;
  /** Image source. Local slides are rendered through next/image. */
  src: string;
  alt: string;
  /** Rendered with next/image + priority. Exactly one slide should set this. */
  local?: boolean;
  eyebrow: string;
  title: string;
  /** "Live Project" / "Demo" — taken verbatim from demos.ts so the showcase
   *  disclosure stays consistent everywhere it is rendered. */
  badge?: string;
  /** Internal product page this slide links to. */
  href?: string;
  /** Tailwind gradient painted under the screenshot so a slow or failed
   *  screenshot is never a blank rectangle. */
  accent: string;
};

/** Showcase ids in the order they appear, with the one factual line each. */
const reelProducts: { id: string; title: string }[] = [
  {
    id: "properties-pak",
    title: "Pakistan property marketplace — 19 property types across 8 cities.",
  },
  {
    id: "education",
    title: "School platform — 37 modules, 5 role portals, JazzCash & Easypaisa fees.",
  },
  {
    id: "motor",
    title: "Auto marketplace — 21 brands, EV and hybrid, English and اردو.",
  },
  {
    id: "ecommerce",
    title: "Storefront — 9 departments, 8 currencies, full cart and checkout.",
  },
];

export function getHeroSlides(): HeroSlide[] {
  const team: HeroSlide = {
    id: "team",
    src: media.heroTeam,
    alt: "Illustration of a product team reviewing work together",
    local: true,
    eyebrow: "Founder-led delivery",
    title: "Scope, build and launch — one accountable team.",
    badge: "Pakistan · Worldwide",
    accent: "from-navy-900 via-navy-800 to-navy-900",
  };

  const products = reelProducts.flatMap<HeroSlide>(({ id, title }) => {
    const demo = getShowcase(id);
    if (!demo) return [];
    const preview = demoPreview(demo);
    return [
      {
        id,
        /* A committed screenshot or a local cover is used as-is. A proxied
           one is asked for in strict mode so a missing screenshot 404s and
           the reel drops the slide, instead of rotating an empty frame. */
        src: preview.src.startsWith("/api/") ? `${preview.src}?strict=1` : preview.src,
        alt: preview.isCover
          ? `Illustration representing ${demo.name} — ${demo.category.toLowerCase()} product built by WordbitX`
          : `${demo.name} — ${demo.category} product built by WordbitX`,
        eyebrow: `Our product · ${demo.name}`,
        title,
        badge: demo.label,
        href: `/products/${demo.id}`,
        accent: demo.accent ?? "from-navy-900 via-brand-700 to-navy-800",
      },
    ];
  });

  return [team, ...products];
}
