import type { Project } from "@/lib/types";
import { media } from "@/lib/media";

export const moreProjects: Project[] = [
  {
    slug: "saas-operations-dashboard",
    title: "SaaS Operations & Customer Dashboard",
    type: "B2B SaaS web application",
    category: "Software",
    industry: "Software & SaaS",
    year: "2025",
    engagement: "Product discovery, UX, full-stack development, cloud delivery",
    clientLabel: "Confidential Client",
    publicStatus: "Public scope profile; client name and commercial metrics withheld.",
    summary: "A role-based customer portal with onboarding, usage visibility, billing records, support requests and an internal operations console.",
    metaTitle: "SaaS Operations Dashboard | WordbitX Project Profile",
    metaDescription: "Confidential SaaS dashboard project profile: customer onboarding, role-based access, usage analytics, billing records and internal operations tooling.",
    image: media.businessAnalyticsTeam,
    imageAlt: "Team reviewing an analytics dashboard for a SaaS operations product",
    gallery: [
      { src: media.businessAnalyticsTeam, alt: "Product team reviewing dashboard decisions", caption: "Usage and account health views for customer success" },
      { src: media.analyticsChart, alt: "Analytics reporting for a SaaS product", caption: "Internal operations reporting and issue triage" },
    ],
    overview: [
      "A growing software product needed to move customers out of email-based onboarding and give account teams a shared view of usage, plan status and open requests.",
      "WordbitX shaped the data model around accounts rather than individual users, then delivered a customer-facing portal and a separate operations console with clearly separated permissions.",
    ],
    challenge: [
      "Customer onboarding depended on manual emails and spreadsheets.",
      "Account managers could not see usage and support context in one place.",
      "Different customer roles needed different access to billing and product data.",
    ],
    solution: [
      "Account-level onboarding with invitations, role-based permissions and setup checklists.",
      "Usage dashboards with date filters, exports and account health indicators.",
      "Internal operations console for support requests, plan changes and audit history.",
    ],
    features: ["Account onboarding", "Role-based access", "Usage dashboard", "Billing records", "Support requests", "CSV exports", "Audit log"],
    technologies: ["Next.js", "React", "TypeScript", "Node.js", "PostgreSQL", "Redis", "AWS"],
    outcomes: [
      "Customer and internal teams work from the same account record.",
      "Support conversations have usage and plan context before a reply is written.",
      "Access to billing and product data is separated by role.",
    ],
    relatedServices: ["custom-software-development", "web-development", "devops-cloud-solutions"],
  },
  {
    slug: "school-admissions-fee-portal",
    title: "School Admissions & Fee Management Portal",
    type: "Education management web portal",
    category: "Software",
    industry: "Education",
    year: "2025",
    engagement: "Workflow mapping, portal UX, development, staff rollout",
    clientLabel: "Confidential Education Client",
    publicStatus: "Public scope profile; institution identity withheld for privacy.",
    summary: "An admissions-to-enrolment portal with online applications, document review, attendance, fee vouchers and parent access.",
    metaTitle: "School Admissions & Fee Portal | WordbitX Project Profile",
    metaDescription: "Confidential school portal project profile covering online admissions, application review, student records, fee vouchers and parent access.",
    image: media.classroomDiscussion,
    imageAlt: "Teacher and students collaborating in a classroom supported by education software",
    gallery: [
      { src: media.classroomDiscussion, alt: "Classroom discussion in an education environment", caption: "Teacher view for attendance and class communication" },
      { src: media.universityLecture, alt: "Students in a lecture hall", caption: "Admissions and student information workflow" },
    ],
    overview: [
      "A school group wanted admissions, fee collection and parent communication to move out of paper forms and disconnected spreadsheets before a new academic intake.",
      "The portal was designed around the student record: applicant, enrolled student, attendance, results and fee ledger are connected without giving every user access to every record.",
    ],
    challenge: [
      "Application documents were reviewed by email and hard to track.",
      "Fee vouchers and defaulter lists required manual consolidation.",
      "Parents had no reliable self-service view of attendance or fee status.",
    ],
    solution: [
      "Online application forms with document upload and review statuses.",
      "Student record created from an approved application instead of re-keying it.",
      "Fee vouchers, payments and parent access with role-based reporting.",
    ],
    features: ["Admissions", "Document review", "Student records", "Attendance", "Fee vouchers", "Parent login", "Reports"],
    technologies: ["Next.js", "TypeScript", "Node.js", "PostgreSQL", "Tailwind CSS", "AWS"],
    outcomes: [
      "Admissions status is visible to staff without searching email threads.",
      "The same student record supports fees and parent communication.",
      "Collection reporting is generated from the ledger rather than manually combined.",
    ],
    relatedServices: ["education-portals", "custom-software-development", "web-development"],
  },
  {
    slug: "restaurant-order-kitchen-system",
    title: "Restaurant Order & Kitchen Operations System",
    type: "Restaurant POS and kitchen workflow",
    category: "Software",
    industry: "Hospitality",
    year: "2025",
    engagement: "Counter study, POS UX, kitchen workflow, rollout support",
    clientLabel: "Confidential Hospitality Client",
    publicStatus: "Public scope profile; venue identity and revenue figures withheld.",
    summary: "A restaurant counter and kitchen system for tables, modifiers, kitchen tickets, split bills, delivery orders and ingredient stock.",
    metaTitle: "Restaurant Kitchen & POS System | WordbitX Project Profile",
    metaDescription: "Confidential restaurant POS project profile: table orders, kitchen tickets, modifiers, split bills, delivery orders and ingredient inventory.",
    image: media.posTerminal,
    imageAlt: "Point of sale terminal representing a restaurant counter system",
    gallery: [
      { src: media.posTerminal, alt: "POS terminal at a service counter", caption: "Fast counter and cashier billing workflow" },
      { src: media.officeTeam, alt: "Operations team reviewing restaurant reports", caption: "Shift close and branch reporting" },
    ],
    overview: [
      "A busy hospitality operation needed to reduce verbal orders and paper kitchen tickets while retaining flexible modifiers, split payments and delivery orders.",
      "WordbitX mapped the flow from table or counter to kitchen, then connected the order to payments, shift close and ingredient deductions.",
    ],
    challenge: [
      "Modifiers and extras were frequently missed during rush periods.",
      "Kitchen tickets were difficult to prioritise and reprint.",
      "Managers did not have a clean shift and wastage report.",
    ],
    solution: [
      "Touch-first ordering with required modifiers and kitchen routing.",
      "KOT display and printer routing by station.",
      "Split bills, delivery orders, shift close and ingredient movement reports.",
    ],
    features: ["Tables", "KOT", "Modifiers", "Split bills", "Delivery orders", "Shift close", "Recipe stock"],
    technologies: ["React", "TypeScript", "Node.js", "PostgreSQL", "Redis", "Docker"],
    outcomes: [
      "The kitchen receives structured tickets instead of handwritten notes.",
      "Add-ons and modifiers are required before the order can be fired.",
      "Shift reconciliation includes cash, card and delivery order channels.",
    ],
    relatedServices: ["pos-software", "inventory-management-software", "custom-software-development"],
  },
  {
    slug: "construction-project-management-portal",
    title: "Construction Project Management Portal",
    type: "Project operations and procurement portal",
    category: "Software",
    industry: "Construction & Real Estate",
    year: "2025",
    engagement: "Process mapping, role model, portal engineering",
    clientLabel: "Confidential Construction Client",
    publicStatus: "Public scope profile; project and company details withheld.",
    summary: "A project portal for work packages, site updates, material requests, approvals, contractor documents and progress reporting.",
    metaTitle: "Construction Project Management Portal | WordbitX",
    metaDescription: "Confidential construction software profile: project work packages, site updates, material requests, approvals, contractor documents and progress reporting.",
    image: media.warehouseTeam,
    imageAlt: "Operations team coordinating stock and field work in an industrial environment",
    gallery: [
      { src: media.warehouseTeam, alt: "Team coordinating operational work", caption: "Material requests and procurement approvals" },
      { src: media.businessAnalyticsTeam, alt: "Team reviewing operational reporting", caption: "Project progress and open issue dashboard" },
    ],
    overview: [
      "A construction team had site updates, supplier documents and material requests spread across chats and spreadsheets. The business needed a single project view without forcing field staff into a complicated ERP.",
      "The portal separated site capture from head-office approval: mobile-friendly forms at the site, structured queues and reporting for management.",
    ],
    challenge: [
      "Material requests were approved in chat with no audit trail.",
      "Supplier documents were hard to find when a project changed hands.",
      "Management reporting arrived late and depended on one coordinator.",
    ],
    solution: [
      "Project and work-package records with assigned owners and due dates.",
      "Mobile-first site updates with photos, notes and issue status.",
      "Approval workflows for material requests and contractor documents.",
    ],
    features: ["Projects", "Work packages", "Site updates", "Material requests", "Approvals", "Documents", "Progress reports"],
    technologies: ["Next.js", "React", "TypeScript", "Node.js", "PostgreSQL", "AWS"],
    outcomes: [
      "Site updates become searchable project records.",
      "Requests show owner, status and approval history.",
      "Management sees open issues and progress without waiting for a weekly spreadsheet.",
    ],
    relatedServices: ["custom-software-development", "crm-erp-solutions", "web-development"],
  },
  {
    slug: "subscription-ecommerce-platform",
    title: "Subscription E-Commerce Platform",
    type: "Recurring commerce storefront",
    category: "E-Commerce",
    industry: "Consumer Products",
    year: "2025",
    engagement: "Commerce strategy, recurring order flows, storefront build",
    clientLabel: "Confidential E-Commerce Client",
    publicStatus: "Public scope profile; brand and subscription figures withheld.",
    summary: "A recurring-order storefront with subscription selection, pause and skip controls, payment retries and fulfilment visibility.",
    metaTitle: "Subscription E-Commerce Platform | WordbitX Project Profile",
    metaDescription: "Confidential recurring commerce project profile: subscription plans, pause and skip, payment retries, fulfilment visibility and customer self-service.",
    image: media.shopifyStoreAlt,
    imageAlt: "Laptop displaying an online store interface for a recurring product business",
    gallery: [
      { src: media.shopifyStoreAlt, alt: "Online store interface on a laptop", caption: "Customer subscription selection and self-service" },
      { src: media.ecommerceOnline, alt: "Customer shopping online on a laptop", caption: "Checkout and delivery preference flow" },
    ],
    overview: [
      "A product brand needed to move recurring orders away from manual reminders. Customers had to choose a plan, change frequency, pause without calling support and recover a failed payment without losing their subscription.",
      "WordbitX designed the storefront and customer area around the recurring lifecycle rather than treating a subscription as a normal one-off product.",
    ],
    challenge: [
      "Customers relied on support to pause or skip a delivery.",
      "Failed payments created manual follow-up work.",
      "The operations team could not see upcoming fulfilment volume clearly.",
    ],
    solution: [
      "Plan selection with frequency, pause and skip controls.",
      "Payment retry and customer notification flow.",
      "Operations view for upcoming orders, fulfilment status and exceptions.",
    ],
    features: ["Plans", "Pause / skip", "Payment retry", "Customer portal", "Fulfilment queue", "Analytics"],
    technologies: ["Shopify", "Next.js", "TypeScript", "Node.js", "Stripe", "PostgreSQL"],
    outcomes: [
      "Customers manage routine subscription changes without contacting support.",
      "Failed payments enter a visible recovery flow.",
      "Fulfilment teams can plan upcoming volume from live orders.",
    ],
    relatedServices: ["ecommerce-shopify", "ecommerce-development", "web-development"],
  },
  {
    slug: "field-service-mobile-application",
    title: "Field Service Scheduling Mobile Application",
    type: "Mobile workforce application",
    category: "Mobile Apps",
    industry: "Field Services",
    year: "2025",
    engagement: "Product discovery, Flutter build, dispatcher console",
    clientLabel: "Confidential Field Service Client",
    publicStatus: "Public scope profile; client and operational volumes withheld.",
    summary: "A technician app with scheduled jobs, offline notes, photo proof, parts usage and a dispatcher view for assignments.",
    metaTitle: "Field Service Mobile App | WordbitX Project Profile",
    metaDescription: "Confidential field service app profile: technician scheduling, offline job notes, photo proof, parts usage and dispatcher assignment.",
    image: media.deliveryAppAlt,
    imageAlt: "Mobile application used by a field worker during a service visit",
    gallery: [
      { src: media.deliveryAppAlt, alt: "Field service job screen on a smartphone", caption: "Technician job queue and offline status updates" },
      { src: media.deliveryApp, alt: "Mobile delivery and field application", caption: "Photo proof, signature and parts used" },
    ],
    overview: [
      "A field service team was coordinating technician visits by phone. The office could not see job status, and technicians lost notes when they worked in basements or rural areas with weak signal.",
      "The app stores the day's work locally, syncs later and gives dispatch a structured status view instead of a chain of calls.",
    ],
    challenge: [
      "Weak signal made the existing web form unreliable.",
      "Parts and job notes were written on paper.",
      "Dispatch had no consistent arrival or completion status.",
    ],
    solution: [
      "Offline job queue with sync and conflict handling.",
      "Photo, signature, note and parts capture at completion.",
      "Dispatcher console with assignment and exception views.",
    ],
    features: ["Job queue", "Offline sync", "Route handoff", "Photo proof", "Signature", "Parts usage", "Dispatcher view"],
    technologies: ["Flutter", "Dart", "Node.js", "PostgreSQL", "Firebase", "Google Cloud"],
    outcomes: [
      "Technicians can complete jobs without a live connection.",
      "Completion evidence is attached to the work order.",
      "Dispatchers see exceptions without calling every technician.",
    ],
    relatedServices: ["mobile-app-development", "custom-software-development", "devops-cloud-solutions"],
  },
  {
    slug: "travel-booking-platform",
    title: "Travel Booking & Itinerary Platform",
    type: "Booking web application",
    category: "Websites",
    industry: "Travel",
    year: "2025",
    engagement: "UX, booking flow, partner integration, SEO architecture",
    clientLabel: "Confidential Travel Client",
    publicStatus: "Public scope profile; partner and booking data withheld.",
    summary: "A travel booking platform for enquiries, itinerary building, availability requests, deposits and customer trip documents.",
    metaTitle: "Travel Booking Platform | WordbitX Project Profile",
    metaDescription: "Confidential travel platform profile: itinerary builder, availability requests, deposits, customer documents and SEO-ready destination pages.",
    image: media.deliveryApp,
    imageAlt: "Travel planning application viewed on a smartphone",
    gallery: [
      { src: media.deliveryApp, alt: "Mobile travel planning interface", caption: "Itinerary and traveller communication view" },
      { src: media.businessAnalyticsTeam, alt: "Team reviewing booking analytics", caption: "Operations dashboard for enquiries and trip status" },
    ],
    overview: [
      "A travel operator needed more than a lead form. Their team assembled itineraries, availability and deposit requests across spreadsheets while the customer had no single place to review the trip.",
      "The platform separates public destination content from private trip workspaces, so SEO pages attract demand and authenticated workflows handle the booking.",
    ],
    challenge: [
      "Trip details changed across several spreadsheets and emails.",
      "Customers could not approve an itinerary in one place.",
      "Destination content and booking operations were disconnected.",
    ],
    solution: [
      "Itinerary builder with day-by-day activities, transfers and accommodation.",
      "Customer workspace for review, documents, deposits and status.",
      "Server-rendered destination pages with internal links into enquiry journeys.",
    ],
    features: ["Itineraries", "Availability requests", "Customer workspace", "Deposits", "Documents", "Destination pages"],
    technologies: ["Next.js", "TypeScript", "Node.js", "PostgreSQL", "Stripe", "AWS"],
    outcomes: [
      "Customers review the current itinerary instead of a chain of attachments.",
      "Operations sees trip status, documents and outstanding actions together.",
      "Destination content has a crawlable path into booking enquiries.",
    ],
    relatedServices: ["web-development", "custom-software-development", "seo-services"],
  },
  {
    slug: "legal-document-review-workflow",
    title: "AI-Assisted Legal Document Review Workflow",
    type: "Document intelligence and review portal",
    category: "AI",
    industry: "Professional Services",
    year: "2025",
    engagement: "Use-case assessment, extraction pipeline, review UI",
    clientLabel: "Confidential Professional Services Client",
    publicStatus: "Public scope profile; documents, client identity and accuracy figures withheld.",
    summary: "A controlled document review workflow that extracts fields, highlights uncertain sections and keeps human approval in the loop.",
    metaTitle: "AI Document Review Workflow | WordbitX Project Profile",
    metaDescription: "Confidential AI document review profile: controlled extraction, confidence scoring, human review queues, source links and audit logging.",
    image: media.aiNeural,
    imageAlt: "AI network visual representing document intelligence and assisted review",
    gallery: [
      { src: media.aiNeural, alt: "AI document processing visualisation", caption: "Extraction pipeline with confidence scoring" },
      { src: media.analyticsPaper, alt: "Document analytics and review reporting", caption: "Review accuracy and exception reporting" },
    ],
    overview: [
      "A professional services team spent hours finding clauses and re-keying structured fields from documents that arrived in different formats. They needed speed without giving an automated model final authority.",
      "WordbitX delivered a review queue: extraction produces values and source references, low-confidence fields route to a human, and every decision is logged.",
    ],
    challenge: [
      "Documents varied by sender and layout.",
      "The workflow needed source evidence for every extracted field.",
      "Final acceptance had to remain with a qualified reviewer.",
    ],
    solution: [
      "Document ingestion with OCR and structured extraction.",
      "Field-level confidence with links back to source text.",
      "Reviewer queue, corrections, evaluation set and cost monitoring.",
    ],
    features: ["Ingestion", "OCR", "Extraction", "Confidence", "Review queue", "Source links", "Audit"],
    technologies: ["Python", "OpenAI", "LangChain", "Node.js", "PostgreSQL", "Docker"],
    outcomes: [
      "Routine fields are prepared before a reviewer opens the document.",
      "Low-confidence items remain visible instead of being silently accepted.",
      "Each reviewed value can be traced to the source document.",
    ],
    relatedServices: ["ai-solutions", "custom-software-development", "devops-cloud-solutions"],
  },
  {
    slug: "multi-location-clinic-booking-app",
    title: "Multi-Location Clinic Booking Application",
    type: "Healthcare booking web and mobile experience",
    category: "Mobile Apps",
    industry: "Healthcare",
    year: "2025",
    engagement: "UX, availability engine, patient booking, clinic admin",
    clientLabel: "Confidential Healthcare Client",
    publicStatus: "Public scope profile; clinic identity and patient data withheld.",
    summary: "A multi-location booking experience with doctor schedules, location search, reminders, rescheduling and clinic reception controls.",
    metaTitle: "Multi-Location Clinic Booking App | WordbitX Project Profile",
    metaDescription: "Confidential clinic booking profile: doctor schedules, location search, real-time slots, reminders, rescheduling and reception controls.",
    image: media.doctorTablet,
    imageAlt: "Healthcare professional using a digital tablet during a clinic workflow",
    gallery: [
      { src: media.doctorTablet, alt: "Doctor using a clinic application on a tablet", caption: "Doctor and location availability view" },
      { src: media.doctorsReview, alt: "Doctors reviewing patient information", caption: "Reception and appointment management workflow" },
    ],
    overview: [
      "A clinic group needed one booking experience across locations without losing each doctor's individual schedule, consultation duration or leave rules.",
      "The product combines public search and booking with an internal reception console that can override, reschedule and manage walk-ins with an audit trail.",
    ],
    challenge: [
      "Patients were calling separate branches to find a slot.",
      "Doctor leave and overlapping schedules created conflicts.",
      "Reception needed override power without losing a history of changes.",
    ],
    solution: [
      "Location and speciality search with a real-time slot engine.",
      "Doctor schedules with breaks, leave and consultation duration.",
      "Confirmation, reminder and rescheduling flow with reception control.",
    ],
    features: ["Location search", "Doctor schedules", "Slot locking", "Reminders", "Rescheduling", "Walk-ins", "Audit trail"],
    technologies: ["Next.js", "TypeScript", "Node.js", "PostgreSQL", "Firebase", "Tailwind CSS"],
    outcomes: [
      "Patients can find an appropriate slot across branches without separate calls.",
      "The data layer prevents double bookings.",
      "Reception overrides remain visible in an audit history.",
    ],
    relatedServices: ["hospital-medical-portals", "web-development", "mobile-app-development"],
  },
  {
    slug: "b2b-procurement-portal",
    title: "B2B Procurement & Supplier Portal",
    type: "Purchasing and supplier operations platform",
    category: "Software",
    industry: "Distribution & Manufacturing",
    year: "2025",
    engagement: "Procurement mapping, supplier portal, approvals and reporting",
    clientLabel: "Confidential Distribution Client",
    publicStatus: "Public scope profile; supplier identities and spend data withheld.",
    summary: "A procurement portal for purchase requests, supplier quotes, approvals, goods received and invoice matching.",
    metaTitle: "B2B Procurement Portal | WordbitX Project Profile",
    metaDescription: "Confidential procurement portal profile: purchase requests, supplier quotes, approvals, goods received and invoice matching.",
    image: media.warehouseTeam,
    imageAlt: "Warehouse operations team coordinating procurement and inventory",
    gallery: [
      { src: media.warehouseTeam, alt: "Warehouse team coordinating operations", caption: "Goods received and warehouse confirmation" },
      { src: media.businessAnalyticsTeam, alt: "Business team reviewing procurement reports", caption: "Supplier and purchase order reporting" },
    ],
    overview: [
      "A distribution business had purchase requests in chat, quotes in email and goods received on paper. The owner could see a bill but not the request or approval that led to it.",
      "The portal connected the lifecycle from request to supplier quote, approval, receiving and invoice match, with role-specific access by department.",
    ],
    challenge: [
      "Approvals had no consistent threshold or audit record.",
      "Goods received were not reliably matched to purchase orders.",
      "Supplier performance and lead time were hard to compare.",
    ],
    solution: [
      "Purchase request workflow with configurable approval levels.",
      "Supplier quote comparison and selected-vendor record.",
      "GRN and invoice matching with exception reporting.",
    ],
    features: ["Purchase requests", "Quote comparison", "Approvals", "POs", "GRN", "Invoice match", "Supplier reports"],
    technologies: ["React", "TypeScript", "Node.js", "PostgreSQL", "Redis", "Docker"],
    outcomes: [
      "Every purchase has a request, approval and receiving history.",
      "Invoice exceptions are visible before payment.",
      "Supplier performance can be reviewed from recorded dates and quantities.",
    ],
    relatedServices: ["inventory-management-software", "crm-erp-solutions", "custom-software-development"],
  },
  {
    slug: "marketing-analytics-lead-platform",
    title: "Marketing Analytics & Lead Routing Platform",
    type: "Lead generation and attribution web platform",
    category: "Websites",
    industry: "Marketing & Professional Services",
    year: "2025",
    engagement: "Tracking audit, lead platform, attribution dashboard",
    clientLabel: "Confidential Marketing Client",
    publicStatus: "Public scope profile; campaign spend and client identity withheld.",
    summary: "A lead platform connecting landing pages, campaign sources, routing rules, sales follow-up and conversion reporting.",
    metaTitle: "Marketing Lead Routing Platform | WordbitX Project Profile",
    metaDescription: "Confidential marketing platform profile: landing-page leads, source attribution, automatic routing, follow-up status and conversion reporting.",
    image: media.adsAnalytics,
    imageAlt: "Laptop showing analytics used for lead generation and campaign reporting",
    gallery: [
      { src: media.adsAnalytics, alt: "Marketing analytics on a laptop", caption: "Source and conversion reporting" },
      { src: media.businessAnalyticsTeam, alt: "Team reviewing marketing performance", caption: "Lead quality and sales follow-up dashboard" },
    ],
    overview: [
      "A service business was generating leads across paid search, social and landing pages but could not identify which source produced qualified conversations. Leads were forwarded manually and follow-up had no standard status.",
      "WordbitX connected capture, source attribution, routing and follow-up into a small operational platform so marketing and sales could review the same pipeline.",
    ],
    challenge: [
      "Lead source parameters were lost between landing page and CRM.",
      "Sales ownership was assigned manually.",
      "Reports measured form fills instead of qualified conversations.",
    ],
    solution: [
      "Landing forms that preserve source, campaign and page context.",
      "Routing rules based on service, territory and capacity.",
      "Dashboard for response time, qualification and closed outcomes.",
    ],
    features: ["Landing forms", "Source tracking", "Routing", "Follow-up status", "Lead quality", "Conversion reports"],
    technologies: ["Next.js", "TypeScript", "Node.js", "PostgreSQL", "Google Analytics", "Tag Manager"],
    outcomes: [
      "Marketing sees source context attached to the lead record.",
      "New enquiries are assigned using rules rather than an inbox queue.",
      "Reporting separates raw leads from qualified business conversations.",
    ],
    relatedServices: ["digital-marketing", "web-development", "seo-services", "custom-software-development"],
  },
];
