import type { Service } from "@/lib/types";
import { media } from "@/lib/media";

/**
 * Reusable process, so each of the newer service pages is complete without
 * repeating hundreds of near-identical lines. Individual services still get
 * unique overview, offerings, deliverables, FAQs and imagery.
 */
const publishingProcess = [
  { step: "01", title: "Account setup", text: "Developer account creation, ownership configured under your business." },
  { step: "02", title: "Listing prep", text: "Metadata, screenshots, preview assets and compliance forms prepared." },
  { step: "03", title: "Submission", text: "Build uploaded, review responses drafted, submission tracked to approval." },
  { step: "04", title: "Post-launch", text: "Version updates, staged rollouts and store analytics wired in." },
];

const campaignProcess = [
  { step: "01", title: "Audit", text: "Existing account, tracking and previous performance reviewed." },
  { step: "02", title: "Strategy", text: "Audience, offer, budget and creative approach defined." },
  { step: "03", title: "Launch", text: "Campaigns built and creative published with clean tracking." },
  { step: "04", title: "Optimise", text: "Weekly review, testing and scaling of what converts." },
];

export const servicesD: Service[] = [
  {
    slug: "ecommerce-development",
    title: "E-Commerce Development",
    shortTitle: "E-Commerce Development",
    icon: "ecommerce",
    h1: "Custom E-Commerce Development for Growing Online Stores",
    tagline:
      "WooCommerce, headless commerce and fully custom storefronts — built when Shopify cannot fit your pricing, catalogue or operations.",
    summary:
      "Custom eCommerce platforms and WooCommerce stores with tailored catalogue logic, payment gateways, wholesale pricing and marketplace integrations.",
    metaTitle: "E-Commerce Development Company | Custom Online Store Development",
    metaDescription:
      "Custom eCommerce development: WooCommerce, headless storefronts and bespoke platforms with wholesale pricing, marketplace integration and conversion-focused UX.",
    primaryKeyword: "eCommerce development company",
    keywords: [
      "eCommerce development company",
      "custom eCommerce website",
      "WooCommerce development",
      "headless eCommerce",
      "online store development",
    ],
    image: media.storeFashion,
    imageAlt: "Chic retail store entrance in a modern shopping mall, representing a custom e-commerce storefront",
    overview: [
      "Not every online business fits into a hosted template. Wholesale pricing, made-to-order production, B2B accounts, complex shipping rules and marketplace-style catalogues quickly hit the limits of what an off-the-shelf platform can express — and app subscriptions keep climbing while the workarounds keep growing.",
      "WordbitX builds custom eCommerce platforms and WooCommerce stores where the checkout logic, pricing rules and operational flows belong to you. When Shopify is the right tool we say so; when it is not, we engineer the alternative.",
    ],
    whoNeeds: [
      "Wholesale and B2B stores with customer-specific pricing",
      "Brands with configurators, bundles or made-to-order products",
      "Content-led stores needing deep editorial control",
      "Retailers exceeding what a hosted platform can express",
      "Businesses replacing several apps with a single custom flow",
    ],
    problems: [
      { title: "Platform pricing limits", text: "Hosted stores struggle with tiered wholesale, contract pricing and complex discount rules. Custom logic solves it at the source." },
      { title: "App-stack sprawl", text: "Dozens of overlapping apps slow the store and inflate cost. A tailored build removes them." },
      { title: "Marketplace-style catalogues", text: "Very large or vendor-driven catalogues need architecture the hosted platforms do not offer." },
    ],
    benefits: [
      { title: "Full control", text: "Own the front-end, checkout logic and data model end to end." },
      { title: "Lower monthly cost at scale", text: "No per-transaction fees or app subscription creep." },
      { title: "Better performance", text: "Lean code and modern rendering keep Core Web Vitals healthy." },
      { title: "Real integrations", text: "ERPs, POS, couriers and payment gateways connected properly." },
    ],
    offerings: [
      { title: "Custom eCommerce platforms", text: "Fully bespoke storefronts with your exact business rules." },
      { title: "WooCommerce development", text: "Content-heavy WordPress stores with custom checkout." },
      { title: "Headless commerce", text: "Next.js storefronts on a commerce backend of your choice." },
      { title: "B2B & wholesale", text: "Company accounts, tiered pricing, quotes and credit workflows." },
    ],
    deliverables: [
      "Custom product, cart and checkout implementation",
      "Payment gateway and shipping integrations",
      "B2B pricing, quotes and account workflows where required",
      "Inventory sync with POS, ERP or marketplaces",
      "Enhanced eCommerce analytics and event tracking",
      "Admin training and post-launch optimisation window",
    ],
    process: [
      { step: "01", title: "Commerce audit", text: "Catalogue, pricing rules, operations and platform fit." },
      { step: "02", title: "Architecture", text: "Data model, integrations, platform choice and phased build plan." },
      { step: "03", title: "Storefront build", text: "Design system, product templates, cart and checkout." },
      { step: "04", title: "Data & QA", text: "Product import, tax and shipping tests, end-to-end order QA." },
      { step: "05", title: "Launch & optimise", text: "Go-live, funnel monitoring and iterative CRO." },
    ],
    techStack: ["Next.js", "WooCommerce", "WordPress", "Node.js", "TypeScript", "PostgreSQL", "Stripe", "AWS"],
    whyUs: [
      { title: "Honest platform advice", text: "We recommend Shopify when it fits — even on a custom-build enquiry." },
      { title: "Operations included", text: "Stock, fulfilment and returns designed with your team." },
      { title: "Measurable analytics", text: "Clean events so marketing spend can be judged on order data." },
      { title: "Ownership", text: "Code, data and accounts belong to your business." },
    ],
    faqs: [
      { question: "How is this different from your Shopify service?", answer: "Shopify is a hosted platform with fast launch and simple operations. Custom eCommerce is used when catalogue, pricing or workflow requirements exceed what Shopify can express — such as B2B accounts, configurators or heavy ERP integration." },
      { question: "Can you migrate from Shopify or Magento?", answer: "Yes. We migrate products, customers, orders and content with redirects that preserve SEO, then validate indexing after launch." },
      { question: "Do you build on WooCommerce?", answer: "Yes, particularly for content-driven brands already on WordPress. WooCommerce with a custom theme and lean plugin footprint remains a strong choice when speed and marketing content matter." },
    ],
    related: ["ecommerce-shopify", "woocommerce-development", "google-merchant-center", "amazon-store-setup"],
    relatedPosts: ["shopify-vs-custom-ecommerce-website", "how-to-launch-a-shopify-store"],
    projectCategory: "E-Commerce",
    featured: true,
  },
  {
    slug: "android-app-development",
    title: "Android App Development",
    shortTitle: "Android App Development",
    icon: "mobile",
    h1: "Android App Development Company for Native & Cross-Platform Apps",
    tagline:
      "Native Kotlin and cross-platform Android apps built for Google Play — with proper Play Console submission and update management.",
    summary:
      "Native Kotlin, Java and cross-platform Android applications with Google Play publishing, in-app billing and background service optimisation.",
    metaTitle: "Android App Development Company | Native Android & Play Store",
    metaDescription:
      "Android app development services: native Kotlin, Java and cross-platform apps, Google Play publishing, in-app billing, push notifications and background service optimisation.",
    primaryKeyword: "Android app development",
    keywords: [
      "Android app development",
      "Android app development company",
      "native Android app developers",
      "Kotlin app development",
      "Google Play app development",
    ],
    image: media.androidApp,
    imageAlt: "Android smartphone showing multiple applications on a modern home screen",
    overview: [
      "Android is the dominant platform in most emerging markets, which means the phones that matter most for your users are often not flagships. An Android app that looks good on a demo device but hitches on a mid-range phone loses the majority of its audience within a week.",
      "WordbitX builds Android applications the right way — native Kotlin for performance-critical products, cross-platform frameworks when a shared codebase serves better, and disciplined profiling on the real device tier your customers actually use.",
    ],
    whoNeeds: [
      "Startups targeting Android-first markets in South Asia, MENA and Africa",
      "Businesses needing background services, location or hardware access",
      "Retailers and delivery services running Android on rugged devices",
      "Companies replacing an outdated or unmaintained Android app",
      "Products distributed via Google Play, Huawei AppGallery or MDM",
    ],
    problems: [
      { title: "Fragmentation and mid-range performance", text: "Testing only on flagship devices hides real-world jank. We profile on the OS versions and hardware your users actually own." },
      { title: "Battery and background issues", text: "Aggressive background work drains batteries and gets apps killed. Foreground services and WorkManager are used correctly." },
      { title: "Play Console rejections", text: "Data safety, permissions and target API rules cause most rejections. We prepare submissions properly the first time." },
    ],
    benefits: [
      { title: "Native performance", text: "Kotlin and Jetpack Compose deliver smooth UI on mid-range Android." },
      { title: "Reliable background work", text: "Location, sync and notifications that survive Android's power management." },
      { title: "Play Store confidence", text: "Prepared listings, correct data safety declarations and versioned release channels." },
      { title: "Long-term maintainability", text: "Modular architecture with tests on critical paths." },
    ],
    offerings: [
      { title: "Native Kotlin apps", text: "Jetpack Compose interfaces with modern architecture components." },
      { title: "Cross-platform Android", text: "Flutter or React Native when a shared iOS/Android codebase makes sense." },
      { title: "Legacy modernisation", text: "Migrating older Java apps to Kotlin and current SDK targets." },
      { title: "Publishing & updates", text: "Play Console submission, staged rollouts and in-app updates." },
    ],
    deliverables: [
      "Android application in your Play Console with signed release pipeline",
      "Backend and APIs with authentication, notifications and analytics",
      "Play Store listing, screenshots and data safety form",
      "Release notes, staged rollout plan and crash monitoring",
      "Documentation, source code and developer handover",
    ],
    process: [
      { step: "01", title: "Product definition", text: "User stories, release-one scope, device matrix and technical feasibility." },
      { step: "02", title: "UX & prototype", text: "Interactive prototype validated before any code." },
      { step: "03", title: "Build sprints", text: "Two-week sprints with installable test builds each cycle." },
      { step: "04", title: "Device QA", text: "Performance, memory and battery testing across the target Android tier." },
      { step: "05", title: "Publish & iterate", text: "Play submission, monitoring and data-driven improvements." },
    ],
    techStack: ["Kotlin", "Java", "Flutter", "React", "Firebase", "PostgreSQL", "Node.js", "Docker"],
    whyUs: [
      { title: "Mid-range first", text: "We test where your users actually live, not on the latest flagship." },
      { title: "Publishing expertise", text: "Data safety, permissions and review responses handled by us." },
      { title: "Backend under one roof", text: "APIs, notifications and admin dashboards from the same team." },
      { title: "Post-launch support", text: "OS updates arrive every year; we keep your app compatible and secure." },
    ],
    faqs: [
      { question: "Native Kotlin or cross-platform?", answer: "Native Kotlin wins for heavy graphics, deep hardware use, or where every millisecond matters. Cross-platform wins when you need iOS and Android in parallel from one codebase. We recommend based on your feature set and budget." },
      { question: "Do you publish the app for us?", answer: "Yes. Under your Google Play developer account, so you always own the listing, reviews and data." },
      { question: "Can you fix an existing Android app?", answer: "Yes. We audit performance, crash reports and code quality, then propose targeted fixes or a phased rebuild." },
    ],
    related: ["ios-app-development", "mobile-app-development", "google-play-console", "app-store-optimization"],
    relatedPosts: ["android-vs-ios-which-to-build-first", "hire-android-app-developers"],
    projectCategory: "Mobile Apps",
    featured: true,
  },
  {
    slug: "ios-app-development",
    title: "iOS App Development",
    shortTitle: "iOS App Development",
    icon: "mobile",
    h1: "iOS App Development Company for iPhone & iPad Applications",
    tagline:
      "Native Swift and cross-platform iOS apps built for the App Store — with proper review-team handling and TestFlight rollout.",
    summary:
      "Native Swift and SwiftUI iOS applications with App Store submission, in-app purchases, push notifications and TestFlight beta distribution.",
    metaTitle: "iOS App Development Company | iPhone & iPad App Developers",
    metaDescription:
      "iOS app development services: native Swift, SwiftUI and cross-platform iPhone and iPad apps, App Store submission, TestFlight distribution and in-app purchase integration.",
    primaryKeyword: "iOS app development",
    keywords: [
      "iOS app development",
      "iOS app development company",
      "iPhone app development",
      "Swift app development",
      "Apple App Store development",
    ],
    image: media.iosApp,
    imageAlt: "iPhone displaying a polished iOS application interface on a wooden desk",
    overview: [
      "iOS users spend more and expect more. The App Store review team is stricter than Google Play, the design bar is higher, and the platform-specific patterns matter — an app that ignores iOS conventions feels immediately foreign to the audience it needs to convert.",
      "WordbitX builds iOS applications with native Swift and SwiftUI where the product benefits from platform depth, and cross-platform frameworks where iOS and Android need to ship together. Either way, submissions clear the App Store review team the first time.",
    ],
    whoNeeds: [
      "Consumer brands where iOS users represent premium revenue",
      "Businesses targeting Western, GCC and international audiences",
      "Products needing HealthKit, ARKit, CoreML or Apple Pay",
      "Enterprises distributing via Apple Business Manager",
      "Startups replacing an outdated or crash-prone iOS build",
    ],
    problems: [
      { title: "App Store rejections", text: "Privacy manifests, purpose strings and IAP rules trip up unprepared submissions. We handle the review requirements upfront." },
      { title: "Ignored iOS conventions", text: "Copying Android patterns onto iOS feels wrong to users. Native patterns and Human Interface Guidelines are followed." },
      { title: "In-app purchase misconfiguration", text: "Subscriptions, restores and family sharing must be handled correctly, or Apple removes the app." },
    ],
    benefits: [
      { title: "Native fluidity", text: "SwiftUI and UIKit interfaces that feel right on iPhone and iPad." },
      { title: "Store approval", text: "Correct privacy, IAP and permission handling for first-time approval." },
      { title: "Access to Apple frameworks", text: "Apple Pay, HealthKit, ARKit and CoreML integrated properly when needed." },
      { title: "TestFlight beta", text: "Structured beta cycles for internal and external testers." },
    ],
    offerings: [
      { title: "Native Swift apps", text: "SwiftUI and UIKit builds with modern iOS architecture." },
      { title: "Cross-platform iOS", text: "Flutter or React Native for parallel iOS and Android delivery." },
      { title: "In-app purchases", text: "Subscription, consumable and one-time purchase flows tested end to end." },
      { title: "App Store publishing", text: "TestFlight distribution, submission and phased release." },
    ],
    deliverables: [
      "iOS application in your App Store Connect with signed release pipeline",
      "Backend, APIs, push notifications and analytics",
      "App Store listing, screenshots and privacy manifests",
      "TestFlight beta rollout for stakeholders",
      "Documentation, source code and developer handover",
    ],
    process: [
      { step: "01", title: "Product definition", text: "Scope, HIG-aligned UX plan and technical feasibility." },
      { step: "02", title: "UX & prototype", text: "SwiftUI prototype validated on real devices." },
      { step: "03", title: "Build sprints", text: "TestFlight builds delivered every cycle." },
      { step: "04", title: "Device QA", text: "Testing across iPhone and iPad sizes, current and previous iOS." },
      { step: "05", title: "Submit & iterate", text: "App Store submission, review handling and data-driven improvements." },
    ],
    techStack: ["Swift", "SwiftUI", "Flutter", "React", "Firebase", "Node.js", "PostgreSQL", "Docker"],
    whyUs: [
      { title: "HIG-aware design", text: "Interfaces that feel native to iOS users, not ported from Android." },
      { title: "Review-team ready", text: "Privacy manifests, purpose strings and IAP rules covered upfront." },
      { title: "TestFlight discipline", text: "Structured beta with real feedback before public release." },
      { title: "Ongoing support", text: "iOS releases yearly; we keep the app compatible and safe." },
    ],
    faqs: [
      { question: "Do we need our own Apple Developer account?", answer: "Yes — you own it. Apple requires the app to publish under the business entity, and we help you set it up if needed." },
      { question: "How long does App Store approval take?", answer: "Reviews typically complete within 24–48 hours, sometimes same-day. We prepare submissions to minimise rework, and handle any reviewer responses on your behalf." },
      { question: "Swift or cross-platform?", answer: "Native Swift is preferred for performance-critical products, deep Apple integrations or App Store-first launches. Cross-platform is efficient when iOS and Android must ship in parallel." },
    ],
    related: ["android-app-development", "mobile-app-development", "app-store-publishing", "app-store-optimization"],
    relatedPosts: ["mobile-app-development-guide", "how-ai-automation-helps-businesses"],
    projectCategory: "Mobile Apps",
    featured: true,
  },
  {
    slug: "social-media-marketing",
    title: "Social Media Marketing",
    shortTitle: "Social Media Marketing",
    icon: "marketing",
    h1: "Social Media Marketing Services for Growth-Focused Brands",
    tagline:
      "Content, community and paid social — Instagram, Facebook, TikTok, LinkedIn and YouTube — managed as one measurable programme.",
    summary:
      "Social media management, content production and paid campaigns across Instagram, Facebook, TikTok, LinkedIn and YouTube.",
    metaTitle: "Social Media Marketing Services | Instagram, Facebook, TikTok, LinkedIn",
    metaDescription:
      "Social media marketing services: content calendars, creative production, community management and paid campaigns across Instagram, Facebook, TikTok, LinkedIn and YouTube.",
    primaryKeyword: "social media marketing services",
    keywords: [
      "social media marketing services",
      "social media agency",
      "Instagram marketing services",
      "TikTok marketing agency",
      "Facebook and Meta ads management",
    ],
    image: media.socialCreator,
    imageAlt: "Content creator planning social media posts on notebook and smartphone",
    overview: [
      "Social media is where most brands are discovered today, but posting alone rarely produces revenue. The channels that convert are the ones with a proper editorial calendar, on-brand creative, active community management and paid amplification for content that actually performs.",
      "WordbitX runs social media as an integrated programme — content, community and ads working together — with attribution that shows which posts and campaigns produce real business, not just impressions.",
    ],
    whoNeeds: [
      "Brands with inconsistent or reactive social posting",
      "Businesses running ads without organic support",
      "eCommerce stores driving traffic from Instagram and TikTok",
      "B2B companies building trust through LinkedIn",
      "Local businesses turning followers into walk-ins and enquiries",
    ],
    problems: [
      { title: "Posting without a plan", text: "Ad-hoc content confuses the algorithm and the audience. A monthly editorial calendar fixes both." },
      { title: "Ads on a weak profile", text: "Paid campaigns fail when the organic profile looks abandoned. We build both together." },
      { title: "No attribution", text: "Vanity metrics hide what is working. Clean tracking ties reach and clicks to real conversions." },
    ],
    benefits: [
      { title: "Consistent brand voice", text: "Content calendars that ship, not one-off bursts." },
      { title: "Higher engagement", text: "Formats and hooks matched to each platform's native behaviour." },
      { title: "Efficient ad spend", text: "Retargeting and lookalike layers built on your best organic content." },
      { title: "Measurable outcomes", text: "Reporting tied to leads, orders and cost per acquisition." },
    ],
    offerings: [
      { title: "Content & calendar", text: "Monthly content plan across the platforms that matter for your audience." },
      { title: "Creative production", text: "Photography, reels, carousels and short-form video." },
      { title: "Community management", text: "Comments, DMs and reviews handled with SLA response times." },
      { title: "Paid social", text: "Instagram, Facebook, TikTok, LinkedIn and YouTube campaigns." },
    ],
    deliverables: [
      "Monthly content calendar with themes, hooks and CTAs",
      "Creative production package (posts, reels, stories)",
      "Community management with response-time targets",
      "Paid campaign build and weekly optimisation",
      "Monthly reporting on reach, engagement and conversions",
    ],
    process: campaignProcess,
    techStack: ["Meta Ads", "TikTok", "LinkedIn", "YouTube", "Google Analytics", "Figma"],
    whyUs: [
      { title: "Content + ads together", text: "Organic and paid managed by the same team, not two agencies." },
      { title: "Native creative", text: "Formats built for each platform, not a rectangular banner repurposed." },
      { title: "Honest reporting", text: "Attribution that shows real business impact, not vanity screenshots." },
      { title: "No lock-in", text: "Ad accounts, pixels and content belong to your business." },
    ],
    faqs: [
      { question: "Which platforms should we be on?", answer: "The platforms your customers actively use — usually two or three, not all of them. Instagram, TikTok and Facebook lead for consumer; LinkedIn and YouTube lead for B2B. We recommend after an audience audit." },
      { question: "Do you handle creative production?", answer: "Yes. Photography, short-form video, carousels and story assets are produced monthly or in themed batches." },
      { question: "How is this different from digital marketing?", answer: "Social media marketing focuses on the social channels themselves — content, community and paid social. Our broader digital marketing service covers Google Ads, SEO, landing pages and full-funnel attribution." },
    ],
    related: ["digital-marketing", "seo-services", "app-store-optimization", "ui-ux-design"],
    relatedPosts: ["seo-guide-for-businesses", "shopify-vs-custom-ecommerce-website"],
    projectCategory: "Websites",
  },
  {
    slug: "google-admob",
    title: "Google AdMob Integration & Management",
    shortTitle: "Google AdMob",
    icon: "marketing",
    h1: "Google AdMob Integration for Mobile App Monetisation",
    tagline:
      "AdMob integration, mediation setup and revenue optimisation for Android and iOS applications.",
    summary:
      "Mobile app monetisation with AdMob: SDK integration, ad unit strategy, mediation with multiple networks and revenue reporting.",
    metaTitle: "Google AdMob Integration Services | Mobile App Monetisation",
    metaDescription:
      "Google AdMob integration and management: SDK setup, ad unit strategy, mediation with multiple ad networks, eCPM optimisation and revenue reporting for Android and iOS apps.",
    primaryKeyword: "Google AdMob integration",
    keywords: [
      "Google AdMob integration",
      "AdMob mediation setup",
      "mobile app monetisation",
      "app advertising revenue",
      "AdMob eCPM optimisation",
    ],
    image: media.adsRevenue,
    imageAlt: "Analytics dashboard tracking mobile advertising revenue",
    overview: [
      "AdMob is the default choice for monetising mobile apps, but a bad integration destroys retention. Interstitials shown at the wrong moment kill user experience, rewarded ads placed thoughtlessly train users to skip, and missing mediation leaves 30–50% of revenue on the table.",
      "WordbitX integrates AdMob properly — with mediation across multiple networks, placements chosen against player experience data, and revenue tracked in a way you can actually optimise against.",
    ],
    whoNeeds: [
      "Free or freemium apps ready to monetise",
      "Games needing rewarded video and interstitial strategy",
      "Publishers wanting mediation across multiple ad networks",
      "Apps whose current ad revenue seems too low for their traffic",
      "Products replacing IAP-only revenue with hybrid monetisation",
    ],
    problems: [
      { title: "Ads that destroy retention", text: "Poorly timed interstitials cause churn. Placement is designed around session data, not guesswork." },
      { title: "Single-network dependence", text: "AdMob alone leaves money on the table. Mediation adds competing bidders." },
      { title: "Untracked revenue", text: "Without proper reporting, optimisation is impossible. We wire analytics from day one." },
    ],
    benefits: [
      { title: "Higher eCPM", text: "Mediation with multiple networks lifts revenue per impression." },
      { title: "Retained users", text: "Placement chosen so ads earn without pushing users to uninstall." },
      { title: "Rewarded strategy", text: "Rewarded video designed as a positive user experience." },
      { title: "Clean reporting", text: "Revenue tied to ad units, placements and user cohorts." },
    ],
    offerings: [
      { title: "AdMob SDK integration", text: "Correct implementation for iOS and Android with GDPR/CCPA consent." },
      { title: "Ad unit strategy", text: "Banner, interstitial, rewarded and native ad placement design." },
      { title: "Mediation setup", text: "AdMob mediation with Meta Audience Network, Unity, AppLovin and more." },
      { title: "Revenue optimisation", text: "eCPM floors, A/B testing and placement iteration." },
    ],
    deliverables: [
      "AdMob and mediation SDK integration with consent handling",
      "Ad placement plan documented against user flow",
      "eCPM baselines and optimisation targets",
      "Revenue dashboard with cohort and placement breakdown",
      "Post-launch review and iteration plan",
    ],
    process: [
      { step: "01", title: "Monetisation audit", text: "Current revenue, placements and retention data reviewed." },
      { step: "02", title: "Strategy", text: "Ad unit mix, mediation networks and placement plan agreed." },
      { step: "03", title: "Integration", text: "SDKs added with consent, tracking and safe defaults." },
      { step: "04", title: "Optimise", text: "eCPM floors and placement tests to lift revenue without hurting retention." },
    ],
    techStack: ["Google AdMob", "Meta Audience Network", "Unity Ads", "AppLovin", "Firebase", "Flutter"],
    whyUs: [
      { title: "Experience-first", text: "Placement decisions balance revenue against retention, not chase eCPM alone." },
      { title: "Mediation done properly", text: "Multiple networks with correct waterfall or bidding setup." },
      { title: "Analytics wired in", text: "Revenue attribution by placement, cohort and user segment." },
      { title: "App team on hand", text: "Integration happens with the same team that builds your app." },
    ],
    faqs: [
      { question: "Will ads hurt our app rating?", answer: "Only when they are placed badly. We choose placements based on user flow and monitor rating after launch. Rewarded video, correctly implemented, often improves ratings." },
      { question: "Can AdMob work with in-app purchases?", answer: "Yes. Hybrid monetisation — IAP for premium users, ads for free users — usually earns more than either alone. We design the split against your product." },
      { question: "How long until we see revenue?", answer: "AdMob approves accounts within days and revenue begins immediately after launch. Optimisation cycles run monthly to lift eCPM." },
    ],
    related: ["android-app-development", "ios-app-development", "mobile-app-development", "google-adsense"],
    relatedPosts: ["mobile-app-development-guide", "how-ai-automation-helps-businesses"],
    projectCategory: "Mobile Apps",
  },
  {
    slug: "google-adsense",
    title: "Google AdSense Setup & Optimisation",
    shortTitle: "Google AdSense",
    icon: "marketing",
    h1: "Google AdSense Setup for Website Monetisation",
    tagline:
      "AdSense approval, placement strategy and revenue optimisation for content websites and web applications.",
    summary:
      "Website monetisation with Google AdSense: approval preparation, ad placement, Core Web Vitals safety and RPM optimisation.",
    metaTitle: "Google AdSense Setup Services | Website Monetisation & Approval",
    metaDescription:
      "Google AdSense setup, approval preparation and revenue optimisation: policy compliance, ad placement, Core Web Vitals safety and RPM improvement for content websites.",
    primaryKeyword: "Google AdSense setup",
    keywords: [
      "Google AdSense setup",
      "AdSense approval services",
      "website monetisation",
      "AdSense RPM optimisation",
      "AdSense ad placement",
    ],
    image: media.adsAnalytics,
    imageAlt: "Website analytics and advertising performance dashboard on a laptop",
    overview: [
      "AdSense remains the most reliable way to monetise a content website — but only if the site passes policy review, uses ad placements that respect Core Web Vitals, and structures content in a way advertisers actually bid on.",
      "WordbitX prepares websites for AdSense approval, integrates ads without wrecking page speed, and optimises placements against real RPM data instead of guesswork.",
    ],
    whoNeeds: [
      "Content publishers, blogs and news sites",
      "Educational and review websites ready to monetise",
      "Sites rejected by AdSense that need policy remediation",
      "Existing AdSense publishers with low RPM",
      "Businesses adding a revenue layer to a high-traffic website",
    ],
    problems: [
      { title: "AdSense rejections", text: "Thin content, policy issues and navigation problems cause most rejections. We remediate before applying." },
      { title: "Ads that break Core Web Vitals", text: "Poor placements collapse LCP and CLS. We use lazy loading and layout reservations correctly." },
      { title: "Low RPM", text: "Random placements underperform. A tested placement plan lifts revenue per thousand views." },
    ],
    benefits: [
      { title: "Approval on first try", text: "Content, policy and technical checks completed before submission." },
      { title: "Fast pages", text: "Ads that respect Core Web Vitals and mobile experience." },
      { title: "Higher RPM", text: "Placement, sizes and auto-ads settings tuned to your content." },
      { title: "Compliant setup", text: "Consent management and privacy policy aligned with AdSense rules." },
    ],
    offerings: [
      { title: "AdSense approval prep", text: "Content, navigation, policy and consent readiness." },
      { title: "Placement strategy", text: "Ad units chosen per template, tested against RPM." },
      { title: "Performance safety", text: "Lazy loading, layout shift prevention and Core Web Vitals monitoring." },
      { title: "Ongoing optimisation", text: "Auto-ads tuning, ad experiment testing and reporting." },
    ],
    deliverables: [
      "AdSense-ready site with policy checklist completed",
      "Consent management (GDPR/CCPA) integrated",
      "Ad placement plan per template",
      "Core Web Vitals report before and after ads",
      "Monthly RPM and revenue optimisation report",
    ],
    process: [
      { step: "01", title: "Site audit", text: "Content, policy compliance and technical readiness reviewed." },
      { step: "02", title: "Approval prep", text: "Gaps fixed, consent installed, application submitted." },
      { step: "03", title: "Integration", text: "Ad units placed with Core Web Vitals safeguards." },
      { step: "04", title: "Optimise", text: "Placement testing and RPM improvements each cycle." },
    ],
    techStack: ["Google AdSense", "Google Analytics", "Search Console", "Tag Manager", "Next.js"],
    whyUs: [
      { title: "Performance-safe ads", text: "Ads that do not destroy your Core Web Vitals or mobile speed." },
      { title: "Policy expertise", text: "We know why AdSense rejects sites and fix it before submitting." },
      { title: "Data-driven placement", text: "RPM testing rather than opinions on ad positions." },
      { title: "Full stack in-house", text: "Integrated by the same team that maintains your site." },
    ],
    faqs: [
      { question: "How long does AdSense approval take?", answer: "Once a site is properly prepared, approval usually takes 1–2 weeks. Sites with existing policy or content issues can take longer while remediation happens." },
      { question: "Will AdSense slow our site?", answer: "Not when integrated correctly. Lazy loading, deferred script execution and reserved layout space keep Core Web Vitals healthy." },
      { question: "Do you handle both AdSense and AdMob?", answer: "Yes — AdSense for websites, AdMob for mobile apps. Both are managed by the same team when you run web and app together." },
    ],
    related: ["seo-services", "web-development", "wordpress-development", "google-admob"],
    relatedPosts: ["how-to-get-google-adsense-approval", "website-speed-and-seo"],
    projectCategory: "Websites",
  },
  {
    slug: "google-play-console",
    title: "Google Play Console Management",
    shortTitle: "Google Play Console",
    icon: "aso",
    h1: "Google Play Console Publishing & App Management",
    tagline:
      "Play Store submission, release management, staged rollouts and review-team responses handled end to end.",
    summary:
      "Google Play Console management: app submission, staged rollouts, in-app updates, policy compliance and review-team handling.",
    metaTitle: "Google Play Console Publishing Services | Android App Submission",
    metaDescription:
      "Google Play Console management: app submission, staged rollouts, data safety declarations, policy compliance, review-team handling and versioned release management.",
    primaryKeyword: "Google Play Console publishing",
    keywords: [
      "Google Play Console publishing",
      "Android app publishing services",
      "Play Store submission",
      "app release management",
      "Google Play policy compliance",
    ],
    image: media.androidInterface,
    imageAlt: "Android smartphone interface managed through the Google Play Console",
    overview: [
      "Publishing an Android app is not just uploading an AAB. Play Console requires data safety declarations, target API compliance, policy screening for permissions and content, and — for regulated categories — additional verification. Missing any of it delays the launch by weeks.",
      "WordbitX handles the Play Console process end to end: preparing the listing, submitting correctly the first time, responding to review-team messages on your behalf, and running staged rollouts so a bad build never reaches every user at once.",
    ],
    whoNeeds: [
      "Startups launching their first Android app",
      "Businesses whose previous submissions were rejected",
      "Products in regulated categories needing extra verification",
      "Apps needing staged rollouts and in-app update flows",
      "Teams that want release management taken off their plate",
    ],
    problems: [
      { title: "Rejections and takedowns", text: "Data safety and permission issues cause most rejections. We prepare submissions to Play's current standards." },
      { title: "Unstaged releases blow up", text: "Pushing a bad build to 100% of users is a disaster. Staged rollouts contain the damage." },
      { title: "Ignored review messages", text: "Play communicates through the console, not email. We monitor and respond quickly." },
    ],
    benefits: [
      { title: "First-time approval", text: "Correct data safety, permissions and store listing prepared upfront." },
      { title: "Safer releases", text: "Staged rollouts and in-app updates protect users from bad versions." },
      { title: "Faster resolution", text: "We respond to review-team messages within business hours." },
      { title: "Ownership retained", text: "Everything published under your Play Console developer account." },
    ],
    offerings: [
      { title: "Store listing prep", text: "Metadata, screenshots, feature graphic and preview video." },
      { title: "Policy compliance", text: "Data safety, permissions declaration and target API checks." },
      { title: "Release management", text: "Internal, closed, open testing and staged production rollouts." },
      { title: "Ongoing publishing", text: "Version updates, changelog management and review handling." },
    ],
    deliverables: [
      "Google Play Console developer account setup under your business",
      "Store listing configured with metadata and creative assets",
      "Data safety and permissions declarations completed",
      "Signed release with staged rollout plan",
      "Post-launch monitoring and response playbook",
    ],
    process: publishingProcess,
    techStack: ["Google Play Console", "Firebase App Distribution", "Fastlane", "Android", "Kotlin"],
    whyUs: [
      { title: "Submission-first thinking", text: "Compliance and policy considered during build, not after rejection." },
      { title: "Review-team fluency", text: "We know how Play reviewers write, what they ask, and how to respond." },
      { title: "Staged discipline", text: "Rollouts scaled 1% → 5% → 20% → 100% with crash monitoring at each step." },
      { title: "Handover-ready", text: "Documentation so your team can take over publishing when ready." },
    ],
    faqs: [
      { question: "Do we need our own Google Play developer account?", answer: "Yes, and you should own it. Google requires the developer account to represent the business, and it is where all reviews, revenue and downloads live. We handle setup and verification for you." },
      { question: "How long does Play submission take?", answer: "First submissions in most categories complete within a few days. Regulated categories (finance, health, gambling) require additional verification and can take 2–4 weeks." },
      { question: "Can you publish an app we built elsewhere?", answer: "Yes. We audit the build for Play compliance, prepare the listing and handle submission — even for apps built by other teams." },
    ],
    related: ["android-app-development", "app-store-optimization", "app-store-publishing", "mobile-app-development"],
    relatedPosts: ["mobile-app-development-guide", "seo-guide-for-businesses"],
    projectCategory: "Mobile Apps",
  },
  {
    slug: "app-store-publishing",
    title: "Apple App Store Publishing",
    shortTitle: "Apple App Store Publishing",
    icon: "aso",
    h1: "Apple App Store Submission & Publishing Services",
    tagline:
      "App Store Connect setup, review-team submission, TestFlight rollout and IAP compliance handled end to end.",
    summary:
      "Apple App Store publishing: developer account setup, App Store Connect configuration, review submission, TestFlight distribution and in-app purchase compliance.",
    metaTitle: "Apple App Store Publishing Services | iOS App Submission",
    metaDescription:
      "Apple App Store publishing services: developer account setup, App Store Connect configuration, review-team submission, TestFlight distribution and in-app purchase compliance.",
    primaryKeyword: "Apple App Store publishing",
    keywords: [
      "Apple App Store publishing",
      "iOS app publishing services",
      "App Store submission",
      "TestFlight distribution",
      "App Store review team",
    ],
    image: media.iosInterface,
    imageAlt: "iPhone home screen showing published apps from the Apple App Store",
    overview: [
      "Apple's review team is the strictest gatekeeper in mobile. Privacy manifests, purpose strings, third-party SDK declarations, IAP rules and the Human Interface Guidelines all get checked — and rejections often demand rework rather than clarifications.",
      "WordbitX prepares App Store submissions the way Apple expects them: privacy documents complete, TestFlight betas run first, IAP configured correctly, and reviewer replies drafted in the language the review team responds to.",
    ],
    whoNeeds: [
      "Startups shipping their first iOS app",
      "Businesses whose previous submissions were rejected",
      "Products with in-app purchases or subscriptions",
      "Apps distributed via Apple Business Manager or education",
      "Teams that want release management taken off their plate",
    ],
    problems: [
      { title: "Rejections that need rework", text: "Missing purpose strings, wrong IAP setup and HIG violations cause most rejections. Prevention beats appeal." },
      { title: "TestFlight surprises", text: "Untested builds surprise real users. Structured beta cycles catch problems first." },
      { title: "Subscription mis-implementation", text: "IAP restore flows, family sharing and receipt validation are strict — mistakes cause removal." },
    ],
    benefits: [
      { title: "Fewer rejection cycles", text: "Submissions prepared against the current App Review Guidelines." },
      { title: "Structured beta", text: "TestFlight cohorts with feedback captured before public launch." },
      { title: "Correct IAP", text: "Subscriptions, one-time purchases and restore flows tested end to end." },
      { title: "Ownership retained", text: "Everything under your Apple Developer Program account." },
    ],
    offerings: [
      { title: "Developer account setup", text: "Apple Developer Program enrolment under your business entity." },
      { title: "App Store Connect config", text: "Metadata, screenshots, app previews and privacy answers." },
      { title: "TestFlight distribution", text: "Internal and external beta cohorts with feedback capture." },
      { title: "Review submission", text: "Submission, reviewer response handling and phased release." },
    ],
    deliverables: [
      "Apple Developer Program account under your business",
      "App Store Connect listing with metadata and creative assets",
      "Privacy manifests and purpose strings verified",
      "TestFlight beta with structured cohorts",
      "Signed release with phased rollout plan",
    ],
    process: publishingProcess,
    techStack: ["App Store Connect", "TestFlight", "Fastlane", "Swift", "SwiftUI", "Xcode"],
    whyUs: [
      { title: "Review-team fluency", text: "We know why Apple rejects, and how to write replies that succeed." },
      { title: "Privacy first", text: "Manifests, tracking declarations and consent handled properly." },
      { title: "IAP done right", text: "Subscriptions and restores tested against Apple's rules, not just happy path." },
      { title: "Business-owned assets", text: "Developer account, app record and revenue stay with you." },
    ],
    faqs: [
      { question: "Do we need our own Apple Developer account?", answer: "Yes — it must be under your business entity for the store listing to represent the company. We handle the enrolment paperwork including D-U-N-S if needed." },
      { question: "How long does App Store review take?", answer: "Standard reviews complete within 24–48 hours. First-time apps and IAP-heavy apps can take longer. We prepare submissions to minimise back-and-forth." },
      { question: "Can you publish an existing app?", answer: "Yes. We audit the build for App Store compliance, fix any gaps, then submit and handle reviewer responses." },
    ],
    related: ["ios-app-development", "app-store-optimization", "google-play-console", "mobile-app-development"],
    relatedPosts: ["mobile-app-development-guide", "seo-guide-for-businesses"],
    projectCategory: "Mobile Apps",
  },
];
