import type { Service } from "@/lib/types";
import { media } from "@/lib/media";

export const servicesB: Service[] = [
  {
    slug: "digital-marketing",
    title: "Digital Marketing",
    shortTitle: "Digital Marketing",
    icon: "marketing",
    h1: "Digital Marketing Services Built Around Revenue, Not Vanity Metrics",
    tagline:
      "Paid media, social and content programmes measured on qualified leads and cost per acquisition.",
    summary:
      "Performance marketing, social media and content campaigns with clean tracking and honest reporting.",
    metaTitle: "Digital Marketing Agency | Performance & Social Media Marketing Services",
    metaDescription:
      "Digital marketing services from WordBitX: Google Ads, Meta ads, social media marketing, content and conversion tracking focused on qualified leads and ROI.",
    primaryKeyword: "digital marketing services",
    keywords: [
      "digital marketing agency",
      "digital marketing services",
      "social media marketing services",
      "PPC management services",
      "performance marketing agency",
    ],
    image: media.analyticsChart,
    imageAlt: "Marketing performance charts and campaign analytics on a mobile device",
    overview: [
      "Impressions do not pay salaries. WordBitX runs digital marketing as a measurable system: correct tracking first, then campaigns, creative and landing pages that can be judged on cost per qualified lead.",
      "We work in tight loops — test, read the data, cut what fails and scale what works. You get a dashboard showing spend, leads and pipeline instead of a slide deck full of reach numbers.",
    ],
    whoNeeds: [
      "Businesses spending on ads without knowing which campaigns produce sales",
      "Companies with a new website that needs immediate demand",
      "E-commerce brands scaling acquisition profitably",
      "B2B teams generating qualified enquiries",
      "Local service businesses competing in a defined area",
    ],
    problems: [
      { title: "Untrackable spend", text: "Broken tags and missing conversion events make optimisation guesswork. We rebuild measurement first." },
      { title: "Leads that never close", text: "Wrong targeting fills the pipeline with unqualified enquiries. We optimise toward sales-qualified outcomes." },
      { title: "Traffic sent to weak pages", text: "Great ads on a poor landing page still fail. We fix the destination, not just the campaign." },
    ],
    benefits: [
      { title: "Trustworthy measurement", text: "Server-side friendly tracking, conversion events and channel attribution you can act on." },
      { title: "Lower acquisition cost", text: "Continuous testing of audiences, creative and offers reduces cost per lead." },
      { title: "Aligned landing pages", text: "Ad message and page promise match, which lifts quality score and conversion." },
      { title: "Clear reporting", text: "Monthly reporting in plain language, including what did not work." },
    ],
    offerings: [
      { title: "Google Ads", text: "Search, Performance Max, shopping and remarketing campaigns." },
      { title: "Meta & social ads", text: "Facebook, Instagram, TikTok and LinkedIn campaign management." },
      { title: "Social media management", text: "Content calendars, creative production and community engagement." },
      { title: "Analytics & CRO", text: "GA4, Tag Manager, funnel analysis and landing page testing." },
    ],
    deliverables: [
      "Tracking and conversion measurement setup",
      "Campaign structure with budget allocation plan",
      "Ad creative and copy variants for testing",
      "Landing page recommendations or builds",
      "Monthly performance dashboard",
      "Strategy review call with next-cycle priorities",
    ],
    process: [
      { step: "01", title: "Audit & tracking", text: "Review existing accounts, fix measurement, define success metrics." },
      { step: "02", title: "Strategy", text: "Audience, offer, channel mix and budget plan." },
      { step: "03", title: "Launch", text: "Campaign build, creative production and landing page alignment." },
      { step: "04", title: "Optimise", text: "Weekly review of spend, creative fatigue and search terms." },
      { step: "05", title: "Scale", text: "Increase budget only on channels with proven unit economics." },
    ],
    techStack: ["Google Ads", "Google Analytics", "Tag Manager", "Meta Ads", "Semrush", "Next.js"],
    whyUs: [
      { title: "Measurement before spend", text: "We refuse to scale budget on broken tracking." },
      { title: "In-house build capability", text: "Landing pages and funnels are built by the same team, so fixes ship fast." },
      { title: "Honest reporting", text: "You see failures and learnings, not only the best-looking chart." },
      { title: "No lock-in", text: "Ad accounts, pixels and data stay in your ownership." },
    ],
    faqs: [
      { question: "What budget should we start with?", answer: "Enough to gather statistically useful data — typically a defined test budget over 6–8 weeks. We size it against your average order value and sales cycle during the audit." },
      { question: "Do you guarantee lead volume?", answer: "No responsible agency can guarantee results before seeing performance data. We commit to correct measurement, disciplined testing and transparent reporting, then set realistic targets after the first cycle." },
      { question: "Can you work with our internal team?", answer: "Yes. We often run paid media while your team handles brand content, or act as the technical layer supporting an in-house marketer." },
    ],
    related: ["google-ads", "facebook-instagram-ads", "seo-services", "content-marketing"],
    relatedPosts: ["seo-guide-for-businesses", "shopify-vs-custom-ecommerce-website"],
    projectCategory: "Websites",
  },
  {
    slug: "seo-services",
    title: "Search Engine Optimization",
    shortTitle: "SEO Services",
    icon: "seo",
    h1: "SEO Services That Build Compounding Organic Traffic",
    tagline:
      "Technical SEO, content architecture and internal linking that make your site easy to crawl, understand and rank.",
    summary:
      "Technical SEO fixes, keyword-led content structures and on-page optimisation that grow qualified organic traffic.",
    metaTitle: "SEO Services Company | Technical & On-Page SEO Agency",
    metaDescription:
      "SEO services from WordBitX: technical SEO audits, Core Web Vitals fixes, keyword strategy, on-page optimisation, schema and content architecture for sustainable rankings.",
    primaryKeyword: "SEO services",
    keywords: [
      "SEO services",
      "SEO company",
      "search engine optimization services",
      "technical SEO services",
      "on-page SEO agency",
    ],
    image: media.stockCharts,
    imageAlt: "Analytics report showing organic search growth trends",
    overview: [
      "SEO is not a monthly report of keyword positions. It is a set of engineering and content decisions that make your site the most useful, fastest and best-structured answer for a search query.",
      "WordBitX combines technical work — crawlability, speed, indexation, schema, internal links — with content built for real search intent. Because we also build websites, fixes get implemented instead of sitting in a recommendation document.",
    ],
    whoNeeds: [
      "Sites with pages that Google is not indexing",
      "Businesses depending entirely on paid ads for leads",
      "Companies that lost traffic after a redesign or migration",
      "Stores with thousands of URLs and crawl-budget waste",
      "Brands entering competitive international markets",
    ],
    problems: [
      { title: "Pages not indexed", text: "Blocked resources, thin content and orphan URLs keep pages out of the index. We diagnose and resolve at the source." },
      { title: "Slow Core Web Vitals", text: "Poor LCP and CLS hurt users first and rankings second. We fix them in code, not with plugins." },
      { title: "Content with no strategy", text: "Publishing without intent mapping creates cannibalisation. We build topic clusters with clear internal linking." },
    ],
    benefits: [
      { title: "Sustainable traffic", text: "Organic visits keep arriving after the campaign budget stops." },
      { title: "Better crawl efficiency", text: "Clean sitemaps, canonicals and internal links help search engines find what matters." },
      { title: "Rich results eligibility", text: "Valid schema for organisation, articles, FAQs, products and breadcrumbs." },
      { title: "Higher quality leads", text: "Intent-matched pages attract visitors already looking for your service." },
    ],
    offerings: [
      { title: "Technical SEO audits", text: "Crawl analysis, indexation, speed, structured data and mobile usability." },
      { title: "Keyword & intent research", text: "Topic clusters mapped to real business services and buying stages." },
      { title: "On-page optimisation", text: "Titles, metadata, headings, internal links and content depth improvements." },
      { title: "Migration SEO", text: "URL mapping, redirect strategy and post-launch indexing validation." },
    ],
    deliverables: [
      "Prioritised technical audit with implementation notes",
      "Keyword map by page and search intent",
      "Optimised titles, metadata and heading structures",
      "Schema markup implementation",
      "Internal linking plan across services and blog",
      "Search Console and analytics monitoring setup",
    ],
    process: [
      { step: "01", title: "Audit", text: "Technical crawl, content inventory and competitor gap analysis." },
      { step: "02", title: "Strategy", text: "Keyword map, page-level targets and a content roadmap." },
      { step: "03", title: "Fix", text: "Technical corrections and on-page optimisation shipped by developers." },
      { step: "04", title: "Publish", text: "New pages and articles built on the approved architecture." },
      { step: "05", title: "Measure", text: "Monthly reporting on impressions, clicks, positions and conversions." },
    ],
    techStack: ["Next.js", "Search Console", "Google Analytics", "Semrush", "Tag Manager", "Cloudflare"],
    whyUs: [
      { title: "We can implement", text: "Developers and SEOs on one team means fixes ship in days, not quarters." },
      { title: "No black-hat shortcuts", text: "No link schemes or spun content that risk manual actions." },
      { title: "Business-relevant keywords", text: "We chase queries that produce enquiries, not high-volume vanity terms." },
      { title: "Transparent reporting", text: "Search Console data, not made-up rank-tracker averages." },
    ],
    faqs: [
      { question: "How long before we see SEO results?", answer: "Technical fixes can show impact within weeks. Competitive rankings and content-driven growth generally take four to six months of consistent work. Anyone promising page one in 30 days is guessing." },
      { question: "Do you guarantee number one rankings?", answer: "No. Nobody controls Google's ranking systems. We guarantee the work: a technically sound, well-structured, genuinely useful site that competes on merit." },
      { question: "Can you fix SEO on our existing website?", answer: "Yes. Most engagements start with an audit of your current site, and we implement fixes directly or hand precise instructions to your developers." },
    ],
    related: ["technical-seo", "local-seo", "website-speed-optimization", "content-marketing"],
    relatedPosts: ["seo-guide-for-businesses", "how-to-choose-a-web-development-company"],
    projectCategory: "Websites",
    featured: true,
  },
  {
    slug: "app-store-optimization",
    title: "App Store Optimization",
    shortTitle: "App Store Optimization",
    icon: "aso",
    h1: "App Store Optimization Services for Google Play & the App Store",
    tagline:
      "Store listings, keyword metadata and creative testing that turn store impressions into installs.",
    summary:
      "ASO strategy covering keyword metadata, screenshots, ratings and conversion testing across both app stores.",
    metaTitle: "App Store Optimization Services | ASO Agency for iOS & Android",
    metaDescription:
      "ASO services from WordBitX: keyword research, store listing optimisation, screenshot and icon testing, review management and install conversion improvement.",
    primaryKeyword: "app store optimization services",
    keywords: [
      "app store optimization services",
      "ASO services",
      "Google Play ASO",
      "Apple App Store optimization",
      "app marketing agency",
    ],
    image: media.appIcons,
    imageAlt: "Smartphone home screen showing app icons and store listings",
    overview: [
      "Most apps are discovered inside the stores, not through advertising. App Store Optimization decides whether your listing appears for relevant searches and whether the people who see it actually install.",
      "WordBitX treats ASO as two connected problems: visibility (keywords, category, ratings, localisation) and conversion (icon, screenshots, first three lines of the description). Both are tested continuously against store analytics.",
    ],
    whoNeeds: [
      "Newly launched apps with low organic install volume",
      "Apps with impressions but a weak install conversion rate",
      "Products expanding into new language markets",
      "Teams paying for installs that could come organically",
      "Apps with low ratings damaging store ranking",
    ],
    problems: [
      { title: "Invisible in store search", text: "Weak titles, subtitles and keyword fields mean no impressions. We rebuild metadata around real search terms." },
      { title: "Low install conversion", text: "Generic screenshots fail to communicate value in two seconds. We design benefit-led creative sets." },
      { title: "Ratings dragging ranking down", text: "No review prompts and unanswered complaints hurt visibility. We add timing-based prompts and response workflows." },
    ],
    benefits: [
      { title: "More organic installs", text: "Better keyword coverage brings qualified store traffic without ad spend." },
      { title: "Higher conversion rate", text: "Tested creative increases the share of visitors who install." },
      { title: "Lower paid CPI", text: "A stronger listing improves the efficiency of any paid user acquisition." },
      { title: "Better ratings", text: "Structured prompts and review responses lift average scores over time." },
    ],
    offerings: [
      { title: "Store keyword research", text: "Search volume and difficulty analysis for both stores." },
      { title: "Listing optimisation", text: "Titles, subtitles, keyword fields, descriptions and localisation." },
      { title: "Creative sets", text: "Icon, screenshots and preview videos designed around key benefits." },
      { title: "Rating & review programme", text: "In-app prompt strategy and response templates." },
    ],
    deliverables: [
      "ASO audit for existing listings",
      "Keyword map per store and per market",
      "Optimised metadata copy ready to publish",
      "Screenshot and icon design set",
      "Review response playbook",
      "Monthly install and conversion reporting",
    ],
    process: [
      { step: "01", title: "Listing audit", text: "Benchmark against competitors and store analytics." },
      { step: "02", title: "Keyword research", text: "Build ranked keyword sets per store and locale." },
      { step: "03", title: "Metadata & creative", text: "Rewrite listing copy and design new creative sets." },
      { step: "04", title: "Test", text: "Store experiments and staged rollouts to compare variants." },
      { step: "05", title: "Iterate", text: "Refresh keywords and creative each release cycle." },
    ],
    techStack: ["App Store", "Google Play", "Firebase", "Google Analytics", "Figma"],
    whyUs: [
      { title: "Built by app developers", text: "We understand release cycles, so ASO changes ship with your updates." },
      { title: "Creative and copy in-house", text: "Screenshot design and metadata come from the same team." },
      { title: "Data-driven testing", text: "Decisions based on store experiments, not opinions." },
      { title: "Localisation support", text: "Market-specific keywords rather than machine translation." },
    ],
    faqs: [
      { question: "How is ASO different from SEO?", answer: "ASO optimises listings inside Google Play and the App Store — metadata, creative, ratings and installs. SEO targets web search. They share research logic but use different ranking signals." },
      { question: "How quickly does ASO work?", answer: "Metadata changes typically show keyword movement within two to four weeks. Creative testing needs enough traffic to reach significance, so plan on a two to three month cycle." },
      { question: "Do you also run paid app campaigns?", answer: "Yes, through our digital marketing team. A strong listing makes paid installs measurably cheaper, so we usually fix ASO first." },
    ],
    related: ["mobile-app-development", "digital-marketing", "seo-services", "ui-ux-design"],
    relatedPosts: ["mobile-app-development-guide", "seo-guide-for-businesses"],
    projectCategory: "Mobile Apps",
  },
  {
    slug: "wordpress-development",
    title: "WordPress Development",
    shortTitle: "WordPress Development",
    icon: "wordpress",
    h1: "WordPress Development Company for Fast, Secure, Editable Sites",
    tagline:
      "Custom WordPress themes and blocks — lightweight, secure and genuinely easy for your marketing team to run.",
    summary:
      "Custom WordPress themes, block editor setups, WooCommerce stores, speed optimisation and ongoing maintenance.",
    metaTitle: "WordPress Development Company | Custom WordPress Websites",
    metaDescription:
      "Custom WordPress development services: bespoke themes, Gutenberg blocks, WooCommerce, speed and security hardening, migrations and monthly maintenance.",
    primaryKeyword: "WordPress development company",
    keywords: [
      "WordPress development company",
      "custom WordPress development",
      "WordPress website design",
      "WooCommerce development",
      "WordPress maintenance services",
    ],
    image: media.htmlEditor,
    imageAlt: "Developer building a custom WordPress theme in a code editor",
    overview: [
      "WordPress is excellent when it is built properly and painful when it is not. Most slow WordPress sites are not WordPress problems — they are twenty-plugin problems layered over a page builder.",
      "WordBitX builds custom themes and block patterns with minimal dependencies, so editors get flexible content control while the site stays fast, secure and cheap to maintain.",
    ],
    whoNeeds: [
      "Content and marketing teams publishing regularly",
      "Businesses on a page builder site that has become slow",
      "Sites needing WooCommerce with custom requirements",
      "Companies with security or malware issues",
      "Organisations wanting multilingual or multisite setups",
    ],
    problems: [
      { title: "Plugin bloat", text: "Dozens of overlapping plugins slow the site and expand the attack surface. We replace them with lean custom code." },
      { title: "Page builder lock-in", text: "Content trapped in shortcodes cannot be migrated. We use native blocks and clean markup." },
      { title: "Security incidents", text: "Outdated cores and nulled themes invite malware. We harden, monitor and maintain." },
    ],
    benefits: [
      { title: "Fast page loads", text: "Optimised queries, caching, image handling and minimal scripts." },
      { title: "Editor freedom", text: "Custom blocks and patterns let marketers build pages without breaking design." },
      { title: "Stronger security", text: "Hardening, least-privilege roles, backups and update discipline." },
      { title: "SEO friendly", text: "Clean templates, schema, sitemaps and correct heading structure." },
    ],
    offerings: [
      { title: "Custom theme development", text: "Bespoke themes built to your design with reusable block patterns." },
      { title: "WooCommerce", text: "Product, checkout and payment customisation for WordPress stores." },
      { title: "Speed & security", text: "Performance tuning, malware cleanup and hardening." },
      { title: "Care plans", text: "Updates, backups, uptime monitoring and monthly content support." },
    ],
    deliverables: [
      "Custom theme with reusable block patterns",
      "Editor documentation and content guidelines",
      "SEO plugin configuration and schema",
      "Performance report with before/after metrics",
      "Automated backup and staging environment",
      "Security hardening checklist",
    ],
    process: [
      { step: "01", title: "Audit or discovery", text: "Review current site or define the new content model." },
      { step: "02", title: "Design mapping", text: "Translate designs into reusable block components." },
      { step: "03", title: "Theme build", text: "Custom theme development with minimal plugin dependencies." },
      { step: "04", title: "Content & QA", text: "Migration, cross-browser testing and speed validation." },
      { step: "05", title: "Launch & care", text: "Deployment, monitoring and an optional maintenance plan." },
    ],
    techStack: ["WordPress", "WooCommerce", "PHP", "MySQL", "JavaScript", "Tailwind CSS", "Cloudflare"],
    whyUs: [
      { title: "Custom over template", text: "We build themes rather than reskinning bought ones." },
      { title: "Editor training included", text: "Your team leaves knowing how to run the site." },
      { title: "Performance accountability", text: "We publish before-and-after Core Web Vitals." },
      { title: "Long-term care", text: "Maintenance plans keep the site patched and backed up." },
    ],
    faqs: [
      { question: "Should we use WordPress or a custom build?", answer: "WordPress is ideal for content-heavy marketing sites with frequent publishing. A custom application is better for complex logic, dashboards or product platforms. We recommend based on your content and feature needs." },
      { question: "Can you fix our slow WordPress site?", answer: "Usually yes. We audit plugins, database queries, images and hosting, then remove or replace what is causing the slowdown, often without a full rebuild." },
      { question: "Do you offer ongoing maintenance?", answer: "Yes. Care plans include core and plugin updates, security monitoring, backups, uptime checks and a monthly allowance for content changes." },
    ],
    related: ["woocommerce-development", "custom-cms-development", "seo-services", "web-development"],
    relatedPosts: ["how-to-choose-a-web-development-company", "seo-guide-for-businesses"],
    projectCategory: "Websites",
  },
  {
    slug: "crm-erp-solutions",
    title: "CRM & ERP Solutions",
    shortTitle: "CRM & ERP",
    icon: "crm",
    h1: "Custom CRM & ERP Software Solutions for Operational Control",
    tagline:
      "Sales pipelines, inventory, finance and HR in one system your team will actually use every day.",
    summary:
      "Custom CRM and ERP platforms — or tailored implementations — that unify sales, operations and reporting.",
    metaTitle: "CRM & ERP Development | Custom Business Management Software",
    metaDescription:
      "Custom CRM and ERP software development: sales pipelines, inventory, procurement, finance and HR modules with dashboards, permissions and integrations.",
    primaryKeyword: "CRM development",
    keywords: [
      "CRM development",
      "ERP software solutions",
      "custom CRM software",
      "business management software",
      "ERP development company",
    ],
    image: media.officeTeam,
    imageAlt: "Business team reviewing CRM dashboards and operational reports",
    overview: [
      "CRM manages relationships and revenue. ERP manages resources and operations. Most growing businesses need part of both, and buying two rigid platforms usually creates a third problem: keeping them in sync.",
      "WordBitX builds tailored CRM and ERP systems — or extends what you already run — so leads, orders, stock, invoices and staff data live in one connected model with permissions and reporting your managers trust.",
    ],
    whoNeeds: [
      "Sales teams tracking pipelines in spreadsheets",
      "Manufacturers and distributors managing stock and procurement",
      "Service companies handling contracts, jobs and invoicing",
      "Businesses with data scattered across disconnected tools",
      "Companies whose SaaS licences grow faster than revenue",
    ],
    problems: [
      { title: "Leads falling through cracks", text: "No follow-up structure loses deals silently. Pipelines with reminders and ownership fix accountability." },
      { title: "Disconnected departments", text: "Sales promises what operations cannot deliver. Shared data removes the guesswork." },
      { title: "Reporting nobody trusts", text: "Manual consolidation produces different numbers per department. One database ends the argument." },
    ],
    benefits: [
      { title: "One connected system", text: "Customers, orders, inventory and invoices share a single data model." },
      { title: "Process automation", text: "Approvals, notifications and recurring tasks run without manual chasing." },
      { title: "Role-based control", text: "Every user sees only what their role requires, with full audit history." },
      { title: "Decision-ready reporting", text: "Live dashboards for revenue, stock, receivables and team performance." },
    ],
    offerings: [
      { title: "Custom CRM", text: "Lead capture, pipelines, quotations, follow-ups and customer history." },
      { title: "ERP modules", text: "Inventory, procurement, production, finance, HR and payroll." },
      { title: "Integrations", text: "Website forms, POS, accounting software, email, SMS and WhatsApp." },
      { title: "Migration & rollout", text: "Data cleanup, import, training and phased department onboarding." },
    ],
    deliverables: [
      "Module and permission matrix documentation",
      "Configured CRM pipelines and automation rules",
      "ERP modules matched to your operating process",
      "Management dashboards and scheduled reports",
      "Data migration from existing tools",
      "Department-level training and admin guide",
    ],
    process: [
      { step: "01", title: "Operational audit", text: "Map departments, handoffs, approvals and reporting needs." },
      { step: "02", title: "Module design", text: "Decide build vs configure per module and define the data model." },
      { step: "03", title: "Phased build", text: "Deliver the highest-pain module first, then expand." },
      { step: "04", title: "Migration & training", text: "Clean and import data, then train by role." },
      { step: "05", title: "Adoption support", text: "Usage monitoring, refinements and continued enhancement." },
    ],
    techStack: ["Node.js", "TypeScript", "Laravel", "PostgreSQL", "MySQL", "React", "Docker", "AWS"],
    whyUs: [
      { title: "Adoption-focused design", text: "A system nobody uses is wasted spend, so we design for daily usability." },
      { title: "Phase by pain", text: "We start where the cost of the current process is highest." },
      { title: "Honest build-vs-buy advice", text: "If an existing platform fits, we will tell you and implement it." },
      { title: "Reporting your managers trust", text: "Definitions agreed with finance before dashboards are built." },
    ],
    faqs: [
      { question: "CRM or ERP — which do we need first?", answer: "If revenue leaks from poor follow-up, start with CRM. If cost and delivery problems come from stock, procurement or production, start with ERP. Most businesses phase one then the other." },
      { question: "Can you customise an existing platform instead?", answer: "Yes. We extend and integrate platforms you already use when that is the pragmatic choice, and build custom only where the fit is genuinely poor." },
      { question: "How do you handle staff resistance?", answer: "Role-based training, phased rollout and involving department leads during design. Adoption is measured after launch and addressed with refinements." },
    ],
    related: ["custom-software-development", "inventory-management-software", "pos-software", "ai-solutions"],
    relatedPosts: ["crm-vs-erp-which-one-does-your-business-need", "inventory-management-software-guide"],
    projectCategory: "Software",
  },
  {
    slug: "game-development",
    title: "Game Development",
    shortTitle: "Game Development",
    icon: "game",
    h1: "Game Development Company for Mobile & Cross-Platform Games",
    tagline:
      "2D and 3D games, gamified apps and interactive experiences engineered for smooth frame rates on real devices.",
    summary:
      "Mobile and cross-platform game development: gameplay systems, monetisation, live-ops and store publishing.",
    metaTitle: "Game Development Company | Mobile & Cross-Platform Game Studio",
    metaDescription:
      "Game development services from WordBitX: 2D and 3D mobile games, gamified applications, multiplayer features, monetisation systems and app store publishing.",
    primaryKeyword: "game development company",
    keywords: [
      "game development company",
      "mobile game development",
      "2D game development",
      "3D game development",
      "gamification services",
    ],
    image: media.gameControllers,
    imageAlt: "Game controllers arranged for mobile and console game development",
    overview: [
      "Games live or die on feel. A half-second input delay or a frame-rate dip during a key moment costs you the player, no matter how good the art is.",
      "WordBitX builds mobile and cross-platform games with performance profiling from the first prototype: tuned physics and controls, memory-conscious asset pipelines, and monetisation designed so it does not ruin the experience.",
    ],
    whoNeeds: [
      "Studios and founders launching a mobile game concept",
      "Brands wanting a promotional or advergame experience",
      "Education and training companies building simulations",
      "Apps adding gamification to increase retention",
      "Teams needing multiplayer or leaderboard infrastructure",
    ],
    problems: [
      { title: "Poor performance on mid-range phones", text: "Most players are not on flagships. We profile and optimise for the devices your audience actually owns." },
      { title: "Weak retention after day one", text: "No progression loop means no reason to return. We design session goals and reward pacing." },
      { title: "Monetisation that annoys players", text: "Aggressive ads destroy ratings. We balance placement, rewarded video and in-app purchase design." },
    ],
    benefits: [
      { title: "Smooth gameplay", text: "Frame-rate budgets and profiling on target devices from prototype stage." },
      { title: "Designed retention loops", text: "Progression, rewards and events that create a reason to come back." },
      { title: "Balanced monetisation", text: "Ads, IAP and rewards tuned against player experience metrics." },
      { title: "Live-ops ready", text: "Remote config and analytics so content can be tuned after launch." },
    ],
    offerings: [
      { title: "2D & 3D mobile games", text: "Casual, hyper-casual, puzzle, arcade and simulation titles." },
      { title: "Gamified applications", text: "Points, streaks, levels and leaderboards inside business apps." },
      { title: "Multiplayer & backend", text: "Matchmaking, real-time sync, leaderboards and cloud saves." },
      { title: "Publishing & live-ops", text: "Store submission, analytics, remote config and content updates." },
    ],
    deliverables: [
      "Game design document with core loop definition",
      "Playable prototype for early validation",
      "Art pipeline and optimised asset bundles",
      "Backend for accounts, saves and leaderboards",
      "Analytics, ads and IAP integration",
      "Store-ready builds with performance report",
    ],
    process: [
      { step: "01", title: "Concept & GDD", text: "Core loop, target audience, platform and monetisation model." },
      { step: "02", title: "Prototype", text: "Grey-box build to prove the mechanic is fun before art investment." },
      { step: "03", title: "Production", text: "Art, levels, systems and backend built in milestone sprints." },
      { step: "04", title: "Optimisation & QA", text: "Device profiling, memory tuning and playtest feedback rounds." },
      { step: "05", title: "Launch & live-ops", text: "Soft launch, metrics review, then scaling and content updates." },
    ],
    techStack: ["Flutter", "Dart", "TypeScript", "Node.js", "Firebase", "PostgreSQL", "Google Play", "App Store"],
    whyUs: [
      { title: "Prototype before production", text: "We validate the mechanic before spending on art and content." },
      { title: "Real-device profiling", text: "Optimised for mid-range Android hardware, not just flagship demos." },
      { title: "Full backend capability", text: "Multiplayer, accounts and economy handled by the same team." },
      { title: "Post-launch partnership", text: "Live-ops support to keep the game earning after release." },
    ],
    faqs: [
      { question: "Can you build both 2D and 3D games?", answer: "Yes. We scope engine and pipeline choices around your concept, target devices and budget, covering casual 2D titles through to lightweight 3D experiences." },
      { question: "Do you handle art and sound?", answer: "Yes, through our design team and vetted specialist partners for music and voice, coordinated under one project plan." },
      { question: "How is a game project priced?", answer: "By milestone: concept and prototype first, then production phases. That lets you validate the core loop before committing to full production budget." },
    ],
    related: ["mobile-app-development", "ui-ux-design", "app-store-optimization", "devops-cloud-solutions"],
    relatedPosts: ["mobile-app-development-guide", "how-ai-automation-helps-businesses"],
    projectCategory: "Mobile Apps",
  },
  {
    slug: "devops-cloud-solutions",
    title: "DevOps & Cloud Solutions",
    shortTitle: "DevOps & Cloud",
    icon: "devops",
    h1: "DevOps & Cloud Solutions for Reliable, Scalable Infrastructure",
    tagline:
      "Automated pipelines, containerised environments and monitored cloud infrastructure that survives real traffic.",
    summary:
      "Cloud architecture, CI/CD automation, containerisation, monitoring and cost optimisation on AWS and Google Cloud.",
    metaTitle: "DevOps Services & Cloud Solutions | Infrastructure Engineering",
    metaDescription:
      "DevOps services and cloud solutions: AWS and Google Cloud architecture, CI/CD pipelines, Docker and Kubernetes, monitoring, security and cloud cost optimisation.",
    primaryKeyword: "DevOps services",
    keywords: [
      "DevOps services",
      "cloud solutions",
      "cloud infrastructure services",
      "CI/CD pipeline setup",
      "AWS cloud consulting",
    ],
    image: media.serverBlue,
    imageAlt: "Cloud infrastructure server racks powering scalable applications",
    overview: [
      "Software only creates value when it is running. WordBitX builds the delivery and infrastructure layer that gets code to production safely: automated pipelines, reproducible environments, monitoring that catches problems before customers do, and cost control that stops cloud bills drifting.",
      "Whether you need a first proper deployment setup or a rescue for infrastructure that breaks under load, we work with what you have and improve it incrementally rather than demanding a rewrite.",
    ],
    whoNeeds: [
      "Teams deploying manually over FTP or SSH",
      "Applications that slow down or crash during traffic spikes",
      "Companies with unpredictable and rising cloud bills",
      "Products needing staging, QA and production parity",
      "Businesses with no backup or disaster recovery plan",
    ],
    problems: [
      { title: "Risky manual deployments", text: "Hand-copied files cause outages and unrepeatable environments. Pipelines make releases boring and reversible." },
      { title: "No visibility when things break", text: "Without logs, metrics and alerts you learn from customers. We instrument the stack properly." },
      { title: "Cloud waste", text: "Oversized instances and forgotten resources inflate bills. Right-sizing and autoscaling cut spend." },
    ],
    benefits: [
      { title: "Safer releases", text: "Automated tests, staged rollouts and one-command rollback." },
      { title: "Elastic scaling", text: "Infrastructure that expands for peaks and shrinks when quiet." },
      { title: "Faster recovery", text: "Tested backups, documented runbooks and defined recovery objectives." },
      { title: "Lower cloud cost", text: "Continuous right-sizing, caching and storage lifecycle policies." },
    ],
    offerings: [
      { title: "Cloud architecture", text: "AWS and Google Cloud design for availability, security and cost." },
      { title: "CI/CD automation", text: "Build, test and deployment pipelines with environment promotion." },
      { title: "Containers & orchestration", text: "Docker images and Kubernetes or managed container platforms." },
      { title: "Monitoring & security", text: "Metrics, logs, alerts, backups and access hardening." },
    ],
    deliverables: [
      "Infrastructure diagram and environment plan",
      "Infrastructure-as-code configuration",
      "CI/CD pipelines for each environment",
      "Container images and deployment manifests",
      "Monitoring dashboards and alert rules",
      "Runbooks, backup policy and cost review",
    ],
    process: [
      { step: "01", title: "Assessment", text: "Review current hosting, deployment flow, risks and spend." },
      { step: "02", title: "Target architecture", text: "Design environments, scaling model and security boundaries." },
      { step: "03", title: "Automate", text: "Implement infrastructure as code and delivery pipelines." },
      { step: "04", title: "Migrate", text: "Move workloads with rollback plans and minimal downtime." },
      { step: "05", title: "Operate", text: "Monitoring, on-call runbooks and monthly cost optimisation." },
    ],
    techStack: ["AWS", "Google Cloud", "Docker", "Kubernetes", "GitHub", "Jenkins", "Cloudflare", "PostgreSQL"],
    whyUs: [
      { title: "Pragmatic scope", text: "We right-size the platform to your traffic instead of over-engineering." },
      { title: "Documented handover", text: "Runbooks and diagrams so your team is never dependent on tribal knowledge." },
      { title: "Security baked in", text: "Least-privilege access, secrets management and patching policy." },
      { title: "Cost transparency", text: "Monthly infrastructure cost review with reduction recommendations." },
    ],
    faqs: [
      { question: "Do we need Kubernetes?", answer: "Often not. Many products run better and cheaper on managed container services. We recommend Kubernetes only when scale, multi-service complexity or portability genuinely justify it." },
      { question: "Can you work with our existing cloud account?", answer: "Yes. We work inside your AWS or Google Cloud organisation so ownership, billing and access stay with you." },
      { question: "Do you offer ongoing infrastructure support?", answer: "Yes. Support plans include monitoring, incident response, patching, backup verification and monthly cost optimisation." },
    ],
    related: ["web-hosting", "website-security", "website-maintenance", "custom-software-development"],
    relatedPosts: ["custom-software-vs-ready-made-software", "how-ai-automation-helps-businesses"],
    projectCategory: "Software",
  },
  {
    slug: "inventory-management-software",
    title: "Inventory Management Software",
    shortTitle: "Inventory Management",
    icon: "inventory",
    h1: "Inventory Management Software That Matches Stock on Screen to Stock on Shelf",
    tagline:
      "Real-time stock control across warehouses, branches and sales channels — with batch, expiry and reorder automation.",
    summary:
      "Custom inventory and warehouse management systems with barcode operations, multi-location stock, batch tracking and purchase automation.",
    metaTitle: "Inventory Management Software Development | Warehouse & Stock Control",
    metaDescription:
      "Custom inventory management software by WordBitX: real-time multi-warehouse stock, barcode scanning, batch and expiry tracking, reorder automation and profit reporting.",
    primaryKeyword: "inventory management software",
    keywords: [
      "inventory management software",
      "warehouse management system",
      "stock management software",
      "inventory software development",
      "custom inventory system",
    ],
    image: media.warehouseScanning,
    imageAlt: "Warehouse operator scanning stock into an inventory management system on a tablet",
    overview: [
      "Almost every stock problem is really a data problem. Goods move physically — received, transferred, sold, returned, damaged, expired — but if the system only records some of those movements, the number on screen slowly drifts away from the number on the shelf. Once staff stop trusting it, they revert to manual counting and the software becomes decoration.",
      "WordBitX builds inventory systems where every movement is a transaction. Stock cannot change without a reason code, a user and a timestamp, which means the balance is always explainable. On top of that ledger we layer barcode operations, reorder rules, batch and expiry tracking, and reporting that shows which items actually earn money.",
    ],
    whoNeeds: [
      "Distributors and wholesalers managing warehouses and vans",
      "Retail chains needing accurate stock across multiple branches",
      "Pharmacies and food businesses tracking batches and expiry dates",
      "Manufacturers consuming raw materials against production orders",
      "Online sellers whose marketplace and store inventory drift apart",
    ],
    problems: [
      {
        title: "System stock never matches physical stock",
        text: "Untracked wastage, returns and transfers break the balance. A movement ledger with mandatory reason codes and cycle counts keeps the two aligned.",
      },
      {
        title: "Dead stock and stockouts at the same time",
        text: "Cash sits in slow items while bestsellers run out. Reorder points based on real sales velocity and lead time fix both ends.",
      },
      {
        title: "Expiry and batch losses",
        text: "Without batch-level visibility, near-expiry goods are discovered too late. FEFO picking and expiry alerts protect margin.",
      },
    ],
    benefits: [
      { title: "Stock you can trust", text: "Every unit traced to a document, a user and a timestamp — fully auditable." },
      { title: "Less capital locked up", text: "Reorder automation and ageing reports release cash tied to slow-moving inventory." },
      { title: "Faster counting", text: "Barcode-driven receiving, picking and cycle counts replace clipboard stock takes." },
      { title: "True profitability", text: "Landed cost, freight and wastage included so margin per item is real." },
    ],
    offerings: [
      { title: "Warehouse management", text: "Bins, racks, transfers, pick lists and goods-received workflows." },
      { title: "Batch & expiry tracking", text: "Lot numbers, FEFO picking, expiry alerts and recall traceability." },
      { title: "Procurement automation", text: "Reorder points, supplier lead times, purchase orders and GRN matching." },
      { title: "Channel sync", text: "Keeping POS, Shopify, WooCommerce and marketplace stock in one balance." },
    ],
    deliverables: [
      "Item master with units, variants, barcodes and landed cost",
      "Multi-warehouse stock ledger with full movement history",
      "Barcode receiving, picking, transfer and cycle-count screens",
      "Purchase orders, supplier ledger and GRN reconciliation",
      "Reorder alerts, ageing, wastage and valuation reports",
      "Role-based permissions with an approval trail",
    ],
    process: [
      { step: "01", title: "Stock audit", text: "Map how goods physically move today and where records break down." },
      { step: "02", title: "Data model", text: "Items, units, batches, locations, costing method and permissions." },
      { step: "03", title: "Build", text: "Ledger, barcode operations, procurement and reporting delivered in modules." },
      { step: "04", title: "Opening balances", text: "Physical count, data import and parallel running against the old process." },
      { step: "05", title: "Rollout", text: "Warehouse team training, then branch-by-branch go-live with support." },
    ],
    techStack: ["React", "TypeScript", "Node.js", "PostgreSQL", "Redis", "Flutter", "Docker", "AWS"],
    whyUs: [
      { title: "Ledger-first architecture", text: "Balances are derived from movements, so numbers can always be explained." },
      { title: "Built for the floor", text: "Scanner-friendly screens designed for gloves, dust and speed — not office desks." },
      { title: "Costing done properly", text: "FIFO or weighted average with landed cost, agreed with your accountant first." },
      { title: "Integrates, not replaces", text: "Connects to your POS, accounting and online stores instead of forcing a rip-out." },
    ],
    faqs: [
      {
        question: "Can it handle multiple warehouses and branches?",
        answer:
          "Yes. Stock is tracked per location with transfers, in-transit visibility and consolidated reporting, so head office sees one accurate picture across every site.",
      },
      {
        question: "Does it support barcodes and expiry dates?",
        answer:
          "Yes. Items can carry barcodes, batch or lot numbers and expiry dates, with FEFO picking, near-expiry alerts and full recall traceability for pharmacy and food businesses.",
      },
      {
        question: "Can it connect to our POS or online store?",
        answer:
          "Yes. We sync stock and orders with POS systems, Shopify, WooCommerce and marketplaces so a sale on any channel deducts from the same balance.",
      },
    ],
    related: ["pos-software", "crm-erp-solutions", "custom-software-development", "ecommerce-shopify"],
    relatedPosts: ["inventory-management-software-guide", "crm-vs-erp-which-one-does-your-business-need"],
    projectCategory: "Software",
    featured: true,
  },
];
