import type { Service } from "@/lib/types";
import { media } from "@/lib/media";
import { growthProcess, marketplaceProcess, withServiceDefaults } from "@/lib/service-builder";

export const servicesF: Service[] = [
  withServiceDefaults({
    slug: "amazon-store-setup",
    title: "Amazon Store Setup & Management",
    shortTitle: "Amazon Store",
    icon: "ecommerce",
    h1: "Amazon Store Setup and Seller Central Management",
    tagline:
      "Seller account, brand store, listings and Seller Central routines set up under your Amazon login — not a rented store you cannot take back.",
    summary:
      "Amazon seller account setup, listing optimisation, brand store and ongoing Seller Central support.",
    metaTitle: "Amazon Store Setup & Seller Central Management",
    metaDescription:
      "Amazon store setup and Seller Central support from WordbitX: seller account, listings, A+ content, brand store and catalogue management under your Amazon login.",
    primaryKeyword: "Amazon store setup",
    keywords: [
      "Amazon store setup",
      "Amazon Seller Central",
      "Amazon seller account setup",
      "Amazon listing optimization",
      "Amazon store management",
    ],
    image: media.storeBoutique,
    imageAlt: "Retail products prepared for an Amazon brand store listing",
    overview: [
      "Amazon rewards complete catalogues and clean account health, not a pretty logo. WordbitX sets up or repairs Seller Central under your ownership: company details, tax, brand registry where you qualify, and listings that follow category style guides.",
      "Management means a weekly rhythm — inventory, suppressed listings, cases and simple ads — not a promise that you will outrank a brand with ten years of reviews in a month.",
    ],
    whoNeeds: [
      "Brands opening their first Amazon seller account",
      "Sellers with suppressed listings or incomplete A+ content",
      "Teams that need someone who can work Seller Central without taking the password away",
      "Stores expanding from Shopify onto Amazon",
    ],
    problems: [
      { title: "Account not yours", text: "Agencies that keep the login own your reviews. We work in your Seller Central." },
      { title: "Thin listings", text: "Missing bullets and backend terms waste impressions. We rewrite to Amazon’s rules." },
      { title: "Account warnings", text: "We help you answer cases with evidence instead of generic templates." },
    ],
    benefits: [
      { title: "Store you can keep", text: "Brand store and listings stay with the company." },
      { title: "Clearer catalogue", text: "Variations and parent ASINs structured so shoppers find the right SKU." },
      { title: "Health first", text: "Policy and performance issues get attention before ads scale." },
      { title: "Handover docs", text: "Your staff can continue if the retainer ends." },
    ],
    offerings: [
      { title: "Seller account setup", text: "Registration, verification support and brand registry eligibility check." },
      { title: "Listing & A+ content", text: "Titles, images, bullets and A+ modules." },
      { title: "Brand store", text: "Storefront pages that match the catalogue." },
      { title: "Seller Central support", text: "Weekly listing, inventory and case handling." },
    ],
    deliverables: [
      "Live seller account owned by you",
      "Initial listing batch and image specs",
      "Store page or A+ set as scoped",
      "SOP for orders and cases",
    ],
    process: marketplaceProcess,
    techStack: ["Amazon Seller Central", "Helium 10", "Excel", "Canva"],
    faqs: [
      { question: "Do you guarantee the Buy Box?", answer: "No. Buy Box depends on price, stock, performance and Amazon’s rules. We set the account and listings correctly; we do not sell guaranteed ranks." },
      { question: "FBA or FBM?", answer: "We recommend based on margin, size and where you already warehouse. We do not force FBA if it destroys profit." },
    ],
    related: ["google-merchant-center", "ecommerce-shopify", "ebay-store-setup", "graphic-design"],
    relatedPosts: ["how-to-launch-a-shopify-store", "shopify-vs-custom-ecommerce-website"],
    projectCategory: "E-Commerce",
  }),
  withServiceDefaults({
    slug: "ebay-store-setup",
    title: "eBay Store Setup & Management",
    shortTitle: "eBay Store",
    icon: "ecommerce",
    h1: "eBay Store Setup and Listing Management",
    tagline:
      "Seller account, store subscription, listing templates and policies configured so you can sell without fighting eBay’s rules after the first item.",
    summary:
      "eBay store setup, listing templates, shipping policies and catalogue management for new and existing sellers.",
    metaTitle: "eBay Store Setup & Management Services",
    metaDescription:
      "eBay store setup from WordbitX: seller account, store pages, listing templates, shipping and return policies, and ongoing eBay catalogue management.",
    primaryKeyword: "eBay store setup",
    keywords: [
      "eBay store setup",
      "eBay store management",
      "eBay listing services",
      "eBay seller account setup",
      "eBay store design",
    ],
    image: media.ecommerceOnline,
    imageAlt: "Laptop showing an online marketplace storefront ready for listings",
    overview: [
      "eBay still converts for parts, collectibles, refurbished and cross-border sellers who treat listings as a system. WordbitX sets up the store, policies and templates so every SKU is not a one-off HTML experiment.",
      "We work in your eBay account. Promoted Listings are optional and only after the catalogue is complete.",
    ],
    whoNeeds: [
      "Sellers moving leftover or secondary inventory onto eBay",
      "Stores that need multi-quantity listings and variations",
      "Businesses expanding from Amazon or Shopify to eBay",
      "Teams with poor seller standards after messy listings",
    ],
    problems: [
      { title: "Inconsistent listings", text: "Templates keep title, item specifics and returns aligned." },
      { title: "Shipping surprises", text: "Policies and calculated shipping are set before you take the first order." },
      { title: "Policy strikes", text: "We stay inside eBay’s category rules instead of copying Amazon copy blindly." },
    ],
    benefits: [
      { title: "Faster listing", text: "Reuse templates instead of designing every SKU." },
      { title: "Fewer defects", text: "Accurate specifics reduce returns and cases." },
      { title: "Your account", text: "Feedback and seller level stay with you." },
      { title: "Optional ads later", text: "Promoted Listings only when the offer is clear." },
    ],
    offerings: [
      { title: "Account & store", text: "Seller setup, store pages and about content." },
      { title: "Listing templates", text: "Title patterns, item specifics and HTML or editor layouts." },
      { title: "Policy pack", text: "Returns, payment and shipping that match how you actually fulfil." },
      { title: "Catalogue support", text: "Batch listing and weekly cleanup." },
    ],
    deliverables: [
      "Configured eBay store under your login",
      "Template set and first listing batch",
      "Written policy summary",
    ],
    process: marketplaceProcess,
    techStack: ["eBay Seller Hub", "Excel", "Canva"],
    faqs: [
      { question: "Do you handle dispatch?", answer: "No. We set the store and listings. Fulfilment stays with you or your warehouse." },
    ],
    related: ["amazon-store-setup", "etsy-store-setup", "ecommerce-development", "graphic-design"],
    relatedPosts: ["how-to-launch-a-shopify-store", "shopify-vs-custom-ecommerce-website"],
    projectCategory: "E-Commerce",
  }),
  withServiceDefaults({
    slug: "etsy-store-setup",
    title: "Etsy Store Setup & Management",
    shortTitle: "Etsy Store",
    icon: "ecommerce",
    h1: "Etsy Store Setup for Handmade, Vintage and Craft Brands",
    tagline:
      "Shop policies, SEO titles, tags and listing photos set up to Etsy’s handmade and vintage rules — not a generic dropshipping template.",
    summary:
      "Etsy shop setup, listing SEO, brand photography direction and shop-section structure.",
    metaTitle: "Etsy Store Setup & Management Services",
    metaDescription:
      "Etsy store setup from WordbitX: shop policies, listing SEO, tags, sections and Etsy shop management that follows handmade and vintage marketplace rules.",
    primaryKeyword: "Etsy store setup",
    keywords: [
      "Etsy store setup",
      "Etsy shop setup",
      "Etsy listing SEO",
      "Etsy store management",
      "Etsy seller help",
    ],
    image: media.jewelleryBoutique,
    imageAlt: "Handmade products arranged for an Etsy shop listing photo",
    overview: [
      "Etsy buyers search like Google: titles and tags matter, and policy violations close shops. WordbitX sets up a shop that matches how you actually make or curate goods, then writes listings people can find.",
      "We do not run prohibited dropshipping models. If the catalogue is not Etsy-eligible, we say so before you pay for listings.",
    ],
    whoNeeds: [
      "Makers opening a first Etsy shop",
      "Shops with sales but weak titles and tags",
      "Brands adding Etsy next to Shopify",
      "Sellers who need sections, policies and about copy written clearly",
    ],
    problems: [
      { title: "Invisible listings", text: "We research tags and rewrite titles to how buyers search." },
      { title: "Policy risk", text: "Production partners and personalisation are disclosed the way Etsy expects." },
      { title: "Messy shop front", text: "Sections and about copy make the shop feel finished." },
    ],
    benefits: [
      { title: "Search-ready listings", text: "Titles, tags and attributes aligned to Etsy search." },
      { title: "Trust on the shop", text: "Policies and processing times that match dispatch." },
      { title: "Reusable process", text: "A listing SOP for the next SKU." },
      { title: "Honest fit", text: "We walk away if the product is not allowed." },
    ],
    offerings: [
      { title: "Shop setup", text: "Policies, about, shop name review and payment readiness." },
      { title: "Listing SEO", text: "Titles, tags, descriptions and attributes." },
      { title: "Photo direction", text: "Shot lists your photographer or phone can follow." },
      { title: "Shop management", text: "Weekly listing and message support if you retain us." },
    ],
    deliverables: [
      "Live Etsy shop under your account",
      "Initial listing set as scoped",
      "Tag and title pattern document",
    ],
    process: marketplaceProcess,
    techStack: ["Etsy Seller", "Canva", "Excel"],
    faqs: [
      { question: "Can you guarantee Etsy ranks?", answer: "No. We improve listing quality and shop completeness. Rankings depend on reviews, price and Etsy’s algorithm." },
    ],
    related: ["amazon-store-setup", "graphic-design", "ecommerce-shopify", "seo-services"],
    relatedPosts: ["how-to-launch-a-shopify-store", "shopify-vs-custom-ecommerce-website"],
    projectCategory: "E-Commerce",
  }),
  withServiceDefaults({
    slug: "walmart-marketplace",
    title: "Walmart Marketplace Store Setup",
    shortTitle: "Walmart Marketplace",
    icon: "ecommerce",
    h1: "Walmart Marketplace Setup for Approved Sellers",
    tagline:
      "Seller application support, item setup and Walmart Seller Center configuration for brands that already qualify — we do not sell fake approvals.",
    summary:
      "Walmart Marketplace onboarding support, catalogue setup and Seller Center routines for eligible brands.",
    metaTitle: "Walmart Marketplace Store Setup Services",
    metaDescription:
      "Walmart Marketplace store setup from WordbitX: seller application support, item setup, Seller Center configuration and catalogue work for brands.",
    primaryKeyword: "Walmart Marketplace setup",
    keywords: [
      "Walmart Marketplace setup",
      "Walmart seller account",
      "Walmart Marketplace store",
      "Walmart Seller Center",
      "sell on Walmart Marketplace",
    ],
    image: media.warehouseShelves,
    imageAlt: "Warehouse inventory prepared for a large marketplace seller account",
    overview: [
      "Walmart Marketplace is invite- and application-led. WordbitX prepares documents, item data and Seller Center so you look like a seller Walmart can keep — we cannot buy you a slot.",
      "If you are not ready on insurance, GTIN or fulfilment, we tell you before you spend on listings.",
    ],
    whoNeeds: [
      "Brands already selling on Amazon that meet Walmart’s category rules",
      "Manufacturers with GTINs and stable supply",
      "Sellers who received a Walmart invite and need setup help",
      "Teams that need item setup files done correctly the first time",
    ],
    problems: [
      { title: "Rejected applications", text: "We check category, documents and fulfilment story before you apply." },
      { title: "Item setup errors", text: "Feeds fail on attributes. We map them to Walmart’s spec." },
      { title: "Two catalogues", text: "We keep Walmart SKUs aligned with your Shopify or ERP identifiers." },
    ],
    benefits: [
      { title: "Cleaner onboarding", text: "Fewer back-and-forths with Seller Center." },
      { title: "Data you can reuse", text: "Item files become a source for the next channel." },
      { title: "Honest gate", text: "No ‘guaranteed approval’ pitch." },
      { title: "Your seller account", text: "Access stays with the brand." },
    ],
    offerings: [
      { title: "Application pack", text: "Document checklist and category readiness review." },
      { title: "Item setup", text: "Catalogue files and images to spec." },
      { title: "Seller Center setup", text: "Shipping, returns and tax configuration support." },
      { title: "Ongoing listing help", text: "Optional weekly catalogue maintenance." },
    ],
    deliverables: [
      "Readiness report",
      "Item setup files as scoped",
      "Seller Center configuration notes",
    ],
    process: marketplaceProcess,
    techStack: ["Walmart Seller Center", "Excel"],
    faqs: [
      { question: "Can you get us approved for sure?", answer: "No. Walmart decides. We prepare a complete, truthful application and catalogue. Anyone who sells guaranteed approval is not being honest." },
    ],
    related: ["amazon-store-setup", "google-merchant-center", "ecommerce-development", "inventory-management-software"],
    relatedPosts: ["shopify-vs-custom-ecommerce-website", "inventory-management-software-guide"],
    projectCategory: "E-Commerce",
  }),
  withServiceDefaults({
    slug: "tiktok-shop-setup",
    title: "TikTok Shop Setup & Management",
    shortTitle: "TikTok Shop",
    icon: "ecommerce",
    h1: "TikTok Shop Setup Linked to Your Catalogue and Creators",
    tagline:
      "TikTok Shop onboarding, product sync and shop policies — built so live and short-form can sell without a disconnected store.",
    summary:
      "TikTok Shop setup, product catalogue connection, shipping settings and basic shop operations.",
    metaTitle: "TikTok Shop Setup & Management Services",
    metaDescription:
      "TikTok Shop setup from WordbitX: seller onboarding, product catalogue, shipping and shop management so TikTok content can sell from your real inventory.",
    primaryKeyword: "TikTok Shop setup",
    keywords: [
      "TikTok Shop setup",
      "TikTok Shop management",
      "open TikTok Shop",
      "TikTok Shop seller",
      "TikTok Shop product listing",
    ],
    image: media.socialContent,
    imageAlt: "Creator filming product content for a TikTok Shop listing",
    overview: [
      "TikTok Shop only works if products, shipping and videos point at the same SKUs. WordbitX connects the shop to a real catalogue — often Shopify — and sets policies you can fulfil.",
      "We do not promise viral sales. We make the shop eligible and operable so ads or creators have something that can check out.",
    ],
    whoNeeds: [
      "Shopify brands opening TikTok Shop in a supported market",
      "Sellers with content but no product connection",
      "Teams that need shipping and return settings done correctly",
      "Brands adding affiliate or creator samples later",
    ],
    problems: [
      { title: "Shop not linked", text: "We complete onboarding and catalogue sync instead of screenshot tutorials." },
      { title: "Unfulfilable offers", text: "Processing times match your warehouse, not a wish." },
      { title: "Orphaned ads", text: "Product IDs in ads match the shop so checkout does not 404." },
    ],
    benefits: [
      { title: "One catalogue", text: "TikTok SKUs track the store you already run." },
      { title: "Creator-ready later", text: "Clean product data is what affiliates need." },
      { title: "Policy-safe setup", text: "Restricted categories are flagged before you list." },
      { title: "Your Business Center", text: "Access stays with the company." },
    ],
    offerings: [
      { title: "Seller onboarding", text: "Business Center and Shop setup in supported regions." },
      { title: "Catalogue sync", text: "Shopify or feed-based product connection." },
      { title: "Shop operations", text: "Shipping, returns and order routing notes." },
      { title: "TikTok Ads pairing", text: "Optional link to a TikTok ads account." },
    ],
    deliverables: [
      "Shop live or a written blocker list",
      "Product sync as scoped",
      "Ops checklist for orders",
    ],
    process: marketplaceProcess,
    techStack: ["TikTok Shop", "Shopify", "Meta Business Suite"],
    faqs: [
      { question: "Is TikTok Shop available in Pakistan?", answer: "Availability is country-specific and changes. We confirm the market you can sell in before we start. If the shop is not open for your entity, we say so." },
    ],
    related: ["tiktok-ads", "ecommerce-shopify", "facebook-instagram-shop", "digital-marketing"],
    relatedPosts: ["how-to-launch-a-shopify-store", "digital-marketing-for-software-companies"],
    projectCategory: "E-Commerce",
  }),
  withServiceDefaults({
    slug: "facebook-instagram-shop",
    title: "Facebook & Instagram Shop Setup",
    shortTitle: "Facebook & Instagram Shop",
    icon: "ecommerce",
    h1: "Facebook Shop and Instagram Shop Setup on Meta",
    tagline:
      "Commerce-ready Facebook and Instagram shops with a synced catalogue, checkout path and product tags — not a dead Shop tab.",
    summary:
      "Meta Shop setup, product catalogue, Instagram Shopping tags and connection to Shopify or your site.",
    metaTitle: "Facebook Shop & Instagram Shop Setup Services",
    metaDescription:
      "Facebook Shop and Instagram Shop setup from WordbitX: Meta catalogue, Shopping tags, checkout connection and shop tabs that match your live products.",
    primaryKeyword: "Facebook and Instagram Shop setup",
    keywords: [
      "Facebook Shop setup",
      "Instagram Shop setup",
      "Instagram Shopping",
      "Meta product catalogue",
      "Facebook shop management",
    ],
    image: media.socialInstagram,
    imageAlt: "Smartphone showing an Instagram shopping product tag",
    overview: [
      "A Shop tab with three expired products hurts more than no shop. WordbitX connects Commerce Manager, a catalogue and the checkout you actually use — usually Shopify or your website.",
      "Product tags, availability and prices stay in sync so ads and organic posts do not send people to 404s.",
    ],
    whoNeeds: [
      "Retailers already posting on Instagram who cannot tag products",
      "Shopify stores that never finished Commerce Manager",
      "Brands running Meta ads without a catalogue",
      "Teams that need Facebook Shop and Instagram in one setup",
    ],
    problems: [
      { title: "Rejected commerce", text: "We fix Business verification, policies and blocked categories first." },
      { title: "Stale catalogue", text: "Feeds update stock and price so the shop does not lie." },
      { title: "Split brands", text: "Page, IG and catalogue sit under one Business Manager you own." },
    ],
    benefits: [
      { title: "Shoppable posts", text: "Tags that open the right SKU." },
      { title: "Ads that match stock", text: "Catalogue ads can use the same feed." },
      { title: "One checkout story", text: "We do not invent a second cart." },
      { title: "Handover", text: "Admin roles documented for your marketing hire." },
    ],
    offerings: [
      { title: "Commerce Manager", text: "Shop, catalogue and data sources." },
      { title: "Instagram Shopping", text: "Eligibility, tags and highlights." },
      { title: "Facebook Shop tab", text: "Visible shop aligned to the feed." },
      { title: "Feed maintenance", text: "Optional weekly catalogue checks." },
    ],
    deliverables: [
      "Approved or blocker-listed commerce account",
      "Synced catalogue",
      "Role and asset map in Business Manager",
    ],
    process: marketplaceProcess,
    techStack: ["Meta Business Suite", "Shopify", "Google Merchant Center"],
    faqs: [
      { question: "Checkout on Instagram or on our site?", answer: "Depends on your country and Meta’s current commerce options. We pick the path that is allowed and that you can fulfil." },
    ],
    related: ["facebook-instagram-ads", "google-merchant-center", "ecommerce-shopify", "social-media-marketing"],
    relatedPosts: ["how-to-launch-a-shopify-store", "digital-marketing-for-software-companies"],
    projectCategory: "E-Commerce",
  }),
  withServiceDefaults({
    slug: "google-merchant-center",
    title: "Google Merchant Center Setup",
    shortTitle: "Merchant Center",
    icon: "seo",
    h1: "Google Merchant Center Setup for Shopping and Free Listings",
    tagline:
      "A verified Merchant Center, clean product feed and site connection so Google Shopping and free listings can show real stock.",
    summary:
      "Google Merchant Center account, product feed, diagnostics and link to Google Ads or free product listings.",
    metaTitle: "Google Merchant Center Setup Services",
    metaDescription:
      "Google Merchant Center setup from WordbitX: product feeds, diagnostics, site verification and Shopping-ready listings for Google Ads.",
    primaryKeyword: "Google Merchant Center setup",
    keywords: [
      "Google Merchant Center setup",
      "Google Shopping feed",
      "Merchant Center product feed",
      "Google Shopping setup",
      "free product listings setup",
    ],
    image: media.adsAnalytics,
    imageAlt: "Product performance charts used to review a Google Shopping feed",
    overview: [
      "Shopping ads fail when the feed lies: wrong GTIN, missing shipping, banned language. WordbitX builds or repairs Merchant Center so titles, prices and availability match the live product pages.",
      "We verify the domain the way Google asks and keep diagnostics visible so you see disapprovals instead of guessing why SKUs vanished.",
    ],
    whoNeeds: [
      "Stores launching Google Shopping or Performance Max",
      "Shops with hundreds of disapproved items",
      "Shopify or WooCommerce brands that never finished Merchant Center",
      "Teams that want free listings as well as ads",
    ],
    problems: [
      { title: "Feed errors", text: "We map identifiers, condition and shipping to Google’s spec." },
      { title: "Mismatched landing pages", text: "Each item hits a crawlable product URL with the same price." },
      { title: "Unclaimed domain", text: "Verification and Search Console linking are part of the job." },
    ],
    benefits: [
      { title: "Eligible products", text: "Fewer surprise disapprovals after launch." },
      { title: "Ads-ready", text: "The same feed can power Shopping and PMax." },
      { title: "Free listings path", text: "We enable them when the country and account allow." },
      { title: "Your MCC/GMC", text: "Account ownership stays with you." },
    ],
    offerings: [
      { title: "New Merchant Center", text: "Account, verification and users." },
      { title: "Feed build", text: "Shopify, WooCommerce or custom XML/CSV." },
      { title: "Diagnostics cleanup", text: "Fix item and account issues in priority order." },
      { title: "Ads link", text: "Connect Google Ads when you are ready to spend." },
    ],
    deliverables: [
      "Verified Merchant Center",
      "Approved or documented remaining items",
      "Feed update method",
    ],
    process: growthProcess,
    techStack: ["Google Merchant Center", "Google Ads", "Shopify", "WooCommerce"],
    faqs: [
      { question: "Do you also run the ads?", answer: "That is a separate Google Ads engagement. This page is the feed and account. You can start ads after items are eligible." },
    ],
    related: ["google-ads", "ecommerce-shopify", "woocommerce-development", "seo-services"],
    relatedPosts: ["how-to-launch-a-shopify-store", "seo-guide-for-businesses"],
    projectCategory: "E-Commerce",
  }),
  withServiceDefaults({
    slug: "local-seo",
    title: "Local SEO",
    shortTitle: "Local SEO",
    icon: "seo",
    h1: "Local SEO Services for Lahore Businesses and Multi-Location Brands",
    tagline:
      "Google Business Profile, NAP consistency and location pages that help nearby customers find you — not a national keyword campaign you cannot win yet.",
    summary:
      "Local SEO: Google Business Profile optimisation, citations, location pages and review strategy for city and map rankings.",
    metaTitle: "Local SEO Services in Lahore | Google Business Profile",
    metaDescription:
      "Local SEO services from WordbitX in Lahore: Google Business Profile, citations, location pages and on-page local signals for map pack and city searches.",
    primaryKeyword: "local SEO services",
    keywords: [
      "local SEO services",
      "local SEO Lahore",
      "Google Business Profile optimization",
      "local SEO company Pakistan",
      "Google Maps SEO",
    ],
    image: media.realEstateAgent,
    imageAlt: "Local business consultation about map visibility and city search",
    overview: [
      "If customers search ‘near me’ or a city name, classic blog SEO is the wrong first spend. WordbitX focuses on Google Business Profile, matching name-address-phone, and pages that prove you serve that city.",
      "We do not create fake locations. One real address, honest categories and photos beat a directory blast.",
    ],
    whoNeeds: [
      "Clinics, restaurants, showrooms and agencies that serve a city",
      "Software companies in Lahore that should appear for local service queries",
      "Brands with more than one real branch",
      "Businesses with a GBP that has the wrong phone or hours",
    ],
    problems: [
      { title: "Split NAP", text: "Directories disagree. We pick one canonical address and phone and push that." },
      { title: "Weak GBP", text: "Categories, services, photos and posts are completed, not left at signup." },
      { title: "No location proof", text: "The website never mentions the city in a useful way. We add honest location content." },
    ],
    benefits: [
      { title: "Map-pack readiness", text: "The profile and site stop contradicting each other." },
      { title: "Call tracking option", text: "We can separate site and ads numbers without breaking GBP — if you need it." },
      { title: "Review plan", text: "A legal ask-for-review process, not fake stars." },
      { title: "City pages that are real", text: "Only for cities you actually serve." },
    ],
    offerings: [
      { title: "GBP optimisation", text: "Categories, services, Q&A, photos and products/services." },
      { title: "Citation cleanup", text: "Priority directories, not 500 junk listings." },
      { title: "Location pages", text: "On-site pages that match the real coverage area." },
      { title: "Review & photo cadence", text: "A monthly routine your staff can run." },
    ],
    deliverables: [
      "GBP audit and completed profile",
      "NAP sheet for the team",
      "On-page local fixes as scoped",
    ],
    process: growthProcess,
    techStack: ["Google Business Profile", "Google Search Console", "Google Analytics"],
    faqs: [
      { question: "Can you verify Google Business Profile for us?", answer: "Verification is done by the business owner. We prepare the profile and tell you which method Google is offering. We cannot complete video or postcard verification on your behalf." },
      { question: "Do you guarantee map pack #1?", answer: "No. Local rank depends on relevance, distance and prominence. We fix what we control." },
    ],
    related: ["seo-services", "technical-seo", "google-ads", "web-development"],
    relatedPosts: ["seo-guide-for-businesses", "how-seo-helps-businesses-grow"],
    projectCategory: "Websites",
  }),
  withServiceDefaults({
    slug: "technical-seo",
    title: "Technical SEO",
    shortTitle: "Technical SEO",
    icon: "seo",
    h1: "Technical SEO Audits and Fixes Search Engines Can Actually Crawl",
    tagline:
      "Indexation, canonicals, sitemaps, Core Web Vitals and structured data — the plumbing that content cannot fix.",
    summary:
      "Technical SEO: crawl budget, indexation, redirects, structured data, Core Web Vitals and sitemap hygiene.",
    metaTitle: "Technical SEO Services | Crawl, Index & Core Web Vitals",
    metaDescription:
      "Technical SEO services from WordbitX: crawl and index fixes, canonicals, sitemaps, Core Web Vitals, structured data and redirect maps.",
    primaryKeyword: "technical SEO services",
    keywords: [
      "technical SEO services",
      "technical SEO audit",
      "Core Web Vitals SEO",
      "indexation SEO",
      "website crawlability",
    ],
    image: media.speedReport,
    imageAlt: "Website performance and crawl report used in a technical SEO audit",
    overview: [
      "If Google cannot fetch, render or trust the URL, more blog posts will not help. WordbitX audits the crawl path: robots, sitemaps, canonicals, status codes, duplicates and page weight.",
      "We implement the top fixes or hand a sequenced list to your developers. We do not deliver a 90-page PDF with no owners.",
    ],
    whoNeeds: [
      "Sites with ‘discovered, not indexed’ or duplicate sitemap submissions",
      "Replatforms that lost URLs after a rebuild",
      "Heavy JavaScript sites that look empty to fetch",
      "Stores with parameter chaos and thin category copies",
    ],
    problems: [
      { title: "Index bloat", text: "We noindex or canonical thin and duplicate URLs instead of adding more sitemaps." },
      { title: "Redirect chains", text: "Maps and 301s that protect equity after a migration." },
      { title: "Slow LCP", text: "We pair technical SEO with speed work when the HTML itself is the problem." },
    ],
    benefits: [
      { title: "Cleaner Search Console", text: "Fewer conflicting sitemaps and mystery 404s." },
      { title: "Faster discovery", text: "Important URLs in one index, with accurate lastmod." },
      { title: "Safer launches", text: "A go-live SEO checklist, not hope." },
      { title: "Measurable fixes", text: "Each item has a before/after in GSC or a crawler." },
    ],
    offerings: [
      { title: "Technical audit", text: "Crawl, GSC and priority fix list." },
      { title: "Implementation", text: "We ship the fixes in the codebase when you want one team." },
      { title: "Migration SEO", text: "URL map, redirects and post-launch validation." },
      { title: "Schema & sitemaps", text: "JSON-LD and XML that match the live IA." },
    ],
    deliverables: [
      "Prioritised technical backlog",
      "Implemented or ticketed fixes",
      "GSC validation notes",
    ],
    process: growthProcess,
    techStack: ["Google Search Console", "Next.js", "Cloudflare", "Google Analytics"],
    faqs: [
      { question: "Is this the same as SEO services?", answer: "SEO services also cover content and internal linking. Technical SEO is the crawl, index and performance layer. Many clients buy both." },
      { question: "Will this make us rank #1?", answer: "It removes technical blockers. Rank still needs relevance and links. We will not sell technical SEO as a ranking guarantee." },
    ],
    related: ["seo-services", "website-speed-optimization", "local-seo", "web-development"],
    relatedPosts: ["website-speed-and-seo", "seo-guide-for-businesses"],
    projectCategory: "Websites",
  }),
  withServiceDefaults({
    slug: "website-speed-optimization",
    title: "Website Speed Optimization",
    shortTitle: "Speed Optimization",
    icon: "web",
    h1: "Website Speed Optimization for Core Web Vitals and Real Users",
    tagline:
      "Cut HTML weight, images and third-party scripts so pages pass Core Web Vitals on mobile — not just a lab screenshot.",
    summary:
      "Performance work: LCP, INP, CLS, image and font strategy, caching and script hygiene.",
    metaTitle: "Website Speed Optimization | Core Web Vitals",
    metaDescription:
      "Website speed optimization from WordbitX: Core Web Vitals, image and font strategy, caching and third-party script cleanup for faster mobile pages.",
    primaryKeyword: "website speed optimization",
    keywords: [
      "website speed optimization",
      "Core Web Vitals optimization",
      "website performance optimization",
      "improve page speed",
      "LCP optimization",
    ],
    image: media.analyticsPaper,
    imageAlt: "Printed performance charts used while improving website page speed",
    overview: [
      "A 900 KB homepage will not feel fast on Pakistani or Gulf mobile networks no matter how pretty it is. WordbitX measures field and lab data, then removes the heaviest offenders: unoptimised images, blocking fonts, chat widgets and HTML you do not need above the fold.",
      "We set a performance budget and test against it. If a marketing pixel blows the budget, you choose the pixel or the score — we will not hide the trade-off.",
    ],
    whoNeeds: [
      "Sites failing LCP or INP in Search Console",
      "Stores with slow category and product pages",
      "Marketing sites loaded with tags and page builders",
      "Teams about to run ads onto a slow landing page",
    ],
    problems: [
      { title: "Lab vs field", text: "We treat CrUX / GSC as the truth, not only Lighthouse on wifi." },
      { title: "Third-party bloat", text: "Chat, ads and heatmaps are loaded after the page is usable." },
      { title: "Image chaos", text: "Correct formats, sizes and priority on the LCP image." },
    ],
    benefits: [
      { title: "Better mobile UX", text: "Pages become usable sooner." },
      { title: "SEO support", text: "Speed is a ranking and ranking-quality factor, not the only one." },
      { title: "Cheaper ads", text: "Landing experience affects Quality Score and conversion." },
      { title: "A budget you can keep", text: "New features are checked against weight." },
    ],
    offerings: [
      { title: "Performance audit", text: "Waterfall, CWV and a sequenced fix list." },
      { title: "Implementation", text: "Code, CDN and image pipeline changes." },
      { title: "Tag hygiene", text: "GTM loaded without blocking first paint." },
      { title: "Retest", text: "Before/after on the templates that matter." },
    ],
    deliverables: [
      "Baseline and target CWV",
      "Shipped fixes on priority templates",
      "Retest notes",
    ],
    process: growthProcess,
    techStack: ["Next.js", "Cloudflare", "Google Analytics", "Google Search Console"],
    faqs: [
      { question: "Can every site hit 100 on Lighthouse?", answer: "No, and chasing 100 often breaks analytics or ads. We target good Core Web Vitals for real users." },
    ],
    related: ["technical-seo", "web-development", "conversion-rate-optimization", "seo-services"],
    relatedPosts: ["website-speed-and-seo", "seo-guide-for-businesses"],
    projectCategory: "Websites",
  }),
  withServiceDefaults({
    slug: "conversion-rate-optimization",
    title: "Conversion Rate Optimization",
    shortTitle: "CRO",
    icon: "marketing",
    h1: "Conversion Rate Optimization for Sites That Get Traffic but Few Enquiries",
    tagline:
      "Form, checkout and landing-page work driven by behaviour data — not random button-colour opinions.",
    summary:
      "CRO: landing page structure, forms, checkout steps, analytics events and structured tests.",
    metaTitle: "Conversion Rate Optimization (CRO) Services",
    metaDescription:
      "Conversion rate optimization from WordbitX: landing pages, forms, checkout and analytics events so existing traffic produces more enquiries and orders.",
    primaryKeyword: "conversion rate optimization",
    keywords: [
      "conversion rate optimization",
      "CRO services",
      "landing page optimization",
      "checkout optimization",
      "increase website conversions",
    ],
    image: media.adsCharts,
    imageAlt: "Conversion funnel charts used to improve website enquiry rates",
    overview: [
      "If traffic is already arriving, buying more ads is often waste. WordbitX looks at where users drop: hero, form, shipping, trust and mobile tap targets.",
      "We instrument events first. Then we change one primary path at a time so you can see whether the enquiry or checkout rate moved.",
    ],
    whoNeeds: [
      "Sites with impressions or ads but weak form submits",
      "Stores with high add-to-cart and low purchase",
      "SaaS pages with traffic and no trials",
      "Teams arguing about design without numbers",
    ],
    problems: [
      { title: "No events", text: "We define the conversions that matter before redesigning." },
      { title: "Friction", text: "Extra fields, unclear shipping and weak proof get cut or rewritten." },
      { title: "Desktop-only thinking", text: "Most of your users are on a phone. We test there." },
    ],
    benefits: [
      { title: "More from the same spend", text: "Ads and SEO keep working harder." },
      { title: "Clearer offers", text: "One action per screen." },
      { title: "Less opinion", text: "Tests beat taste debates." },
      { title: "Reusable patterns", text: "Winning sections become templates." },
    ],
    offerings: [
      { title: "Funnel review", text: "Recording samples, analytics and form analytics where available." },
      { title: "Landing rebuilds", text: "Structure, copy and CTA hierarchy." },
      { title: "Checkout / form UX", text: "Fewer fields, clearer errors, trust near pay." },
      { title: "Experiment plan", text: "What to test next month, not a one-off polish." },
    ],
    deliverables: [
      "Event map and baseline rates",
      "Implemented UX/copy changes as scoped",
      "Test backlog",
    ],
    process: growthProcess,
    techStack: ["Google Analytics", "Figma", "Next.js", "Shopify"],
    faqs: [
      { question: "Do you guarantee a conversion lift?", answer: "No. We improve the obvious friction and measure. Anyone who guarantees a percentage without seeing your data is guessing." },
    ],
    related: ["ui-ux-design", "google-ads", "website-speed-optimization", "web-development"],
    relatedPosts: ["how-to-choose-a-web-development-company", "digital-marketing-for-software-companies"],
    projectCategory: "Websites",
  }),
];
