import type { Service } from "@/lib/types";
import { media } from "@/lib/media";
import { growthProcess, withServiceDefaults } from "@/lib/service-builder";

export const servicesG: Service[] = [
  withServiceDefaults({
    slug: "app-maintenance",
    title: "App Maintenance & Updates",
    shortTitle: "App Maintenance",
    icon: "mobile",
    h1: "App Maintenance and Updates for Android and iOS Products",
    tagline:
      "OS updates, store policy changes, crash fixes and small features — so last year’s app still installs and still reviews cleanly.",
    summary:
      "Retained mobile maintenance: store updates, dependency patches, crash triage and compatibility with new Android and iOS versions.",
    metaTitle: "App Maintenance & Updates | Android & iOS Support",
    metaDescription:
      "App maintenance and updates from WordbitX: OS compatibility, store policy changes, crash fixes, dependency patches and release management for Android and iOS.",
    primaryKeyword: "app maintenance and updates",
    keywords: [
      "app maintenance",
      "mobile app updates",
      "app support services",
      "iOS app maintenance",
      "Android app maintenance",
    ],
    image: media.phoneCode,
    imageAlt: "Developer updating a mobile application codebase on a phone and laptop",
    overview: [
      "Stores and operating systems move every year. An unmaintained app starts failing review, crashing on new phones or leaking an old SDK. WordbitX takes a monthly or quarterly cycle: crash reports, dependency updates, store questionnaires and a planned release.",
      "We can maintain apps we built or inherit a repo after a handover review. If the code is unsafe to touch, we say so before you pay for months of retainers.",
    ],
    whoNeeds: [
      "Products that launched and then had no owner",
      "Teams that only call a developer when the app is rejected",
      "Companies that need Play and App Store releases on a calendar",
      "Founders who want crash-free sessions before buying new features",
    ],
    problems: [
      { title: "Store surprises", text: "Privacy, data safety and photo permission forms are updated before rejection." },
      { title: "SDK rot", text: "Payments, maps and analytics libraries are patched on a schedule." },
      { title: "No release pipeline", text: "We add signing, tracks and a rollback note you can follow." },
    ],
    benefits: [
      { title: "Fewer emergencies", text: "OS betas are watched before users complain." },
      { title: "Clear monthly report", text: "Crashes, releases and remaining risk — not a vague ‘monitoring’ line." },
      { title: "Feature slots", text: "Small improvements ride the same release train." },
      { title: "Your accounts", text: "Store and Git stay in your name." },
    ],
    offerings: [
      { title: "Compatibility updates", text: "New Android and iOS target versions." },
      { title: "Crash triage", text: "Firebase Crashlytics or equivalent, then fixes." },
      { title: "Store releases", text: "Changelogs, phased rollouts and review responses." },
      { title: "Light features", text: "Scoped tickets inside the retainer hours." },
    ],
    deliverables: [
      "Maintenance plan and hours",
      "At least one storeable build cadence as agreed",
      "Release notes the business can read",
    ],
    techStack: ["Flutter", "Kotlin", "Swift", "Firebase", "React Native"],
    faqs: [
      { question: "Do you maintain someone else’s app?", answer: "Yes, after a paid review. If the architecture is too risky, we quote a stabilisation sprint instead of a cheap monthly." },
    ],
    related: ["mobile-app-development", "flutter-app-development", "firebase-integration", "app-store-optimization"],
    relatedPosts: ["mobile-app-development-guide", "complete-guide-to-app-store-optimization"],
    projectCategory: "Mobile Apps",
  }),
  withServiceDefaults({
    slug: "app-monetization",
    title: "App Monetization",
    shortTitle: "App Monetization",
    icon: "aso",
    h1: "App Monetization Strategy for Ads, IAP and Subscriptions",
    tagline:
      "AdMob, in-app purchases and subscriptions placed so users still finish the job — not a wall of ads on day one.",
    summary:
      "Monetization design for mobile apps: ad placements, IAP, subscriptions, paywalls and basic mediation.",
    metaTitle: "App Monetization Services | AdMob, IAP & Subscriptions",
    metaDescription:
      "App monetization from WordbitX: AdMob, in-app purchases, subscriptions and paywall UX so Android and iOS apps can earn without destroying retention.",
    primaryKeyword: "app monetization",
    keywords: [
      "app monetization",
      "mobile app monetization",
      "in-app purchase development",
      "app subscription monetization",
      "AdMob monetization",
    ],
    image: media.adsRevenue,
    imageAlt: "Revenue analytics used to plan mobile app monetization",
    overview: [
      "The wrong ad density kills retention faster than it pays. WordbitX maps the user job, then places ads, trials or IAP where the product already delivers value.",
      "We implement store-compliant purchases and AdMob (or a mediation layer) under your developer accounts. Revenue numbers we publish are yours after launch — we do not invent eCPM promises.",
    ],
    whoNeeds: [
      "Free apps ready for a first ad unit",
      "Products moving from ads to subscriptions",
      "Games or utilities that need rewarded ads without breaking UX",
      "Teams whose IAP was rejected or never finished",
    ],
    problems: [
      { title: "Ads everywhere", text: "We limit formats and frequency to what the session can bear." },
      { title: "Broken paywalls", text: "Restore purchases, trials and grace periods are implemented properly." },
      { title: "Policy risk", text: "Invalid traffic and restricted categories are reviewed before you scale ads." },
    ],
    benefits: [
      { title: "A model you can explain", text: "Ads, IAP or hybrid — chosen, not stacked at random." },
      { title: "Store-safe billing", text: "Play Billing and StoreKit flows that pass review." },
      { title: "Room to A/B", text: "Placements and prices are not hardcoded in ten files." },
      { title: "Tied to analytics", text: "You see ARPDAU and retention together." },
    ],
    offerings: [
      { title: "Monetization plan", text: "Format, placement and pricing hypothesis." },
      { title: "AdMob / mediation", text: "Units, UMP/consent and basic mediation." },
      { title: "IAP & subscriptions", text: "Products, paywalls and server receipts where needed." },
      { title: "Tuning", text: "Post-launch placement changes from real data." },
    ],
    deliverables: [
      "Monetization map",
      "Implemented units or IAP as scoped",
      "Test account checklist",
    ],
    techStack: ["Google AdMob", "Firebase", "Flutter", "Swift", "Kotlin"],
    faqs: [
      { question: "Will you guarantee a monthly revenue number?", answer: "No. Revenue depends on traffic quality, geo and retention. We implement the machinery and help you read it." },
    ],
    related: ["google-admob", "app-store-optimization", "firebase-integration", "mobile-app-development"],
    relatedPosts: ["complete-guide-to-app-store-optimization", "how-to-get-google-adsense-approval"],
    projectCategory: "Mobile Apps",
  }),
  withServiceDefaults({
    slug: "firebase-integration",
    title: "Firebase Integration",
    shortTitle: "Firebase",
    icon: "devops",
    h1: "Firebase Integration for Auth, Push, Analytics and Crash Reporting",
    tagline:
      "Firebase wired properly: Auth, Cloud Messaging, Analytics, Crashlytics and Remote Config — not a half-added google-services.json.",
    summary:
      "Firebase setup for mobile and web: authentication, push notifications, analytics, crash reporting and remote config.",
    metaTitle: "Firebase Integration Services | Auth, Push & Analytics",
    metaDescription:
      "Firebase integration from WordbitX: Auth, Cloud Messaging, Analytics, Crashlytics, Remote Config and Firestore or custom API pairing for Android, iOS and web.",
    primaryKeyword: "Firebase integration",
    keywords: [
      "Firebase integration",
      "Firebase push notifications",
      "Firebase analytics setup",
      "Firebase authentication",
      "Firebase Cloud Messaging",
    ],
    image: media.appShowcase,
    imageAlt: "Multi-device app showcase representing Firebase-backed mobile products",
    overview: [
      "Firebase is excellent until every feature is turned on ‘just in case’. WordbitX enables the products you will operate: Auth, FCM, Analytics, Crashlytics, and Remote Config or Firestore only when the data model fits.",
      "Push notifications include permission UX and topics or segments you can actually send from. We do not leave a server key in the client.",
    ],
    whoNeeds: [
      "Apps that need login, push and crash reports without a large backend yet",
      "Teams whose Firebase project is a tangle of unused products",
      "Products moving from a custom backend to Firebase Auth + API",
      "Web apps that need FCM or Analytics alongside a mobile app",
    ],
    problems: [
      { title: "Keys in the repo", text: "We move secrets to environment config and restrict API keys." },
      { title: "Push that never arrives", text: "Certificates, topics and permission flows are tested on real devices." },
      { title: "Analytics noise", text: "We define a small event list instead of logging everything." },
    ],
    benefits: [
      { title: "Faster MVP backend", text: "Auth and push without inventing them twice." },
      { title: "Crash visibility", text: "You see broken releases the day they ship." },
      { title: "Safer later exit", text: "If you outgrow Firestore, the API boundary is already thought through." },
      { title: "Your GCP project", text: "Billing and IAM stay under the company." },
    ],
    offerings: [
      { title: "Auth", text: "Email, social or phone — with the providers you need." },
      { title: "Push notifications", text: "FCM, topics and basic campaigns." },
      { title: "Analytics & Crashlytics", text: "Events and crash grouping tied to releases." },
      { title: "Remote Config", text: "Flags for rollouts and simple experiments." },
    ],
    deliverables: [
      "Firebase project under your Google account",
      "Integrated app builds",
      "Event and IAM notes",
    ],
    techStack: ["Firebase", "Flutter", "Kotlin", "Swift", "Next.js"],
    faqs: [
      { question: "Firestore or a custom API?", answer: "Firestore suits simple documents and realtime. Relational or complex billing usually wants Postgres and an API. We choose in discovery." },
    ],
    related: ["flutter-app-development", "mobile-app-development", "app-maintenance", "google-admob"],
    relatedPosts: ["mobile-app-development-guide", "flutter-app-development-benefits"],
    projectCategory: "Mobile Apps",
  }),
  withServiceDefaults({
    slug: "google-ads",
    title: "Google Ads (PPC)",
    shortTitle: "Google Ads",
    icon: "marketing",
    h1: "Google Ads Management for Search, Shopping and Performance Max",
    tagline:
      "Account structure, conversion tracking and Search or Shopping campaigns you can read — not a black-box spend with no search terms.",
    summary:
      "Google Ads setup and management: conversion tracking, Search, Shopping, PMax and weekly search-term hygiene.",
    metaTitle: "Google Ads Management Services | PPC Agency",
    metaDescription:
      "Google Ads (PPC) management from WordbitX: conversion tracking, Search, Shopping and Performance Max campaigns with search-term reports you can actually read.",
    primaryKeyword: "Google Ads management",
    keywords: [
      "Google Ads management",
      "PPC services",
      "Google Ads agency",
      "Google Shopping ads",
      "Pay per click advertising",
    ],
    image: media.adsAnalytics,
    imageAlt: "Paid search performance dashboard used to manage Google Ads",
    overview: [
      "PPC fails when tracking is wrong or the account is one giant campaign. WordbitX starts with conversions you trust, then builds Search or Shopping around the queries that can pay.",
      "You keep the Google Ads account. We share search terms, wasted spend and the next test — not a vanity ROAS screenshot with brand queries only.",
    ],
    whoNeeds: [
      "Businesses ready to pay for high-intent search",
      "Stores with a working Merchant Center feed",
      "Teams whose previous agency could not explain the account",
      "Lead-gen sites that need call and form conversion tracking",
    ],
    problems: [
      { title: "Fake conversions", text: "We fix tags, enhanced conversions and what counts as a lead." },
      { title: "Broad waste", text: "Negatives and intent splits stop informational queries eating budget." },
      { title: "PMax only", text: "If you need query control, we keep Search in the mix." },
    ],
    benefits: [
      { title: "Spend you can audit", text: "Change history and a structure a new hire can inherit." },
      { title: "Landing alignment", text: "Ads point at pages that match the query." },
      { title: "Shopping-ready", text: "Feed issues are treated as ads issues." },
      { title: "Honest forecasts", text: "We estimate from your geo and category, not a global average." },
    ],
    offerings: [
      { title: "Account rebuild", text: "Campaigns, budgets and naming you can follow." },
      { title: "Conversion setup", text: "GA4, Ads and offline where needed." },
      { title: "Search & Shopping", text: "The mix that fits the catalogue or service." },
      { title: "Monthly management", text: "Search terms, creatives and bids." },
    ],
    deliverables: [
      "Tracking that fires on real leads or sales",
      "Live campaigns under your account",
      "Monthly search-term and spend notes",
    ],
    process: growthProcess,
    techStack: ["Google Ads", "Google Analytics", "Google Merchant Center", "Google Tag Manager"],
    faqs: [
      { question: "What budget do you need?", answer: "Enough to get statistically useful clicks in your market. We will say if the budget cannot learn. Media spend is paid to Google, not to us." },
      { question: "Do you guarantee leads?", answer: "No. We commit to correct tracking, relevant structure and transparent reporting." },
    ],
    related: ["google-merchant-center", "seo-services", "conversion-rate-optimization", "local-seo"],
    relatedPosts: ["digital-marketing-for-software-companies", "seo-guide-for-businesses"],
    projectCategory: "Websites",
  }),
  withServiceDefaults({
    slug: "facebook-instagram-ads",
    title: "Facebook & Instagram Ads",
    shortTitle: "Meta Ads",
    icon: "marketing",
    h1: "Facebook Ads and Instagram Ads Management on Meta",
    tagline:
      "Advantage+ or structured campaigns with a pixel you can trust and creatives that match the offer — not boosts from a personal profile.",
    summary:
      "Meta ads: pixel, CAPI, catalogue, creative testing and Facebook/Instagram campaign management.",
    metaTitle: "Facebook Ads & Instagram Ads Management",
    metaDescription:
      "Facebook Ads and Instagram Ads management from WordbitX: Meta pixel, Conversion API, creative testing and campaign structure under your Business Manager.",
    primaryKeyword: "Facebook and Instagram ads",
    keywords: [
      "Facebook Ads",
      "Instagram Ads",
      "Meta ads management",
      "Facebook advertising agency",
      "Instagram advertising services",
    ],
    image: media.socialCreator,
    imageAlt: "Social creative being prepared for Facebook and Instagram ads",
    overview: [
      "Boosting a post is not an ads programme. WordbitX works in Business Manager: pixel, Conversion API where useful, audiences and a creative test plan.",
      "You own the ad account. We report on cost per result against the event you chose — purchase, lead or traffic — and say when the offer, not the algorithm, is the problem.",
    ],
    whoNeeds: [
      "Brands already posting that want paid reach with tracking",
      "Stores with a catalogue ready for Advantage+ shopping",
      "Lead-gen businesses tired of form spam",
      "Teams whose pixel was installed three times",
    ],
    problems: [
      { title: "Pixel chaos", text: "One dataset, one event map, duplicate page views removed." },
      { title: "Creative fatigue", text: "A test backlog instead of one static for six months." },
      { title: "Wrong objective", text: "Traffic campaigns cannot be judged as sales campaigns." },
    ],
    benefits: [
      { title: "Events that match finance", text: "We reconcile leads or purchases, not vanity clicks." },
      { title: "Catalogue optional", text: "Shops can use DPA when the feed is clean." },
      { title: "Clear roles", text: "Page, IG and ad account mapped in Business Manager." },
      { title: "Creative + media", text: "We can brief or produce the first ad set." },
    ],
    offerings: [
      { title: "Tracking", text: "Pixel, CAPI and event priorities." },
      { title: "Campaign build", text: "Prospecting, retargeting and exclusions." },
      { title: "Creative testing", text: "Hooks, angles and formats." },
      { title: "Monthly management", text: "Budgets, winners and kill list." },
    ],
    deliverables: [
      "Working pixel events",
      "Live campaigns in your ad account",
      "Monthly creative and spend notes",
    ],
    process: growthProcess,
    techStack: ["Meta Ads Manager", "Meta Business Suite", "Google Analytics", "Figma"],
    faqs: [
      { question: "Do you boost posts?", answer: "Only if it is the right tool. Most accounts need a real campaign with a conversion event." },
    ],
    related: ["facebook-instagram-shop", "graphic-design", "google-ads", "social-media-marketing"],
    relatedPosts: ["digital-marketing-for-software-companies", "how-to-launch-a-shopify-store"],
    projectCategory: "Websites",
  }),
  withServiceDefaults({
    slug: "tiktok-ads",
    title: "TikTok Ads",
    shortTitle: "TikTok Ads",
    icon: "marketing",
    h1: "TikTok Ads Management for Spark and In-Feed Campaigns",
    tagline:
      "TikTok ads that look like the platform — Spark Ads, in-feed and a pixel — not a 30-second TV commercial cropped to 9:16.",
    summary:
      "TikTok Ads account setup, pixel, creative format guidance and campaign management.",
    metaTitle: "TikTok Ads Management Services",
    metaDescription:
      "TikTok Ads management from WordbitX: pixel setup, Spark Ads, in-feed campaigns and creative testing for brands that already have a product or offer.",
    primaryKeyword: "TikTok Ads",
    keywords: [
      "TikTok Ads",
      "TikTok advertising",
      "TikTok ads management",
      "Spark Ads",
      "TikTok ads agency",
    ],
    image: media.socialContent,
    imageAlt: "Short-form video content being prepared for TikTok advertising",
    overview: [
      "TikTok rewards native creative and punishes polished brand films. WordbitX sets up the ads account and pixel, then tests hooks that can be shot on a phone if needed.",
      "If you have no offer or landing page, we stop you spending. Shop campaigns need a working TikTok Shop or landing experience first.",
    ],
    whoNeeds: [
      "DTC brands with a product that can be shown in 10 seconds",
      "Apps buying install or trial traffic",
      "Companies with organic TikTok that want paid amplification",
      "Teams expanding from Meta into a second short-form channel",
    ],
    problems: [
      { title: "Wrong creative", text: "We brief native formats, not resized Instagram carousels only." },
      { title: "No pixel", text: "Events are defined before scale." },
      { title: "Shop not ready", text: "We will send you to TikTok Shop setup first if that is the real gap." },
    ],
    benefits: [
      { title: "Platform-native tests", text: "Spark and in-feed with a kill/scale rule." },
      { title: "Your Business Center", text: "Spend and pixels stay with the company." },
      { title: "Honest learning budget", text: "We say when the account is too small to learn." },
      { title: "Optional creators", text: "We can brief UGC; we do not fake testimonials." },
    ],
    offerings: [
      { title: "Account & pixel", text: "TikTok Ads and Events Manager." },
      { title: "Campaigns", text: "Traffic, conversions or app depending on the goal." },
      { title: "Creative direction", text: "Hooks, shot lists and Spark setup." },
      { title: "Weekly optimisation", text: "Creative fatigue and audience notes." },
    ],
    deliverables: [
      "Ads account under your Business Center",
      "Live test campaigns as scoped",
      "Creative brief pack",
    ],
    process: growthProcess,
    techStack: ["TikTok Ads", "TikTok Shop", "Google Analytics"],
    faqs: [
      { question: "Do we need a huge follower count?", answer: "No. Ads can run to cold audiences. Followers help Spark social proof but are not a requirement." },
    ],
    related: ["tiktok-shop-setup", "facebook-instagram-ads", "graphic-design", "digital-marketing"],
    relatedPosts: ["digital-marketing-for-software-companies", "how-to-launch-a-shopify-store"],
    projectCategory: "Websites",
  }),
  withServiceDefaults({
    slug: "linkedin-ads",
    title: "LinkedIn Ads",
    shortTitle: "LinkedIn Ads",
    icon: "marketing",
    h1: "LinkedIn Ads for B2B Lead Generation",
    tagline:
      "Sponsored Content and lead gen forms aimed at job titles that can buy — expensive clicks used carefully, not sprayed at every employee in a country.",
    summary:
      "LinkedIn Campaign Manager setup, audience design, creative and lead-gen or website conversion campaigns.",
    metaTitle: "LinkedIn Ads Management | B2B PPC",
    metaDescription:
      "LinkedIn Ads management from WordbitX: Campaign Manager, job-title audiences, lead gen forms and Sponsored Content for B2B software and service companies.",
    primaryKeyword: "LinkedIn Ads",
    keywords: [
      "LinkedIn Ads",
      "LinkedIn advertising",
      "LinkedIn Ads management",
      "B2B LinkedIn ads",
      "LinkedIn lead gen ads",
    ],
    image: media.professionals,
    imageAlt: "B2B professionals in a meeting representing LinkedIn advertising audiences",
    overview: [
      "LinkedIn CPCs are high. That is fine when the audience is a buyer and the landing page asks for one action. WordbitX builds tight job, seniority and company-size filters and refuses vanity follower campaigns unless that is the brief.",
      "Lead gen forms versus website conversions is a trade-off we explain: more volume versus better-qualified form fills.",
    ],
    whoNeeds: [
      "B2B software and service firms selling to managers",
      "Companies with a webinar, demo or white paper offer",
      "Teams whose organic company page is ready but unpaid reach is tiny",
      "Exporters targeting UK, US, UAE or GCC job titles",
    ],
    problems: [
      { title: "Too-wide audiences", text: "We cut ‘all employees’ targeting that burns budget." },
      { title: "Weak offer", text: "A homepage is rarely enough. We recommend a demo or asset." },
      { title: "CRM disconnect", text: "Leads are routed to email or CRM, not left in Campaign Manager." },
    ],
    benefits: [
      { title: "Buyer-shaped reach", text: "Titles and industries you can defend to sales." },
      { title: "Message match", text: "Ad copy sounds like the landing page." },
      { title: "Your Campaign Manager", text: "Billing stays with the company." },
      { title: "Small tests first", text: "We do not recommend a huge always-on until CPL is known." },
    ],
    offerings: [
      { title: "Account setup", text: "Campaign Manager, pixels and matched audiences." },
      { title: "Lead gen or traffic", text: "Forms or website conversions." },
      { title: "Creative", text: "Document, single image or simple video ads." },
      { title: "Monthly management", text: "Audience and offer tests." },
    ],
    deliverables: [
      "Live campaigns under your page",
      "Audience and exclusion notes",
      "Lead routing confirmation",
    ],
    process: growthProcess,
    techStack: ["LinkedIn Campaign Manager", "Google Analytics", "HubSpot"],
    faqs: [
      { question: "Is LinkedIn cheaper than Google?", answer: "Usually no. It is for when job title targeting is the advantage. If your buyers search Google with intent, start there." },
    ],
    related: ["digital-marketing", "content-marketing", "google-ads", "seo-services"],
    relatedPosts: ["digital-marketing-for-software-companies", "how-seo-helps-businesses-grow"],
    projectCategory: "Websites",
  }),
  withServiceDefaults({
    slug: "email-marketing",
    title: "Email Marketing",
    shortTitle: "Email Marketing",
    icon: "marketing",
    h1: "Email Marketing Setup for Welcome, Nurture and Promotional Journeys",
    tagline:
      "Lists you own, automations that match the product, and campaigns that do not land in spam — not a purchased list we will not send to.",
    summary:
      "Email platform setup, list hygiene, welcome and abandoned flows, and campaign templates.",
    metaTitle: "Email Marketing Services | Automations & Campaigns",
    metaDescription:
      "Email marketing from WordbitX: ESP setup, welcome and abandoned-cart flows, list hygiene and campaign templates using lists you own — no purchased databases.",
    primaryKeyword: "email marketing services",
    keywords: [
      "email marketing services",
      "email marketing automation",
      "welcome email sequence",
      "abandoned cart email",
      "email marketing company",
    ],
    image: media.officeTeam,
    imageAlt: "Team planning an email marketing campaign calendar",
    overview: [
      "Email is one of the few channels you actually own. WordbitX connects a proper ESP, cleans the list and builds the two or three automations that pay: welcome, abandon and a simple newsletter cadence.",
      "We will not buy lists or scrape inboxes. That damages the domain and is not how we work.",
    ],
    whoNeeds: [
      "Stores with checkout but no abandoned-cart mail",
      "SaaS products with no onboarding sequence",
      "Teams sending from a personal Gmail to customers",
      "Brands whose domain is already close to spam",
    ],
    problems: [
      { title: "No SPF/DKIM", text: "We set authentication so providers trust the domain." },
      { title: "One giant blast", text: "Segments and automations replace ‘send to all’." },
      { title: "Dead list", text: "We sunset unengaged addresses instead of forcing opens." },
    ],
    benefits: [
      { title: "Revenue from existing users", text: "Reminders beat buying colder traffic." },
      { title: "Brand-safe sending", text: "Authentication and a physical address in the footer." },
      { title: "Templates your team can reuse", text: "Campaigns without a developer every Friday." },
      { title: "List you keep", text: "Export stays with you if you change ESP." },
    ],
    offerings: [
      { title: "ESP setup", text: "Klaviyo, Mailchimp, Brevo or similar — your choice." },
      { title: "Core automations", text: "Welcome, abandon, post-purchase or onboarding." },
      { title: "Campaign system", text: "Templates and a simple calendar." },
      { title: "Deliverability basics", text: "DNS auth and list hygiene." },
    ],
    deliverables: [
      "Authenticated sending domain",
      "Live automations as scoped",
      "Template set and how-to",
    ],
    process: growthProcess,
    techStack: ["Klaviyo", "Mailchimp", "Google Analytics", "Shopify"],
    faqs: [
      { question: "Can you send to a bought list?", answer: "No. We only mail people who opted in. Bought lists get domains blocked." },
    ],
    related: ["content-marketing", "ecommerce-shopify", "digital-marketing", "conversion-rate-optimization"],
    relatedPosts: ["digital-marketing-for-software-companies", "how-to-launch-a-shopify-store"],
    projectCategory: "Websites",
  }),
  withServiceDefaults({
    slug: "content-marketing",
    title: "Content Marketing",
    shortTitle: "Content Marketing",
    icon: "marketing",
    h1: "Content Marketing for Search, Sales Enablement and Authority",
    tagline:
      "Articles, guides and landing content mapped to keywords and sales questions — not a blog nobody internally will maintain.",
    summary:
      "Content strategy, service and industry pages, and editorial articles that support SEO and sales.",
    metaTitle: "Content Marketing Services | SEO Content & Guides",
    metaDescription:
      "Content marketing from WordbitX: keyword-led articles, service pages and sales-enablement guides written for software and service companies — not filler blogs.",
    primaryKeyword: "content marketing services",
    keywords: [
      "content marketing services",
      "SEO content writing",
      "B2B content marketing",
      "content marketing agency",
      "website content writing",
    ],
    image: media.businessMeeting,
    imageAlt: "Editors planning a content marketing calendar around business topics",
    overview: [
      "Content only works if someone will publish it and the pages are worth indexing. WordbitX plans topics from real queries and sales objections, then writes pages that a developer can ship with proper titles and internals links.",
      "We prefer fewer, useful URLs over a hundred thin posts. That matches how we already treat sitemaps on this site.",
    ],
    whoNeeds: [
      "Companies whose blog is empty or stuffed with AI filler",
      "Service businesses that need pages for new offerings",
      "B2B teams that need a guide sales can send",
      "Brands entering a new country market with localised pages",
    ],
    problems: [
      { title: "Orphan posts", text: "Every article links to a service or contact path." },
      { title: "Keyword stuffing", text: "We write for the query and the reader." },
      { title: "No owner", text: "We leave an editorial calendar your team can continue." },
    ],
    benefits: [
      { title: "Pages that can rank later", text: "Unique titles, H1s and internals — not duplicates." },
      { title: "Sales support", text: "Guides that answer ‘how does this work?’." },
      { title: "Honest volume", text: "A pace you can keep after we leave." },
      { title: "On-brand", text: "WordbitX-style spelling and claims stay conservative." },
    ],
    offerings: [
      { title: "Topic map", text: "Keywords clustered to URLs you should actually create." },
      { title: "Service & landing copy", text: "Pages like the ones on this site." },
      { title: "Editorial articles", text: "Guides with sources and FAQs." },
      { title: "Refresh", text: "Update old posts instead of always making new URLs." },
    ],
    deliverables: [
      "Content map",
      "Drafts in your CMS or Docs",
      "On-page SEO fields filled",
    ],
    process: growthProcess,
    techStack: ["Google Search Console", "Google Docs", "WordPress", "Next.js"],
    faqs: [
      { question: "Do you use AI to write everything?", answer: "We may outline with tools. Published pages are edited by a person who understands the service. Thin AI blogs are how sites earn ‘crawled, not indexed’." },
    ],
    related: ["seo-services", "digital-marketing", "linkedin-ads", "web-development"],
    relatedPosts: ["seo-guide-for-businesses", "how-seo-helps-businesses-grow"],
    projectCategory: "Websites",
  }),
  withServiceDefaults({
    slug: "online-reputation-management",
    title: "Online Reputation Management",
    shortTitle: "ORM",
    icon: "marketing",
    h1: "Online Reputation Management for Reviews, Search Results and Brand Mentions",
    tagline:
      "Review generation, response playbooks and truthful brand pages — we do not sell fake reviews or hidden ‘suppression’ tricks.",
    summary:
      "ORM: review strategy, response templates, brand SERP cleanup of what you control, and listing accuracy.",
    metaTitle: "Online Reputation Management (ORM) Services",
    metaDescription:
      "Online reputation management from WordbitX: review strategy, response playbooks and brand listing cleanup. We do not sell fake reviews or illegal suppression.",
    primaryKeyword: "online reputation management",
    keywords: [
      "online reputation management",
      "ORM services",
      "review management services",
      "Google review strategy",
      "brand reputation management",
    ],
    image: media.professionals,
    imageAlt: "Leadership team discussing brand reputation and customer reviews",
    overview: [
      "Reputation work that lasts is boring: ask happy customers legally, reply to every review, and fix the listings you own. WordbitX will not post fake Google or marketplace reviews or promise to bury news articles overnight.",
      "We can improve what you control — GBP, website, profiles — and give you a response process. Legal takedowns stay with a lawyer.",
    ],
    whoNeeds: [
      "Local businesses with few or outdated reviews",
      "Brands whose old name or phone still ranks",
      "Companies that never reply to public feedback",
      "Teams launching a new company page after an old one went stale",
    ],
    problems: [
      { title: "No review habit", text: "A simple, policy-safe ask after a completed job." },
      { title: "Wrong listings", text: "We align name, site and phone on the profiles you still have access to." },
      { title: "Silence", text: "Templates for thanks and for unhappy customers." },
    ],
    benefits: [
      { title: "Trust you can show", text: "Real reviews on the profiles buyers check." },
      { title: "Faster replies", text: "Staff know what they are allowed to say." },
      { title: "Cleaner brand SERP", text: "Owned pages and profiles tell one story." },
      { title: "No policy landmines", text: "We stay inside Google and platform rules." },
    ],
    offerings: [
      { title: "Review programme", text: "When and how to ask — never incentives that break ToS." },
      { title: "Response playbook", text: "Tone and escalation." },
      { title: "Listing cleanup", text: "GBP and major profiles you control." },
      { title: "Brand page advice", text: "What to publish so your own site ranks for the brand." },
    ],
    deliverables: [
      "Review SOP",
      "Updated priority profiles",
      "Monthly mention or review notes if retained",
    ],
    process: growthProcess,
    techStack: ["Google Business Profile", "Google Search Console"],
    faqs: [
      { question: "Can you remove a bad review?", answer: "Only the platform can, and only if it breaks their rules. We can help you flag and reply. We will not sell fake counter-reviews." },
    ],
    related: ["local-seo", "social-media-marketing", "content-marketing", "digital-marketing"],
    relatedPosts: ["how-seo-helps-businesses-grow", "digital-marketing-for-software-companies"],
    projectCategory: "Websites",
  }),
  withServiceDefaults({
    slug: "web-hosting",
    title: "Web Hosting, Domain & Email",
    shortTitle: "Hosting & Domains",
    icon: "devops",
    h1: "Web Hosting, Domain Registration, SSL and Business Email",
    tagline:
      "Domains, DNS, SSL, hosting and mailbox setup under accounts you own — so a vendor change does not take the company offline.",
    summary:
      "Domain registration guidance, DNS, SSL, web or cloud hosting and business email setup.",
    metaTitle: "Web Hosting, Domain Registration & Business Email",
    metaDescription:
      "Domain registration, web hosting, cloud hosting, SSL and business email from WordbitX — billed in your name, so the website is never held hostage.",
    primaryKeyword: "web hosting and domain registration",
    keywords: [
      "web hosting services",
      "domain registration",
      "cloud hosting",
      "SSL installation",
      "business email setup",
    ],
    image: media.serverRacks,
    imageAlt: "Server infrastructure representing web and cloud hosting",
    overview: [
      "Hosting problems are usually ownership problems: the domain is on a freelancer’s card, SSL auto-renew is off, mail is a free Gmail. WordbitX puts domain, DNS, certificate, site and mail in the company’s registrar and cloud accounts.",
      "We recommend a host that matches the stack — Vercel, a VPS or a managed WordPress host — not a one-size reseller plan.",
    ],
    whoNeeds: [
      "Companies launching a first professional site and mailbox",
      "Teams whose site lives on a developer’s personal hosting",
      "Brands that need SSL, redirects and www/apex handled correctly",
      "Offices moving from personal email to @yourdomain",
    ],
    problems: [
      { title: "Lost domains", text: "We use your registrar login and enable lock plus 2FA." },
      { title: "Mixed www and apex", text: "One canonical host, the other redirects — the way search engines expect." },
      { title: "Mail that looks untrusted", text: "SPF, DKIM and a real mailbox, not a spoofed From line." },
    ],
    benefits: [
      { title: "You can fire anyone", text: "Access is documented and transferable." },
      { title: "HTTPS by default", text: "Certificates renew automatically." },
      { title: "Right-sized hosting", text: "We do not sell unused dedicated servers." },
      { title: "Email that matches the brand", text: "info@ and staff mailboxes on the domain." },
    ],
    offerings: [
      { title: "Domain & DNS", text: "Registration advice, records and redirects." },
      { title: "Hosting", text: "Web, VPS or cloud — chosen for the stack." },
      { title: "SSL", text: "Certificates and mixed-content cleanup." },
      { title: "Business email", text: "Google Workspace, Microsoft 365 or host mail." },
    ],
    deliverables: [
      "Accounts under the company",
      "Live DNS and HTTPS",
      "Mailbox and auth records",
      "Access sheet for IT",
    ],
    techStack: ["Cloudflare", "Google Workspace", "Vercel", "cPanel"],
    faqs: [
      { question: "Do you sell domains yourself?", answer: "We recommend a registrar and complete setup. You pay the registrar. We do not trap domains on an agency account." },
    ],
    related: ["website-security", "website-maintenance", "devops-cloud-solutions", "web-development"],
    relatedPosts: ["website-development-cost-pakistan", "website-speed-and-seo"],
    projectCategory: "Websites",
  }),
  withServiceDefaults({
    slug: "website-maintenance",
    title: "Website Maintenance",
    shortTitle: "Website Maintenance",
    icon: "web",
    h1: "Website Maintenance, Updates and Technical Support",
    tagline:
      "Updates, backups, small content changes and uptime checks — so the site does not silently die after launch.",
    summary:
      "Monthly website maintenance: CMS and plugin updates, backups, uptime, small edits and technical support.",
    metaTitle: "Website Maintenance & Technical Support Services",
    metaDescription:
      "Website maintenance from WordbitX: updates, backups, uptime monitoring, small content changes and technical support after launch.",
    primaryKeyword: "website maintenance",
    keywords: [
      "website maintenance services",
      "website support",
      "WordPress maintenance",
      "website updates",
      "technical support for websites",
    ],
    image: media.deskTeam,
    imageAlt: "Support team handling website updates and maintenance tasks",
    overview: [
      "Launch is the start of decay: CMS updates, broken forms, expired certificates, a plugin conflict. WordbitX offers a monthly block of hours for updates, backups and the small tickets that should not become a new project.",
      "Security hardening is a sister service if you need a one-off audit. Maintenance is the ongoing rhythm.",
    ],
    whoNeeds: [
      "WordPress or WooCommerce sites that nobody updates",
      "Marketing sites that need weekly copy tweaks",
      "Companies without an in-house developer",
      "Teams that want a named Slack or email for ‘the site is down’",
    ],
    problems: [
      { title: "Abandoned updates", text: "Core, plugins and dependencies on a schedule." },
      { title: "No backups", text: "Tested restore, not only a host checkbox." },
      { title: "Ticket pile-up", text: "A backlog you can see: done, deferred, out of scope." },
    ],
    benefits: [
      { title: "Predictable cost", text: "Hours instead of emergency invoices only." },
      { title: "Faster small changes", text: "Copy and image swaps without a quote each time." },
      { title: "Uptime visibility", text: "We notice before your customer tweets." },
      { title: "Clear extras", text: "New features are quoted, not hidden in maintenance." },
    ],
    offerings: [
      { title: "Updates & backups", text: "CMS, dependencies and restore tests." },
      { title: "Content tickets", text: "Agreed hours for edits." },
      { title: "Uptime & SSL watch", text: "Alerts and certificate renewals." },
      { title: "Technical support", text: "Form, mail and hosting issues." },
    ],
    deliverables: [
      "Monthly report of updates and hours",
      "Backup confirmation",
      "Ticket log",
    ],
    process: growthProcess,
    techStack: ["WordPress", "Next.js", "Cloudflare", "Google Analytics"],
    faqs: [
      { question: "Is hosting included?", answer: "Hosting is billed to you. We can manage it as part of hosting & domains. Maintenance is the labour on top." },
    ],
    related: ["website-security", "web-hosting", "wordpress-development", "web-development"],
    relatedPosts: ["wordpress-vs-custom-website", "website-speed-and-seo"],
    projectCategory: "Websites",
  }),
  withServiceDefaults({
    slug: "website-security",
    title: "Website Security",
    shortTitle: "Website Security",
    icon: "devops",
    h1: "Website Security Hardening, SSL and Malware Cleanup",
    tagline:
      "Updates, firewall rules, SSL, least-privilege users and cleanup if you already have malware — not a sticker that says ‘secure’.",
    summary:
      "Security hardening: SSL, access control, malware removal, WAF and backup verification.",
    metaTitle: "Website Security Services | SSL, Hardening & Cleanup",
    metaDescription:
      "Website security from WordbitX: SSL, access hardening, malware cleanup, WAF and backup verification for WordPress, WooCommerce and custom sites.",
    primaryKeyword: "website security services",
    keywords: [
      "website security",
      "website malware removal",
      "SSL installation",
      "WordPress security",
      "website hardening",
    ],
    image: media.serverBlue,
    imageAlt: "Secure server environment representing website hardening and SSL",
    overview: [
      "Most compromises are old plugins, reused passwords and no 2FA. WordbitX hardens what you have: users, SSH or wp-admin access, backups, SSL and a WAF when it helps.",
      "If the site is already infected, we clean, rotate secrets and tell you what was exposed. We do not sell fake ‘military grade’ badges.",
    ],
    whoNeeds: [
      "WordPress sites with unknown admin users",
      "Stores handling payments that never had a review",
      "Teams that saw a Google Safe Browsing warning",
      "Companies moving off a shared host after a hack",
    ],
    problems: [
      { title: "Spam injections", text: "We remove malware and close the entry, not only the visible pages." },
      { title: "Shared logins", text: "Named users and 2FA replace ‘admin / password’." },
      { title: "HTTP leftovers", text: "SSL and redirects so mixed content does not linger." },
    ],
    benefits: [
      { title: "Fewer open doors", text: "Unused plugins and users gone." },
      { title: "Recoverability", text: "Backups you have actually restored once." },
      { title: "Clear incident notes", text: "What happened and what to tell customers if data was involved." },
      { title: "Optional retain", text: "Hardening then monthly maintenance." },
    ],
    offerings: [
      { title: "Hardening", text: "Access, headers, updates and file permissions." },
      { title: "Malware cleanup", text: "Infected CMS or server files." },
      { title: "SSL & HTTPS", text: "Certificates and canonical redirects." },
      { title: "WAF / CDN rules", text: "Cloudflare or host WAF tuned to the app." },
    ],
    deliverables: [
      "Hardening checklist completed",
      "Cleanup report if incident work",
      "Credential rotation list",
    ],
    techStack: ["Cloudflare", "WordPress", "Let's Encrypt", "Fail2ban"],
    faqs: [
      { question: "Can you guarantee we will never be hacked?", answer: "No one can. We reduce obvious risk and improve recovery. Keep maintenance going or the same hole returns." },
    ],
    related: ["website-maintenance", "web-hosting", "wordpress-development", "devops-cloud-solutions"],
    relatedPosts: ["wordpress-vs-custom-website", "website-speed-and-seo"],
    projectCategory: "Websites",
  }),
  withServiceDefaults({
    slug: "it-consulting",
    title: "IT & Digital Transformation Consulting",
    shortTitle: "IT Consulting",
    icon: "software",
    h1: "IT Consulting and Digital Transformation for Growing Companies",
    tagline:
      "A written stack and sequence — what to buy, what to build, what to stop — before you spend another year on the wrong tool.",
    summary:
      "IT and digital transformation consulting: systems review, build-vs-buy, integration map and a phased roadmap.",
    metaTitle: "IT Consulting & Digital Transformation Services",
    metaDescription:
      "IT consulting and digital transformation from WordbitX: systems review, build-versus-buy, integration maps and a phased roadmap for growing companies.",
    primaryKeyword: "IT consulting",
    keywords: [
      "IT consulting",
      "digital transformation consulting",
      "IT consultant Pakistan",
      "software consulting",
      "digital transformation services",
    ],
    image: media.businessMeeting,
    imageAlt: "Consultants mapping systems and a digital transformation roadmap",
    overview: [
      "Transformation is a sequence of replacements, not a slogan. WordbitX interviews operations and IT, maps the current tools, and writes what to keep, integrate or rebuild — with costs in ranges, not theatre.",
      "If the answer is ‘buy a known SaaS and configure it’, we say that. We do not invent a custom platform to win a build contract.",
    ],
    whoNeeds: [
      "Owners drowning in disconnected SaaS and spreadsheets",
      "Companies planning POS, ERP or a client portal and unsure where to start",
      "Teams burned by a failed implementation",
      "Exporters that need a stack that can serve more than one country",
    ],
    problems: [
      { title: "Tool sprawl", text: "We list overlaps and the cheapest thing to turn off." },
      { title: "No owner", text: "Every system gets an internal owner in the plan." },
      { title: "Big-bang fear", text: "Phases that each produce a working slice." },
    ],
    benefits: [
      { title: "A decision document", text: "Leadership can approve or reject with eyes open." },
      { title: "Honest build vs buy", text: "Custom only where it pays." },
      { title: "Integration picture", text: "What must talk to what, and how." },
      { title: "Optional delivery", text: "You can hire us to implement the first phase — or not." },
    ],
    offerings: [
      { title: "Systems audit", text: "Interviews, access review and pain map." },
      { title: "Roadmap", text: "90-day and 12-month sequence." },
      { title: "Vendor shortlist", text: "When SaaS is the answer." },
      { title: "Implementation oversight", text: "Optional: we stay as the technical conscience." },
    ],
    deliverables: [
      "Current-state map",
      "Recommended target architecture",
      "Phased budget ranges",
    ],
    techStack: ["Notion", "Figma", "Google Workspace", "PostgreSQL"],
    faqs: [
      { question: "Is this only for large enterprises?", answer: "No. A 10-person company with three broken tools needs the same honesty. The document is just shorter." },
    ],
    related: ["enterprise-software-solutions", "crm-erp-solutions", "custom-software-development", "devops-cloud-solutions"],
    relatedPosts: ["custom-software-vs-ready-made-software", "crm-vs-erp-which-one-does-your-business-need"],
    projectCategory: "Software",
  }),
];
