import type { Service } from "@/lib/types";
import { media } from "@/lib/media";

export const servicesA: Service[] = [
  {
    slug: "web-development",
    title: "Website Development",
    shortTitle: "Website Development",
    icon: "web",
    h1: "Website Development Company Building Fast, Search-Ready Websites",
    tagline:
      "Custom website development for businesses that need speed, structure and search visibility — not another slow template.",
    summary:
      "Custom, high-performance business websites and web applications engineered for conversions, Core Web Vitals and long-term SEO.",
    metaTitle: "Website Development Company | Custom Business Websites",
    metaDescription:
      "WordBitX is a custom website development company building fast, responsive, SEO-ready websites and web applications with Next.js, React and modern backends.",
    primaryKeyword: "website development company",
    keywords: [
      "website development company",
      "custom website development",
      "web development services",
      "professional website development",
      "custom web development company",
    ],
    image: media.engineerCoding,
    imageAlt: "Web developer building a custom responsive website interface on a large monitor",
    overview: [
      "A website is usually the first working product a customer experiences from your business. WordBitX builds custom websites and web applications from the ground up — clean information architecture, component-based front ends, server-rendered pages for search engines, and a backend that your team can actually operate.",
      "We do not start from a bloated theme and remove features. We start from your goals, define the pages and journeys that create enquiries, then engineer only what is needed. The result is a lighter site, faster loading, better Core Web Vitals and a structure that search engines can crawl and understand.",
    ],
    whoNeeds: [
      "Businesses stuck with a slow, outdated or hard-to-edit website",
      "Startups launching a product, SaaS or marketplace front end",
      "Companies that get traffic but very few enquiries",
      "Organisations needing custom portals, dashboards or booking systems",
      "Brands expanding to international markets with multi-language needs",
    ],
    problems: [
      {
        title: "Slow pages that lose visitors",
        text: "Heavy themes, unoptimised images and plugin overload push load times past the point where most mobile users leave. We rebuild with server rendering, image optimisation and a minimal JavaScript footprint.",
      },
      {
        title: "Traffic that never converts",
        text: "Unclear messaging, weak calls to action and confusing navigation waste your marketing spend. We design page flows around a single decision per screen.",
      },
      {
        title: "Content nobody can update",
        text: "If every text change needs a developer, your website stops evolving. We connect a headless or traditional CMS so your team ships updates independently.",
      },
    ],
    benefits: [
      { title: "Faster loading", text: "Optimised assets, caching and modern rendering strategies improve Core Web Vitals and mobile experience." },
      { title: "Search-ready by default", text: "Semantic HTML, clean URLs, metadata, schema and XML sitemaps are built in — not added later." },
      { title: "Higher conversion", text: "Clear hierarchy, persuasive structure and tested CTA placement turn visits into enquiries." },
      { title: "Room to grow", text: "Component libraries and typed APIs make future pages, languages and features cheap to add." },
    ],
    offerings: [
      { title: "Custom business websites", text: "Corporate, service and multi-location websites with a scalable content model." },
      { title: "Web applications", text: "Dashboards, portals, booking engines and internal tools with role-based access." },
      { title: "Landing pages & funnels", text: "Campaign pages built for paid traffic with analytics and A/B ready structure." },
      { title: "Migrations & rebuilds", text: "Replatforming from legacy sites with URL mapping and 301 redirects that protect rankings." },
    ],
    deliverables: [
      "Responsive design system with reusable UI components",
      "Server-rendered or statically generated pages",
      "CMS integration with editor-friendly content models",
      "On-page SEO setup: metadata, headings, schema, sitemap, robots",
      "Analytics, Tag Manager and Search Console configuration",
      "Performance, accessibility and cross-browser QA report",
    ],
    process: [
      { step: "01", title: "Discovery & sitemap", text: "Goals, audience, competitors, keyword themes and a page-level sitemap." },
      { step: "02", title: "UX wireframes", text: "Low-fidelity layouts for every template before a single pixel of visual design." },
      { step: "03", title: "UI design", text: "Brand-aligned high-fidelity screens, responsive states and a component library." },
      { step: "04", title: "Development", text: "Front end, CMS, integrations and SEO foundations built in sprints with staging previews." },
      { step: "05", title: "Launch & support", text: "Redirects, indexing checks, monitoring and a post-launch optimisation window." },
    ],
    techStack: ["Next.js", "React", "TypeScript", "Node.js", "Laravel", "PostgreSQL", "Tailwind CSS", "Cloudflare"],
    whyUs: [
      { title: "Engineering, not theming", text: "Every build is custom code you own, with no licence lock-in or plugin sprawl." },
      { title: "SEO built into the sprint", text: "Technical SEO is part of development, so you launch indexable instead of retrofitting." },
      { title: "Performance budgets", text: "We set target load times and page weights before development starts and test against them." },
      { title: "Clear handover", text: "Documentation, editor training and a maintenance plan so the site keeps working after launch." },
    ],
    faqs: [
      { question: "How long does a custom website take?", answer: "A focused business website typically takes 4–7 weeks. Larger sites with custom portals, integrations or multi-language content usually run 8–14 weeks. You get a milestone plan before we start." },
      { question: "Will my rankings survive a rebuild?", answer: "Yes, when the migration is handled properly. We map every existing URL, implement 301 redirects, keep valuable content, and validate indexing in Google Search Console after launch." },
      { question: "Can we update content ourselves?", answer: "Absolutely. We connect a CMS with structured fields and train your team, so pages, blogs and media can be edited without touching code." },
    ],
    related: ["custom-web-application-development", "wordpress-development", "seo-services", "woocommerce-development"],
    relatedPosts: ["website-development-cost-pakistan", "how-to-choose-a-web-development-company"],
    projectCategory: "Websites",
    featured: true,
  },
  {
    slug: "mobile-app-development",
    title: "Mobile App Development",
    shortTitle: "Mobile Apps",
    icon: "mobile",
    h1: "Mobile App Development Company for Android & iOS Products",
    tagline:
      "Native and cross-platform apps built with Flutter, React Native, Kotlin and Swift — designed for real users and store approval.",
    summary:
      "Android and iOS applications from concept to store launch, with offline support, secure APIs and analytics baked in.",
    metaTitle: "Mobile App Development Company | Android & iOS",
    metaDescription:
      "WordbitX is a mobile app development company: custom Android and iOS apps with Flutter, React Native, Kotlin and Swift — from MVP to store launch.",
    primaryKeyword: "mobile app development company",
    keywords: [
      "mobile app development company",
      "app development company",
      "Android app development",
      "iOS app development",
      "Flutter app development",
      "custom mobile app development",
    ],
    image: media.deliveryApp,
    imageAlt: "Customer using a custom mobile application on a smartphone",
    overview: [
      "Users judge an app in the first thirty seconds. WordBitX builds mobile applications that load fast, work on unreliable networks, respect platform conventions, and pass App Store and Google Play review the first time.",
      "We usually recommend Flutter or React Native when one codebase can serve both platforms, and native Kotlin or Swift when the product depends on deep hardware access or platform-specific performance. The recommendation always follows your feature set and budget — never the other way around.",
    ],
    whoNeeds: [
      "Startups validating an idea with a lean, well-built MVP",
      "Service businesses that need booking, delivery or field-team apps",
      "Retailers extending an online store into a shopping app",
      "Companies replacing paper processes with mobile workflows",
      "Products with an existing app that is slow, unstable or unmaintained",
    ],
    problems: [
      { title: "MVPs that cost too much", text: "Scope creep kills early apps. We define a release-one feature set that can be shipped, measured and extended." },
      { title: "Apps rejected by stores", text: "Privacy policies, permissions, data safety forms and payment rules cause most rejections. We prepare submissions properly." },
      { title: "Poor retention after install", text: "Slow first load, confusing onboarding and no push strategy lose users in week one. We instrument analytics from day one." },
    ],
    benefits: [
      { title: "One codebase, two platforms", text: "Cross-platform delivery reduces build and maintenance cost without a compromised experience." },
      { title: "Offline-first behaviour", text: "Local caching and sync queues keep the app usable on weak connections." },
      { title: "Secure by design", text: "Token-based auth, encrypted storage and hardened API endpoints protect user data." },
      { title: "Measurable growth", text: "Event tracking, crash reporting and store analytics show exactly where users drop off." },
    ],
    offerings: [
      { title: "Cross-platform apps", text: "Flutter and React Native products with shared business logic and platform-aware UI." },
      { title: "Native development", text: "Kotlin for Android and Swift for iOS when performance or hardware access demands it." },
      { title: "Backend & APIs", text: "Authentication, notifications, payments, real-time features and admin dashboards." },
      { title: "Store launch & updates", text: "Store listings, screenshots, release management and versioned update cycles." },
    ],
    deliverables: [
      "Clickable UX prototype before development",
      "Android (.aab) and iOS builds with signed release pipelines",
      "REST or GraphQL backend with documented endpoints",
      "Push notifications, deep links and in-app analytics",
      "Store listing assets and submission support",
      "Crash monitoring and a post-launch stabilisation sprint",
    ],
    process: [
      { step: "01", title: "Product definition", text: "User stories, release-one scope, platform choice and technical feasibility." },
      { step: "02", title: "UX & prototype", text: "Flow maps and an interactive prototype validated before code." },
      { step: "03", title: "Build sprints", text: "Two-week sprints with installable test builds at the end of each." },
      { step: "04", title: "QA on real devices", text: "Functional, performance, network and device-matrix testing." },
      { step: "05", title: "Launch & iterate", text: "Store submission, monitoring, and improvements driven by real usage data." },
    ],
    techStack: ["Flutter", "Dart", "React Native", "Kotlin", "Swift", "Node.js", "Firebase", "PostgreSQL"],
    whyUs: [
      { title: "Product thinking first", text: "We challenge features that will not earn their place in release one." },
      { title: "Store expertise", text: "We handle data safety declarations, privacy requirements and review responses." },
      { title: "Real-device QA", text: "Testing across screen sizes and OS versions, not just simulators." },
      { title: "Maintenance plans", text: "OS updates arrive every year; we keep your app compatible and secure." },
    ],
    faqs: [
      { question: "How much does a mobile app cost?", answer: "A focused MVP with authentication, core workflow and admin panel usually starts around the mid four figures in USD; feature-rich marketplaces or fintech-style apps cost significantly more. We provide a written scope and fixed milestone pricing after discovery." },
      { question: "Flutter or native — which is better?", answer: "Flutter suits most business apps: one codebase, fast delivery, near-native performance. Choose native when you need heavy graphics, complex background processing or the latest platform-only APIs." },
      { question: "Do you publish the app for us?", answer: "Yes. We prepare listings, screenshots and compliance forms, and publish under your developer accounts so you always own the app." },
    ],
    related: ["flutter-app-development", "app-store-optimization", "firebase-integration", "app-maintenance"],
    relatedPosts: ["mobile-app-development-guide", "flutter-app-development-benefits"],
    projectCategory: "Mobile Apps",
    featured: true,
  },
  {
    slug: "custom-software-development",
    title: "Custom Software Development",
    shortTitle: "Custom Software",
    icon: "software",
    h1: "Custom Software Development Services for Growing Businesses",
    tagline:
      "Business software shaped around your workflow — not a subscription you have to bend your operations to fit.",
    summary:
      "Bespoke business platforms, internal tools and integrations that remove manual work and connect your existing systems.",
    metaTitle: "Custom Software Development Company | Business Software Services",
    metaDescription:
      "Custom software development services from WordbitX: bespoke business applications, internal tools, integrations and automation for your workflow.",
    primaryKeyword: "custom software development",
    keywords: [
      "custom software development",
      "software development company",
      "software development services",
      "business software development",
      "custom application development",
    ],
    image: media.teamDevelopers,
    imageAlt: "Software engineering team collaborating on a custom business application",
    overview: [
      "Off-the-shelf tools cover the average case. When your process is your advantage — pricing rules, approval chains, production steps, franchise structures — generic software forces workarounds that cost hours every week.",
      "WordBitX builds custom software around how your business actually operates. We map the workflow, model the data properly, and deliver a system with the reporting, permissions and integrations your team needs, then keep improving it as the business changes.",
    ],
    whoNeeds: [
      "Teams running critical operations on spreadsheets and WhatsApp",
      "Businesses paying for several tools that still do not talk to each other",
      "Companies with a process no SaaS product supports",
      "Organisations needing role-based access and audit trails",
      "Founders building a software product to sell",
    ],
    problems: [
      { title: "Manual data re-entry", text: "The same order or record typed into three systems creates errors and lost hours. We integrate and automate the handoffs." },
      { title: "No single source of truth", text: "Conflicting spreadsheets make reporting unreliable. A modelled database gives one authoritative record." },
      { title: "Software that cannot scale", text: "Tools built for ten users collapse at a hundred. We design schemas, indexes and queues for real growth." },
    ],
    benefits: [
      { title: "Exact process fit", text: "The software follows your workflow, including the exceptions that generic tools ignore." },
      { title: "Lower long-term cost", text: "No per-seat licences that increase every time you hire." },
      { title: "Real-time visibility", text: "Dashboards and exports that reflect live operational data." },
      { title: "You own the asset", text: "Source code, database and documentation belong to your business." },
    ],
    offerings: [
      { title: "Business platforms", text: "Operations, inventory, HR, logistics and finance systems tailored to your rules." },
      { title: "Internal tools", text: "Admin panels, approval workflows and reporting consoles for your team." },
      { title: "System integration", text: "Connecting accounting, CRM, POS, marketplaces and payment gateways through APIs." },
      { title: "Legacy modernisation", text: "Migrating ageing desktop or Access-era systems to secure web applications." },
    ],
    deliverables: [
      "Workflow map and data model documentation",
      "Modular application with role-based permissions",
      "Reporting dashboards and CSV/Excel exports",
      "API layer with authentication and rate limiting",
      "Automated backups and environment setup",
      "Admin documentation and user training sessions",
    ],
    process: [
      { step: "01", title: "Process discovery", text: "Interviews and shadowing to document how work really happens today." },
      { step: "02", title: "Architecture", text: "Data model, module breakdown, integration plan and phased release map." },
      { step: "03", title: "Iterative build", text: "Module-by-module delivery with your team reviewing working software every sprint." },
      { step: "04", title: "Data migration & UAT", text: "Import existing records, run parallel testing and refine before switchover." },
      { step: "05", title: "Rollout & support", text: "Training, phased rollout and an ongoing enhancement backlog." },
    ],
    techStack: ["Node.js", "TypeScript", "Laravel", "Python", ".NET", "PostgreSQL", "Docker", "AWS"],
    whyUs: [
      { title: "We map before we code", text: "Discovery output is a document you can validate, not an assumption we build on." },
      { title: "Phased delivery", text: "Value ships in weeks, not after a year-long waterfall project." },
      { title: "Maintainable code", text: "Typed, tested and documented so another team could pick it up." },
      { title: "Integration experience", text: "Payments, accounting, shipping, marketplaces and messaging APIs." },
    ],
    faqs: [
      { question: "Is custom software cheaper than SaaS?", answer: "Not on day one. It usually wins over two to three years when licence fees, workaround labour and lost efficiency are included — and you keep an asset instead of renting one." },
      { question: "Do we own the source code?", answer: "Yes. Full ownership of code, database and documentation transfers to you, delivered in your own repository." },
      { question: "Can you work with our existing systems?", answer: "Yes. Most projects integrate with software you already use. We build API bridges or scheduled syncs rather than forcing a full replacement." },
    ],
    related: ["saas-application-development", "api-development", "enterprise-software-solutions", "crm-erp-solutions"],
    relatedPosts: ["custom-software-vs-ready-made-software", "crm-vs-erp-which-one-does-your-business-need"],
    projectCategory: "Software",
    featured: true,
  },
  {
    slug: "ai-solutions",
    title: "Artificial Intelligence Solutions",
    shortTitle: "AI Solutions",
    icon: "ai",
    h1: "AI Development Company Building Practical Business AI Solutions",
    tagline:
      "AI that removes repetitive work — document processing, support automation, forecasting and intelligent search.",
    summary:
      "Custom AI and automation solutions: assistants, document intelligence, recommendation engines and predictive analytics.",
    metaTitle: "AI Development Company | Artificial Intelligence Solutions & Automation",
    metaDescription:
      "WordBitX builds custom AI solutions for business: AI assistants, document processing, recommendation engines, predictive analytics and workflow automation.",
    primaryKeyword: "AI development company",
    keywords: [
      "AI development company",
      "artificial intelligence solutions",
      "AI software development",
      "custom AI solutions",
      "AI automation services",
    ],
    image: media.aiNeural,
    imageAlt: "Abstract neural network visualisation representing custom AI solutions",
    overview: [
      "Most businesses do not need a research lab — they need a handful of repetitive, expensive tasks handled reliably. WordBitX builds applied AI: systems that read documents, answer customer questions from your own knowledge base, classify records, forecast demand and trigger the next action automatically.",
      "We start with a narrow, measurable use case, connect it to your real data, and put guardrails around it: human review where accuracy matters, logging for every decision, and clear fallbacks when the model is unsure.",
    ],
    whoNeeds: [
      "Support teams answering the same questions hundreds of times a week",
      "Operations teams manually reading invoices, CVs or forms",
      "E-commerce brands wanting smarter search and recommendations",
      "Businesses sitting on data they never turn into forecasts",
      "Product teams adding AI features to an existing application",
    ],
    problems: [
      { title: "Hours lost to manual review", text: "Reading and re-keying documents does not scale. Extraction pipelines handle the volume with human checks on exceptions." },
      { title: "Generic chatbots that frustrate users", text: "Scripted bots fail on real questions. Retrieval-augmented assistants answer from your actual content with citations." },
      { title: "AI pilots that never ship", text: "Experiments stall without integration. We deliver into your existing systems with monitoring and cost controls." },
    ],
    benefits: [
      { title: "Faster turnaround", text: "Tasks that took hours complete in seconds, with people reviewing only the edge cases." },
      { title: "Answers grounded in your data", text: "Retrieval pipelines keep responses tied to approved company content." },
      { title: "Controlled cost", text: "Model routing, caching and token budgets keep monthly spend predictable." },
      { title: "Auditability", text: "Every request, response and confidence score is logged for review." },
    ],
    offerings: [
      { title: "AI assistants & chat", text: "Internal and customer-facing assistants trained on your documents and policies." },
      { title: "Document intelligence", text: "OCR and extraction for invoices, contracts, KYC files and forms." },
      { title: "Predictive analytics", text: "Demand, churn and inventory forecasting from your historical data." },
      { title: "Workflow automation", text: "Classification, routing and summarisation wired into your existing tools." },
    ],
    deliverables: [
      "Use-case assessment with expected accuracy and ROI",
      "Data pipeline and vector index for retrieval",
      "Model integration with prompt and safety layer",
      "Human-in-the-loop review interface",
      "Evaluation set and accuracy reporting",
      "Cost monitoring dashboard and usage alerts",
    ],
    process: [
      { step: "01", title: "Opportunity mapping", text: "Identify tasks with volume, rules and measurable cost." },
      { step: "02", title: "Data readiness", text: "Collect, clean and structure the data the model will rely on." },
      { step: "03", title: "Prototype", text: "A working proof of concept measured against a real evaluation set." },
      { step: "04", title: "Productionise", text: "Integration, guardrails, logging, permissions and cost controls." },
      { step: "05", title: "Monitor & improve", text: "Track accuracy and drift, then refine prompts, data and routing." },
    ],
    techStack: ["Python", "OpenAI", "LangChain", "Node.js", "PostgreSQL", "Redis", "Docker", "Google Cloud"],
    whyUs: [
      { title: "Use cases with a business case", text: "We decline AI projects that cannot be measured — and say so early." },
      { title: "Engineering discipline", text: "Versioned prompts, evaluation sets and regression checks before every release." },
      { title: "Privacy aware", text: "Data handling, retention and redaction agreed before any integration goes live." },
      { title: "Built into your stack", text: "AI features live inside the tools your team already uses." },
    ],
    faqs: [
      { question: "Do we need a large dataset to start?", answer: "Not for most use cases. Retrieval-based assistants work with your existing documents. Custom forecasting models benefit from historical data, and we assess what you have during discovery." },
      { question: "Will our data be used to train public models?", answer: "No. We configure enterprise API settings that exclude your data from training, and can deploy self-hosted models when policy requires it." },
      { question: "How accurate is it?", answer: "Accuracy depends on the task. We agree a target with you, measure against a labelled evaluation set, and route low-confidence cases to a human reviewer." },
    ],
    related: ["custom-software-development", "mobile-app-development", "devops-cloud-solutions", "digital-marketing"],
    relatedPosts: ["how-ai-automation-helps-businesses", "custom-software-vs-ready-made-software"],
    projectCategory: "AI",
    featured: true,
  },
  {
    slug: "ecommerce-shopify",
    title: "Shopify Development",
    shortTitle: "Shopify Development",
    icon: "ecommerce",
    h1: "Shopify Development Company Building High-Converting Stores",
    tagline:
      "Custom Shopify themes, app integrations, migrations and Shopify Plus builds — launched fast and tuned for conversion.",
    summary:
      "Custom Shopify themes, store migrations, app integrations and Shopify Plus builds with payments, shipping and analytics fully wired.",
    metaTitle: "Shopify Development Company | Custom Shopify Stores",
    metaDescription:
      "Shopify development services: custom themes, Shopify Plus builds, headless storefronts, app integrations, payments, shipping and conversion optimisation.",
    primaryKeyword: "Shopify development company",
    keywords: [
      "Shopify development company",
      "Shopify store development",
      "custom Shopify theme development",
      "Shopify Plus developers",
      "Shopify migration services",
    ],
    image: media.storeCheckout,
    imageAlt: "Premium store checkout counter with a digital payment terminal, representing a Shopify storefront",
    overview: [
      "Online stores lose most of their revenue between the product page and the payment confirmation. WordBitX builds eCommerce experiences that fix that stretch: fast product listings, honest stock and delivery information, and a checkout with as little friction as the platform allows.",
      "We work in both directions — Shopify when speed to market and operational simplicity matter, and custom or headless commerce when catalogue rules, B2B pricing or marketplace logic outgrow a hosted platform.",
    ],
    whoNeeds: [
      "Retailers moving from social selling to a real storefront",
      "Shopify merchants whose theme is slow or hard to extend",
      "Brands needing B2B pricing, wholesale portals or bulk ordering",
      "Businesses selling on marketplaces that need inventory sync",
      "Stores with traffic but a high cart abandonment rate",
    ],
    problems: [
      { title: "Abandoned carts", text: "Forced accounts, hidden shipping costs and slow checkouts kill orders. We simplify and clarify every step." },
      { title: "Products nobody can find", text: "Weak search, thin filters and poor category structure hide inventory. We fix discovery and internal linking." },
      { title: "Stock and order chaos", text: "Manual updates across channels cause oversells. We sync inventory with your POS, ERP or marketplace feeds." },
    ],
    benefits: [
      { title: "Faster storefronts", text: "Optimised images, lean apps and caching improve mobile speed where most shopping happens." },
      { title: "Better product discovery", text: "Structured collections, filters and search that surface the right item quickly." },
      { title: "Higher average order value", text: "Bundles, upsells and post-purchase offers implemented properly, not bolted on." },
      { title: "Commerce SEO", text: "Product schema, canonical rules for variants and clean pagination for large catalogues." },
    ],
    offerings: [
      { title: "Shopify development", text: "Custom themes, app integrations, migrations and Shopify Plus builds." },
      { title: "Custom storefronts", text: "Headless commerce with Next.js for brands needing full control." },
      { title: "WooCommerce stores", text: "WordPress-based commerce for content-driven brands." },
      { title: "Payments & logistics", text: "Local and international gateways, shipping rates, tax rules and courier APIs." },
    ],
    deliverables: [
      "Conversion-focused storefront design system",
      "Product, collection, cart and checkout implementation",
      "Payment gateway and shipping integrations",
      "Inventory sync with POS or ERP where required",
      "Enhanced eCommerce analytics and event tracking",
      "Merchant training for catalogue and content updates",
    ],
    process: [
      { step: "01", title: "Commerce audit", text: "Catalogue structure, margins, funnel data and platform recommendation." },
      { step: "02", title: "UX & merchandising", text: "Category architecture, product templates and checkout flow design." },
      { step: "03", title: "Store build", text: "Theme or headless development, app selection and integrations." },
      { step: "04", title: "Data & testing", text: "Product import, tax and shipping tests, and end-to-end order QA." },
      { step: "05", title: "Launch & optimise", text: "Go-live, funnel monitoring and iterative CRO improvements." },
    ],
    techStack: ["Shopify", "Next.js", "WooCommerce", "WordPress", "Stripe", "Node.js", "PostgreSQL", "Google Analytics"],
    whyUs: [
      { title: "Revenue-first decisions", text: "Every feature is judged against conversion, AOV or operational cost." },
      { title: "Platform honesty", text: "We recommend Shopify when it is the right answer, even on a custom-build enquiry." },
      { title: "Operations included", text: "Stock, fulfilment and returns flows are designed with your team, not ignored." },
      { title: "Measurable tracking", text: "Clean analytics so marketing spend can be judged on real order data." },
    ],
    faqs: [
      { question: "Shopify or a custom store?", answer: "Shopify wins for speed, reliability and simple operations. Custom or headless wins when you need unusual pricing logic, deep integrations, or a content-heavy brand experience. We assess catalogue and workflow before recommending." },
      { question: "Can you migrate our existing store?", answer: "Yes. We migrate products, customers and orders, preserve URLs with redirects, and validate SEO after launch to protect existing rankings." },
      { question: "Do you support us after launch?", answer: "Yes — monthly support covers updates, seasonal campaigns, new features and conversion improvements." },
    ],
    related: ["woocommerce-development", "google-merchant-center", "seo-services", "amazon-store-setup"],
    relatedPosts: ["shopify-vs-custom-ecommerce-website", "seo-guide-for-businesses"],
    projectCategory: "E-Commerce",
    featured: true,
  },
  {
    slug: "pos-software",
    title: "POS Software Development",
    shortTitle: "POS Software",
    icon: "pos",
    h1: "Custom POS Software Development for Retail & Restaurants",
    tagline:
      "Point of sale systems that keep selling when the internet drops — with inventory, staff control and real reporting.",
    summary:
      "Custom point of sale software for retail chains, restaurants and service counters, with offline billing and live stock control.",
    metaTitle: "POS Software Development | Retail & Restaurant Systems",
    metaDescription:
      "Custom POS software development by WordbitX: offline billing, inventory control, multi-branch reporting and integrations for retail and restaurants.",
    primaryKeyword: "POS software development",
    keywords: [
      "POS software development",
      "custom POS software",
      "point of sale system development",
      "retail POS software",
      "restaurant POS system",
    ],
    image: media.posTerminal,
    imageAlt: "Point of sale terminal processing a card payment with mobile app",
    overview: [
      "A point of sale system is the one piece of software that cannot fail during business hours. WordBitX builds POS software that keeps billing when connectivity drops, syncs the moment it returns, and gives owners accurate numbers across every branch.",
      "We build for the counter first — large touch targets, keyboard and barcode support, fast search, and a two-tap checkout — then layer on inventory, purchasing, staff permissions and reporting behind it.",
    ],
    whoNeeds: [
      "Retail shops and multi-branch chains",
      "Restaurants, cafés and cloud kitchens needing KOT and table flows",
      "Pharmacies and grocery stores managing batches and expiry",
      "Service counters requiring invoices and tax compliance",
      "Businesses whose current POS lacks reporting or integrations",
    ],
    problems: [
      { title: "Billing stops when internet drops", text: "Cloud-only systems freeze the counter. Our POS runs offline and syncs automatically on reconnect." },
      { title: "Stock never matches reality", text: "Manual adjustments and untracked wastage break inventory. We tie every sale, return and transfer to stock movements." },
      { title: "No visibility across branches", text: "Owners wait for end-of-day WhatsApp updates. Consolidated dashboards show live sales by branch, staff and product." },
    ],
    benefits: [
      { title: "Offline-first billing", text: "Local storage with conflict-safe sync keeps the counter running." },
      { title: "Accurate inventory", text: "Real-time stock, low-stock alerts, purchase orders and supplier records." },
      { title: "Staff accountability", text: "Role-based access, shift reports, discount limits and void tracking." },
      { title: "Owner-level insight", text: "Profitability by product, category, branch and hour of day." },
    ],
    offerings: [
      { title: "Retail POS", text: "Barcode billing, variants, batches, discounts, loyalty and returns." },
      { title: "Restaurant POS", text: "Table management, kitchen order tickets, modifiers and split billing." },
      { title: "Inventory & purchasing", text: "Stock transfers, supplier ledgers, purchase orders and stock takes." },
      { title: "Hardware integration", text: "Receipt printers, barcode scanners, cash drawers and card terminals." },
    ],
    deliverables: [
      "Touch-optimised POS application for counter hardware",
      "Offline data layer with automatic synchronisation",
      "Inventory, purchasing and supplier modules",
      "Multi-branch admin dashboard and reporting",
      "Tax-compliant invoice templates",
      "On-site or remote staff training",
    ],
    process: [
      { step: "01", title: "Counter study", text: "Observe live billing to map speed requirements and edge cases." },
      { step: "02", title: "Module planning", text: "Define POS, inventory, reporting and permission structures." },
      { step: "03", title: "Build & hardware test", text: "Development with real printers, scanners and drawers in the loop." },
      { step: "04", title: "Pilot branch", text: "Run one location in parallel with the old system to prove stability." },
      { step: "05", title: "Rollout & support", text: "Branch-by-branch deployment with training and priority support." },
    ],
    techStack: ["React", "TypeScript", "Node.js", "PostgreSQL", "Flutter", "Docker", "AWS", "Redis"],
    whyUs: [
      { title: "Built for the counter", text: "Speed at checkout drives every interface decision." },
      { title: "Offline is standard", text: "Not an upsell — resilience is part of the core architecture." },
      { title: "Real hardware testing", text: "We validate on the printers and scanners you actually own." },
      { title: "Priority support", text: "POS issues are business-critical, and our support plans reflect that." },
    ],
    faqs: [
      { question: "Can it work without internet?", answer: "Yes. Billing, printing and stock deduction continue offline. Data syncs automatically when the connection returns, with conflict handling for multi-terminal setups." },
      { question: "Will it work with our existing hardware?", answer: "In most cases yes — standard ESC/POS printers, USB and Bluetooth scanners, and common cash drawers are supported. We confirm compatibility during discovery." },
      { question: "Can it integrate with our online store?", answer: "Yes. We sync products, stock and orders with Shopify, WooCommerce or a custom storefront so online and in-store inventory stay aligned." },
    ],
    related: ["inventory-management-software", "custom-software-development", "crm-erp-solutions", "ecommerce-shopify"],
    relatedPosts: ["inventory-management-software-guide", "crm-vs-erp-which-one-does-your-business-need"],
    projectCategory: "Software",
  },
  {
    slug: "ui-ux-design",
    title: "UI/UX & Graphic Design",
    shortTitle: "UI/UX & Design",
    icon: "design",
    h1: "UI/UX Design Services That Make Products Easy to Use",
    tagline:
      "Research-led interface design, design systems and brand visuals that make complex products feel simple.",
    summary:
      "User research, wireframes, high-fidelity UI, design systems and brand collateral for web, mobile and software products.",
    metaTitle: "UI UX Design Services | Product & Web Design Agency",
    metaDescription:
      "UI/UX design services from WordBitX: user research, wireframing, prototyping, design systems and graphic design for websites, mobile apps and business software.",
    primaryKeyword: "UI UX design services",
    keywords: [
      "UI UX design services",
      "product design agency",
      "web design services",
      "mobile app UI design",
      "design system development",
    ],
    image: media.professionals,
    imageAlt: "Designers reviewing interface wireframes and prototypes on screen",
    overview: [
      "Design decides whether people finish what they started on your product. WordBitX approaches design as problem solving: understand the user's goal, remove the steps that do not serve it, and make the remaining path obvious.",
      "Every project ends with a design system — tokens, components, states and usage rules — so engineering builds faster and future screens stay consistent instead of drifting.",
    ],
    whoNeeds: [
      "Products with high drop-off in signup, checkout or onboarding",
      "Teams whose interface has grown inconsistent over time",
      "Startups needing an investor-ready prototype",
      "Businesses with functional but visually dated software",
      "Companies refreshing brand identity across digital touchpoints",
    ],
    problems: [
      { title: "Users cannot complete tasks", text: "Unclear labels and hidden actions cause abandonment. Usability testing exposes exactly where people stall." },
      { title: "Inconsistent interfaces", text: "Every screen looking different erodes trust and slows development. A design system fixes it at the source." },
      { title: "Designs that cannot be built", text: "Pretty files that ignore technical constraints get rebuilt badly. Our designers work alongside engineers." },
    ],
    benefits: [
      { title: "Higher completion rates", text: "Simplified flows increase signups, checkouts and form submissions." },
      { title: "Faster development", text: "Reusable components and documented states reduce build and QA time." },
      { title: "Accessible by default", text: "Colour contrast, focus states and keyboard navigation included, not optional." },
      { title: "Consistent brand", text: "One visual language across website, app, dashboard and marketing assets." },
    ],
    offerings: [
      { title: "UX research & audits", text: "Heuristic reviews, journey maps, analytics analysis and usability testing." },
      { title: "UI design", text: "High-fidelity screens for web, mobile and dashboards with full responsive states." },
      { title: "Design systems", text: "Figma libraries with tokens, components and documentation." },
      { title: "Graphic design", text: "Logos, brand guidelines, pitch decks, social kits and marketing collateral." },
    ],
    deliverables: [
      "UX audit report with prioritised recommendations",
      "Wireframes for every key screen",
      "High-fidelity UI in light and dark variants where required",
      "Interactive prototype for testing and stakeholder review",
      "Figma design system with components and tokens",
      "Developer handoff specs and exported assets",
    ],
    process: [
      { step: "01", title: "Research", text: "Users, competitors, analytics and business constraints." },
      { step: "02", title: "Structure", text: "Information architecture, user flows and low-fidelity wireframes." },
      { step: "03", title: "Visual design", text: "Brand-aligned UI, states, motion notes and responsive layouts." },
      { step: "04", title: "Prototype & test", text: "Clickable prototype validated with real users, then refined." },
      { step: "05", title: "Handoff", text: "System documentation and active support during development." },
    ],
    techStack: ["Figma", "React", "Next.js", "Tailwind CSS", "Flutter", "TypeScript"],
    whyUs: [
      { title: "Design tied to outcomes", text: "We measure success by task completion, not by how the mockup looks in a slide." },
      { title: "Engineering-aware", text: "Designs are reviewed for feasibility before they reach development." },
      { title: "Systems over screens", text: "You get a reusable library, not a folder of one-off artboards." },
      { title: "Accessibility included", text: "WCAG-aligned contrast, sizing and focus behaviour as standard." },
    ],
    faqs: [
      { question: "Can you design without building?", answer: "Yes. Design-only engagements are common — you receive Figma files, a documented design system and developer handoff specs your in-house team can implement." },
      { question: "Do you redesign existing products?", answer: "Yes. We start with a UX audit and analytics review, then redesign in phases so users are not disrupted by a sudden change." },
      { question: "How many revision rounds are included?", answer: "Two structured rounds per milestone are standard. Feedback is collected in one place so decisions stay clear and timelines hold." },
    ],
    related: ["graphic-design", "logo-brand-identity", "web-development", "flutter-app-development"],
    relatedPosts: ["how-to-choose-a-web-development-company", "mobile-app-development-guide"],
    projectCategory: "Design",
    featured: true,
  },
];
