import type { Service } from "@/lib/types";
import { media } from "@/lib/media";
import { withServiceDefaults } from "@/lib/service-builder";

export const servicesE: Service[] = [
  withServiceDefaults({
    slug: "custom-web-application-development",
    title: "Custom Web Application Development",
    shortTitle: "Web Applications",
    icon: "web",
    h1: "Custom Web Application Development for Dashboards, Portals and Workflows",
    tagline:
      "Role-based web apps — admin panels, client portals, booking engines and internal tools — built around your process, not a generic SaaS seat.",
    summary:
      "Bespoke web applications with authentication, permissions, reporting and integrations, engineered in Next.js, React and Node.js.",
    metaTitle: "Custom Web Application Development Company",
    metaDescription:
      "WordbitX builds custom web applications: client portals, dashboards, booking systems and internal tools with secure login, roles and API integrations.",
    primaryKeyword: "custom web application development",
    keywords: [
      "custom web application development",
      "web application development company",
      "custom web app development",
      "business web application development",
      "portal development company Pakistan",
    ],
    image: media.htmlEditor,
    imageAlt: "Developer building a custom web application dashboard in a code editor",
    overview: [
      "A marketing website is not a web application. WordbitX builds authenticated products: client portals, operations dashboards, booking engines, vendor consoles and internal tools where users log in, complete work and leave an audit trail.",
      "We start from the workflow, not the screen. Roles, permissions, data models and integrations are designed first so the interface stays simple. The stack is usually Next.js or React on the front and Node.js or Laravel on the API, with PostgreSQL when the data must stay consistent.",
    ],
    whoNeeds: [
      "Businesses replacing spreadsheets and WhatsApp with a real workflow",
      "Companies that need a client or vendor portal next to the public website",
      "Teams paying for five SaaS tools that still do not talk to each other",
      "Startups validating a SaaS idea before a full multi-tenant build",
    ],
    problems: [
      { title: "SaaS that almost fits", text: "Off-the-shelf tools force workarounds. A custom web app encodes your actual process and reporting." },
      { title: "No single source of truth", text: "Orders, tickets or students live in three places. We centralise records and expose only the fields each role needs." },
      { title: "Security as an afterthought", text: "Shared passwords and open admin URLs are common. We ship token auth, role checks and activity logs from day one." },
    ],
    benefits: [
      { title: "Faster operations", text: "Repeat tasks become screens and automations instead of email chains." },
      { title: "Clear permissions", text: "Staff, clients and vendors see only their own data." },
      { title: "Integrations you control", text: "Payments, SMS, accounting or CRM connected through documented APIs." },
      { title: "Code you own", text: "No per-seat lock-in. You keep the repository, hosting and data." },
    ],
    offerings: [
      { title: "Client & vendor portals", text: "Self-service access for documents, orders, tickets or project status." },
      { title: "Admin dashboards", text: "Role-based consoles with filters, exports and audit history." },
      { title: "Booking & workflow engines", text: "Calendars, queues, approvals and status pipelines." },
      { title: "API-backed products", text: "A web app plus a documented API for mobile or partner access." },
    ],
    deliverables: [
      "Information architecture and role matrix",
      "Authenticated web application on staging and production",
      "Database schema, backups and environment config",
      "Admin documentation and editor or operator training",
      "Source code under your Git ownership",
    ],
    techStack: ["Next.js", "React", "TypeScript", "Node.js", "Laravel", "PostgreSQL", "Tailwind CSS", "Cloudflare"],
    faqs: [
      { question: "How is this different from website development?", answer: "A website is mostly public pages. A web application has login, roles, data writes and often payments or notifications. We quote them as different products because the engineering is different." },
      { question: "Can you extend an existing app?", answer: "Yes, if the codebase is maintainable. We start with a short technical review and tell you whether to extend or rebuild." },
      { question: "Do you include hosting?", answer: "We can deploy to Vercel, a VPS or your cloud account. Hosting stays billed to you so you keep control if we later pause the retainer." },
    ],
    related: ["web-development", "saas-application-development", "api-development", "custom-software-development"],
    relatedPosts: ["how-to-choose-a-web-development-company", "custom-software-vs-ready-made-software"],
    projectCategory: "Websites",
  }),
  withServiceDefaults({
    slug: "woocommerce-development",
    title: "WooCommerce Store Development",
    shortTitle: "WooCommerce",
    icon: "ecommerce",
    h1: "WooCommerce Store Development for WordPress Commerce",
    tagline:
      "Custom WooCommerce stores with product types, payments, shipping and checkout that your team can actually run.",
    summary:
      "WooCommerce store setup, theme customisation, payment gateways and performance work for WordPress-based commerce.",
    metaTitle: "WooCommerce Development Company | Custom WooCommerce Stores",
    metaDescription:
      "WooCommerce store development from WordbitX: custom product types, checkout, payment gateways, shipping rules and WooCommerce optimisation in Pakistan.",
    primaryKeyword: "WooCommerce development",
    keywords: [
      "WooCommerce development",
      "WooCommerce store development",
      "WooCommerce developer Pakistan",
      "WordPress WooCommerce development",
      "WooCommerce website development",
    ],
    image: media.ecommerceShopping,
    imageAlt: "Online shopping bags and a laptop showing an e-commerce storefront",
    overview: [
      "WooCommerce is the right store when you already live in WordPress or need product types a hosted platform fights. WordbitX builds stores that stay editable: products, variations, coupons and content in wp-admin, not buried in custom code.",
      "We keep the plugin list short. Payments, shipping and tax are configured properly; page speed is treated as a launch requirement, not a later project.",
    ],
    whoNeeds: [
      "Retailers who want a store inside an existing WordPress site",
      "Brands migrating from Shopify or a custom cart to WooCommerce",
      "Wholesalers needing B2B pricing, quotes or role-based catalogues",
      "Teams that must own hosting and data on their own server",
    ],
    problems: [
      { title: "Plugin pile-up", text: "Twenty overlapping extensions slow checkout. We replace them with fewer, well-chosen tools or custom code." },
      { title: "Abandoned carts", text: "Slow or confusing checkout loses paid traffic. We simplify steps and measure completion." },
      { title: "Fragile updates", text: "Theme hacks break on WordPress updates. We use a child theme or a custom block theme you can patch." },
    ],
    benefits: [
      { title: "You keep WordPress", text: "Blog, landing pages and shop share one CMS your team already knows." },
      { title: "Flexible catalogue", text: "Variable products, bundles, bookings or wholesale price lists." },
      { title: "Local payments", text: "Cards, wallets and cash-on-delivery options used in Pakistan and overseas." },
      { title: "SEO on the same site", text: "Category and product templates that search engines can crawl." },
    ],
    offerings: [
      { title: "New WooCommerce stores", text: "Theme, catalogue, payments, shipping and tax from a blank install." },
      { title: "Migrations", text: "Products, customers and SEO redirects from Shopify, Magento or spreadsheets." },
      { title: "Checkout customisation", text: "Fields, fees, multi-currency and gateway rules without breaking PCI scope." },
      { title: "Performance & security", text: "Caching, image work, malware hardening and backup routines." },
    ],
    deliverables: [
      "Configured WooCommerce store on staging and live",
      "Payment and shipping methods tested with real orders",
      "Editor guide for products, coupons and pages",
      "Backup and update routine documented",
    ],
    techStack: ["WordPress", "WooCommerce", "PHP", "MySQL", "JavaScript", "Cloudflare"],
    faqs: [
      { question: "Shopify or WooCommerce?", answer: "Shopify is faster to launch if you want hosted checkout and apps. WooCommerce is better if you need WordPress content, unusual product logic or full server control. We recommend based on catalogue and team, not preference." },
      { question: "Will the store stay fast?", answer: "Yes, if we control plugins and hosting. A cheap shared host plus ten sliders will undo the work. We specify hosting and a performance budget up front." },
    ],
    related: ["wordpress-development", "ecommerce-development", "ecommerce-shopify", "seo-services"],
    relatedPosts: ["shopify-vs-custom-ecommerce-website", "wordpress-vs-custom-website"],
    projectCategory: "E-Commerce",
  }),
  withServiceDefaults({
    slug: "custom-cms-development",
    title: "Custom CMS Development",
    shortTitle: "Custom CMS",
    icon: "software",
    h1: "Custom CMS Development So Your Team Can Publish Without Developers",
    tagline:
      "A content system modelled on your pages — not a generic blog admin your editors have to fight.",
    summary:
      "Headless and traditional CMS builds with structured fields, roles, preview and multi-language publishing.",
    metaTitle: "Custom CMS Development Company | Headless CMS",
    metaDescription:
      "Custom CMS development from WordbitX: structured content models, headless CMS, editor roles, preview and multi-language publishing for your teams.",
    primaryKeyword: "custom CMS development",
    keywords: [
      "custom CMS development",
      "headless CMS development",
      "custom content management system",
      "CMS development company",
      "headless CMS Pakistan",
    ],
    image: media.focusedDeveloper,
    imageAlt: "Editor working on structured website content in a custom CMS",
    overview: [
      "Most businesses do not need another WordPress install. They need fields that match their pages: services, locations, case studies, FAQs and landing blocks that cannot be accidentally broken.",
      "WordbitX designs the content model first, then connects WordPress, a headless CMS or a small custom admin. Editors get preview, roles and a publish flow. Developers keep components versioned in git.",
    ],
    whoNeeds: [
      "Marketing teams waiting on developers for every copy change",
      "Multi-location or multi-language brands",
      "Product companies publishing docs, changelogs or help centres",
      "Sites that outgrew a theme’s page builder",
    ],
    problems: [
      { title: "Page builders everywhere", text: "Unstructured blocks create layout debt. Structured fields keep design consistent." },
      { title: "No preview", text: "Editors publish blind. We add draft preview on production-like URLs." },
      { title: "Mixed ownership", text: "Content and code fight. We separate them so deploys and edits do not collide." },
    ],
    benefits: [
      { title: "Faster publishing", text: "New pages reuse templates instead of new development tickets." },
      { title: "Safer edits", text: "Required fields and validation stop empty or broken pages." },
      { title: "Better SEO control", text: "Title, description, OG and schema fields live next to the content." },
      { title: "Multi-language ready", text: "Locales and fallbacks designed before you need the second language." },
    ],
    offerings: [
      { title: "Content modelling", text: "Types, relationships and editor UX mapped to your sitemap." },
      { title: "Headless CMS", text: "API-driven content for Next.js and mobile clients." },
      { title: "WordPress custom admin", text: "ACF or custom post types when WordPress is the right home." },
      { title: "Migration", text: "Move posts and media from a legacy CMS with URL mapping." },
    ],
    deliverables: [
      "Content model document and editor training",
      "CMS project under your account",
      "Preview and role configuration",
      "Frontend templates bound to the model",
    ],
    techStack: ["Next.js", "WordPress", "TypeScript", "PostgreSQL", "Node.js"],
    faqs: [
      { question: "Is WordPress a custom CMS?", answer: "WordPress can be, if we lock it to structured types. A page-builder free-for-all is not. We will tell you which path is cheaper for your team." },
      { question: "Can non-technical staff use it?", answer: "That is the point. We train editors on the fields they will actually touch and hide everything else." },
    ],
    related: ["web-development", "wordpress-development", "custom-web-application-development", "seo-services"],
    relatedPosts: ["wordpress-vs-custom-website", "website-development-cost-pakistan"],
    projectCategory: "Websites",
  }),
  withServiceDefaults({
    slug: "flutter-app-development",
    title: "Flutter App Development",
    shortTitle: "Flutter Apps",
    icon: "mobile",
    h1: "Flutter App Development Company for Android and iOS from One Codebase",
    tagline:
      "One Flutter codebase, two store listings — faster delivery without a cheap-looking hybrid UI.",
    summary:
      "Custom Flutter apps with Dart, Firebase or a custom API, published to Google Play and the App Store.",
    metaTitle: "Flutter App Development Company | Android & iOS",
    metaDescription:
      "Flutter app development from WordbitX: custom Android and iOS apps from one Dart codebase, with Firebase, APIs, store publishing and maintenance.",
    primaryKeyword: "Flutter app development",
    keywords: [
      "Flutter app development",
      "Flutter app development company",
      "Flutter developers Pakistan",
      "Flutter mobile app development",
      "hire Flutter developers",
    ],
    image: media.flutterCoding,
    imageAlt: "Developer writing Flutter Dart code for a mobile application",
    overview: [
      "Flutter is how most of our clients ship Android and iOS without paying for two native teams. WordbitX designs platform-aware UI — navigation, typography and gestures that feel native — while sharing business logic in Dart.",
      "We use Flutter when the product is a business or consumer app, not a 3D game. Hardware-heavy or OS-preview features still get a native module when needed.",
    ],
    whoNeeds: [
      "Startups that need both stores from one budget",
      "Businesses replacing a slow React Native or WebView app",
      "Teams with an existing Flutter app that has no owner",
      "Products that must look polished on Android and iPhone",
    ],
    problems: [
      { title: "Two apps, two bugs", text: "Native twins drift. Flutter keeps features and fixes in one place." },
      { title: "Generic Material-only UI", text: "We adapt Cupertino patterns on iOS so the app does not look ported." },
      { title: "Store rejection", text: "Permissions, privacy nutrition and payment rules are handled before submission." },
    ],
    benefits: [
      { title: "Faster first release", text: "One team, one sprint board, two binaries." },
      { title: "Consistent features", text: "Parity by default instead of iOS lagging Android by a quarter." },
      { title: "Lower maintenance", text: "OS updates are patched once, then released to both stores." },
      { title: "Hot reload during build", text: "You see UI changes in the weekly review, not at the end." },
    ],
    offerings: [
      { title: "New Flutter products", text: "MVP to store-ready apps with auth, payments and notifications." },
      { title: "Flutter takeovers", text: "Stabilise an inherited repo, then add features." },
      { title: "Backend pairing", text: "Firebase or a custom Node/Laravel API." },
      { title: "Store launch", text: "Listings, screenshots and review responses." },
    ],
    deliverables: [
      "Flutter source under your Git account",
      "Android App Bundle and iOS IPA pipelines",
      "Crash and analytics wiring",
      "Store listing pack",
    ],
    techStack: ["Flutter", "Dart", "Firebase", "Node.js", "PostgreSQL", "Kotlin", "Swift"],
    faqs: [
      { question: "Is Flutter good enough versus native?", answer: "For most business apps, yes. Choose native if you need the newest platform APIs immediately, heavy graphics, or unusual background work. We will say so in discovery." },
      { question: "Can you publish for us?", answer: "Yes, under your Play Console and App Store Connect accounts." },
    ],
    related: ["mobile-app-development", "android-app-development", "ios-app-development", "firebase-integration"],
    relatedPosts: ["flutter-app-development-benefits", "mobile-app-development-guide"],
    projectCategory: "Mobile Apps",
  }),
  withServiceDefaults({
    slug: "enterprise-software-solutions",
    title: "Enterprise Software Solutions",
    shortTitle: "Enterprise Software",
    icon: "software",
    h1: "Enterprise Software Solutions for Multi-Team Operations",
    tagline:
      "Internal platforms that connect departments — approvals, reporting, access control and integrations — without buying another bloated suite.",
    summary:
      "Enterprise-grade internal software: SSO, roles, audit logs, integrations and reporting built for growing organisations.",
    metaTitle: "Enterprise Software Solutions | Custom Business Platforms",
    metaDescription:
      "Enterprise software solutions from WordbitX: custom internal platforms with SSO, roles, audit logs, ERP/CRM integrations and reporting for multi-team companies.",
    primaryKeyword: "enterprise software solutions",
    keywords: [
      "enterprise software solutions",
      "enterprise software development",
      "custom enterprise software",
      "enterprise application development",
      "business software solutions Pakistan",
    ],
    image: media.businessAnalyticsTeam,
    imageAlt: "Operations team reviewing enterprise software dashboards in a meeting",
    overview: [
      "Enterprise here means multiple teams, multiple roles and data that cannot disappear. WordbitX builds internal platforms that sit beside or replace parts of an ERP — not a 200-module product you will never finish implementing.",
      "We design access, audit and integration first. Finance, operations and field teams get different screens over the same records.",
    ],
    whoNeeds: [
      "Companies outgrowing spreadsheets and email approvals",
      "Groups with several branches that need one operations view",
      "IT teams that need SSO and an audit trail for compliance",
      "Businesses integrating a legacy ERP with newer tools",
    ],
    problems: [
      { title: "Shadow IT", text: "Every department invents a sheet. A shared platform with roles stops that quietly." },
      { title: "No audit trail", text: "Nobody can say who changed a price or approved a discount. We log it." },
      { title: "Integration spaghetti", text: "We replace brittle exports with scheduled APIs and error queues." },
    ],
    benefits: [
      { title: "One operations picture", text: "Managers see status without chasing three teams." },
      { title: "Controlled access", text: "SSO and least-privilege roles instead of shared passwords." },
      { title: "Fits your process", text: "We encode how you already work, then improve it." },
      { title: "Phased delivery", text: "Launch one department, then expand — not a two-year big bang." },
    ],
    offerings: [
      { title: "Internal platforms", text: "Approvals, cases, inventory views and branch reporting." },
      { title: "SSO & identity", text: "Google, Microsoft or custom identity wired to roles." },
      { title: "ERP / CRM connectors", text: "Read/write sync with the systems you already pay for." },
      { title: "Management reporting", text: "Saved reports and exports finance will actually use." },
    ],
    deliverables: [
      "Role and data-access matrix",
      "Production platform with staging parity",
      "Integration runbooks",
      "Admin training for IT and operations owners",
    ],
    techStack: ["Next.js", "Node.js", "PostgreSQL", "Laravel", "TypeScript", "Cloudflare"],
    faqs: [
      { question: "Is this an ERP replacement?", answer: "Sometimes a module is. We do not pretend to replace SAP in six weeks. We replace the painful gap — then decide if more modules are worth it." },
      { question: "Can you work with our IT policy?", answer: "Yes. Hosting, VPN and identity stay inside your rules. We deploy to your cloud if required." },
    ],
    related: ["custom-software-development", "crm-erp-solutions", "saas-application-development", "api-development"],
    relatedPosts: ["custom-software-vs-ready-made-software", "crm-vs-erp-which-one-does-your-business-need"],
    projectCategory: "Software",
  }),
  withServiceDefaults({
    slug: "saas-application-development",
    title: "SaaS Application Development",
    shortTitle: "SaaS Development",
    icon: "software",
    h1: "SaaS Application Development from MVP to Multi-Tenant Product",
    tagline:
      "Multi-tenant SaaS with billing, roles, onboarding and admin — built so you can sell subscriptions, not just a custom project.",
    summary:
      "SaaS product engineering: tenancy, subscriptions, trials, admin, APIs and the first paying-customer launch.",
    metaTitle: "SaaS Application Development Company | Multi-Tenant SaaS",
    metaDescription:
      "SaaS application development from WordbitX: multi-tenant products with billing, roles, onboarding, APIs and admin — from MVP to subscription launch.",
    primaryKeyword: "SaaS application development",
    keywords: [
      "SaaS application development",
      "SaaS development company",
      "multi-tenant SaaS development",
      "SaaS product development",
      "build a SaaS application",
    ],
    image: media.marketDashboard,
    imageAlt: "SaaS analytics dashboard showing subscription and usage metrics",
    overview: [
      "A custom app for one company is not SaaS. WordbitX builds products where many customers share an app safely: tenant isolation, plans, trials, billing and an operator admin.",
      "We keep release one small enough to sell. Usage metering, SSO and marketplaces come when the first customers prove the workflow.",
    ],
    whoNeeds: [
      "Founders validating a subscription product",
      "Agencies turning a client build into a product",
      "Companies replacing services revenue with software revenue",
      "Teams with an MVP that cannot onboard a second customer cleanly",
    ],
    problems: [
      { title: "One-tenant thinking", text: "Hard-coded client data blocks the second sale. We design tenancy first." },
      { title: "Billing bolted on later", text: "Trials, invoices and dunning are planned with Stripe or your processor from the start." },
      { title: "No operator tools", text: "You cannot impersonate, refund or disable a tenant. We ship an admin for that." },
    ],
    benefits: [
      { title: "Sell more than once", text: "Onboarding and plans are productised, not a new project each time." },
      { title: "Safer data", text: "Tenant isolation and backups you can explain to a buyer." },
      { title: "Room to price", text: "Feature flags and plan limits without rewriting the app." },
      { title: "API for partners", text: "A public or partner API when you are ready to integrate." },
    ],
    offerings: [
      { title: "SaaS MVPs", text: "The smallest product that can take a paid tenant live." },
      { title: "Multi-tenant rebuilds", text: "Extract a single-client app into a real product." },
      { title: "Billing & trials", text: "Plans, coupons, taxes and customer portal." },
      { title: "Admin & observability", text: "Tenant support tools, logs and basic usage metrics." },
    ],
    deliverables: [
      "Tenancy and plan design",
      "Production SaaS with staging",
      "Billing test mode then live",
      "Operator runbook",
    ],
    techStack: ["Next.js", "TypeScript", "Node.js", "PostgreSQL", "Stripe", "Cloudflare"],
    faqs: [
      { question: "How long is a SaaS MVP?", answer: "A focused workflow with auth, one core job and billing usually takes 8–16 weeks after discovery. Marketplaces and marketplaces-with-payouts take longer." },
      { question: "Do you take equity?", answer: "No. This is a delivery engagement. You own the product." },
    ],
    related: ["custom-web-application-development", "api-development", "custom-software-development", "ui-ux-design"],
    relatedPosts: ["custom-software-vs-ready-made-software", "how-ai-automation-helps-businesses"],
    projectCategory: "Software",
  }),
  withServiceDefaults({
    slug: "api-development",
    title: "API Development & Integration",
    shortTitle: "API Development",
    icon: "devops",
    h1: "API Development and Integration for Web, Mobile and Partners",
    tagline:
      "Documented REST or GraphQL APIs, webhooks and third-party integrations that do not break the first time a vendor changes a field.",
    summary:
      "Custom API design, authentication, webhooks and integrations with payments, CRMs, ERPs, shipping and internal systems.",
    metaTitle: "API Development & Integration Services | REST & GraphQL",
    metaDescription:
      "API development and integration from WordbitX: REST and GraphQL APIs, webhooks, auth and connections to payments, CRM, ERP, shipping and internal software.",
    primaryKeyword: "API development and integration",
    keywords: [
      "API development",
      "API integration services",
      "REST API development",
      "GraphQL API development",
      "third party API integration",
    ],
    image: media.codeReview,
    imageAlt: "Engineers reviewing API endpoints and integration code",
    overview: [
      "If the mobile app, website and warehouse each invent their own data, you will spend the next year reconciling it. WordbitX designs one API (or a small set) with auth, versioning and errors that clients can handle.",
      "Integrations are treated as products: retries, logging and a way to replay a failed webhook. We do not leave a Zapier zap as the only production path unless that is explicitly the budget.",
    ],
    whoNeeds: [
      "Teams launching a mobile app against a new or existing backend",
      "Businesses connecting Shopify, a POS or an ERP to a custom system",
      "SaaS products opening a partner API",
      "Companies drowning in manual CSV uploads",
    ],
    problems: [
      { title: "Undocumented endpoints", text: "New developers guess. We ship OpenAPI or equivalent docs with examples." },
      { title: "Silent failures", text: "A payment webhook dies and nobody knows. We alert and store payloads." },
      { title: "Vendor lock-in", text: "We wrap third parties so you can change a gateway without rewriting the app." },
    ],
    benefits: [
      { title: "One contract", text: "Web, mobile and partners share the same API rules." },
      { title: "Safer deploys", text: "Versioning and staging stop breaking production clients." },
      { title: "Faster features", text: "New screens reuse endpoints instead of new backends." },
      { title: "Auditability", text: "Request logs when finance or support needs to see what happened." },
    ],
    offerings: [
      { title: "Greenfield APIs", text: "Auth, resources, pagination and webhooks from scratch." },
      { title: "System integration", text: "Payments, SMS, shipping, CRM, accounting and marketplaces." },
      { title: "API takeovers", text: "Document and harden an inherited backend." },
      { title: "Partner APIs", text: "Keys, rate limits and a developer-facing guide." },
    ],
    deliverables: [
      "API specification and postman or equivalent collection",
      "Authenticated staging and production environments",
      "Webhook retry and logging",
      "Integration runbook",
    ],
    techStack: ["Node.js", "TypeScript", "PostgreSQL", "Laravel", "GraphQL", "Firebase"],
    faqs: [
      { question: "REST or GraphQL?", answer: "REST for most business APIs. GraphQL when many clients need different shapes of the same graph. We pick in discovery, not by fashion." },
      { question: "Can you integrate a closed legacy system?", answer: "Often yes, via database views, SFTP or a vendor’s limited API. We say if it is unsafe or more expensive than replacing the module." },
    ],
    related: ["custom-software-development", "saas-application-development", "custom-web-application-development", "mobile-app-development"],
    relatedPosts: ["custom-software-vs-ready-made-software", "mobile-app-development-guide"],
    projectCategory: "Software",
  }),
  withServiceDefaults({
    slug: "graphic-design",
    title: "Graphic Design",
    shortTitle: "Graphic Design",
    icon: "design",
    h1: "Graphic Design Services for Brands, Campaigns and Product UI",
    tagline:
      "Campaign creatives, social sets, ads and print-ready artwork that match the product — not a one-off Canva file nobody can reuse.",
    summary:
      "Graphic design for digital ads, social, presentations, packaging-adjacent artwork and marketing sites.",
    metaTitle: "Graphic Design Services | Brand & Campaign Design",
    metaDescription:
      "Graphic design services from WordbitX: social creatives, ad sets, presentations and brand-consistent campaign design for web and mobile products.",
    primaryKeyword: "graphic design services",
    keywords: [
      "graphic design services",
      "graphic design company",
      "social media graphic design",
      "ad creative design",
      "graphic designer Pakistan",
    ],
    image: media.studioShooting,
    imageAlt: "Designer reviewing brand artwork and campaign graphics",
    overview: [
      "Design that does not match the product wastes ad spend. WordbitX produces graphics from the same system as your UI and logo work: type, colour and spacing that still look like you when they leave Figma.",
      "We deliver source files and export sizes your ads and social tools actually need, plus a small usage guide so the next intern does not invent a new purple.",
    ],
    whoNeeds: [
      "Teams launching ads without on-brand creatives",
      "Companies whose social looks unrelated to the website",
      "Founders who need a pitch or sales deck that is not default slides",
      "Stores that need listing images beyond phone photos",
    ],
    problems: [
      { title: "Inconsistent brand", text: "Every freelancer starts over. We work from a kit or create one." },
      { title: "Wrong sizes", text: "Crops break on Stories vs feed. We export the set you will run." },
      { title: "Pretty but unclear", text: "The offer is the design. We write and layout for the click." },
    ],
    benefits: [
      { title: "Faster campaigns", text: "Reusable templates for the next promotion." },
      { title: "One visual language", text: "Ads, site and app feel like the same company." },
      { title: "Files you can edit", text: "Figma or layered sources, not flattened JPEGs only." },
      { title: "Production-aware", text: "Designed next to the developers who will implement the site." },
    ],
    offerings: [
      { title: "Social & ad creatives", text: "Static and simple motion sets for Meta, Google, TikTok and LinkedIn." },
      { title: "Pitch & sales decks", text: "Structured presentations for fundraising or B2B sales." },
      { title: "Listing & catalogue graphics", text: "Marketplace and product imagery layouts." },
      { title: "Campaign landing art", text: "Hero and section artwork for launch pages." },
    ],
    deliverables: [
      "Creative concepts and revised finals",
      "Export pack for the agreed channels",
      "Source files under your drive",
      "Short brand-usage notes",
    ],
    techStack: ["Figma", "Adobe Illustrator", "Adobe Photoshop"],
    faqs: [
      { question: "Do you also do UI/UX?", answer: "Yes, as a separate service. Graphic design here is campaign and brand artwork. Product screens live under UI/UX design." },
      { question: "Can you work from our existing brand?", answer: "Yes. Send the kit. If you do not have one, start with logo and brand identity, then this work." },
    ],
    related: ["logo-brand-identity", "ui-ux-design", "digital-marketing", "facebook-instagram-ads"],
    relatedPosts: ["digital-marketing-for-software-companies", "how-to-choose-a-web-development-company"],
    projectCategory: "Design",
  }),
  withServiceDefaults({
    slug: "logo-brand-identity",
    title: "Logo & Brand Identity Design",
    shortTitle: "Brand Identity",
    icon: "design",
    h1: "Logo and Brand Identity Design for Software and Service Companies",
    tagline:
      "A logo system, type, colour and usage rules you can hand to a developer or printer without starting over.",
    summary:
      "Logo design, brand kits and basic identity systems for startups and growing service businesses.",
    metaTitle: "Logo & Brand Identity Design | Brand Kit",
    metaDescription:
      "Logo and brand identity design from WordbitX: logo systems, colour, type, usage rules and a brand kit your website, app and ads can actually follow.",
    primaryKeyword: "logo and brand identity design",
    keywords: [
      "logo design",
      "brand identity design",
      "logo and brand identity",
      "brand kit design",
      "logo design company Pakistan",
    ],
    image: media.productPhotography,
    imageAlt: "Brand identity materials including logo mark and colour samples",
    overview: [
      "A logo file is not a brand. WordbitX delivers a small system: primary and compact marks, colour, type, spacing and do/don’t rules so the website, app icon and letterhead stay related.",
      "We design for screens first — favicon, app icon, nav bar — then provide print-safe exports if you need them. We do not sell 50 unused mockups.",
    ],
    whoNeeds: [
      "Founders launching without a usable mark",
      "Companies whose logo fails at 16 pixels or on a dark nav",
      "Teams merging two brands after a rename",
      "Businesses ready to stop using a marketplace icon",
    ],
    problems: [
      { title: "Looks cheap at small size", text: "We test favicon and app-icon crops before you fall in love with detail." },
      { title: "No rules", text: "Everyone picks a new font. A one-page kit stops that." },
      { title: "Wrong file types", text: "You get SVG, PNG and print-ready formats, not only a JPG." },
    ],
    benefits: [
      { title: "Works in product UI", text: "Designed next to the people who will put it in the header." },
      { title: "Faster later design", text: "Graphics and UI start from the same tokens." },
      { title: "Clear ownership", text: "You receive transferable source files." },
      { title: "Rename-safe process", text: "If WordbitX-style spelling matters, we lock it in the kit." },
    ],
    offerings: [
      { title: "Logo system", text: "Wordmark, icon and stacked lockups." },
      { title: "Colour & type", text: "Accessible pairs for web and print." },
      { title: "Basic brand kit", text: "Usage, clear space, incorrect use." },
      { title: "Application samples", text: "Website header, social avatar and one stationery item." },
    ],
    deliverables: [
      "Approved logo system",
      "Brand kit PDF or Figma",
      "SVG/PNG export pack",
      "Transfer of source files",
    ],
    techStack: ["Figma", "Adobe Illustrator"],
    faqs: [
      { question: "How many concepts?", answer: "Usually two or three distinct directions, then refinements on the one you pick. Unlimited random concepts slow the work and rarely improve the mark." },
      { question: "Do you register the trademark?", answer: "No. We can prepare files a lawyer or IP agent can file. Registration is a legal process in each country." },
    ],
    related: ["graphic-design", "ui-ux-design", "web-development", "digital-marketing"],
    relatedPosts: ["how-to-choose-a-web-development-company", "digital-marketing-for-software-companies"],
    projectCategory: "Design",
  }),
];
