import type { Topic } from "@/lib/topic-types";

export const topicsC: Topic[] = [
  {
    slug: "software-development-company-usa",
    title: "Software Development Company for the USA",
    h1: "Software Development Company for US Startups and Ops Teams",
    category: "Global",
    summary: "A Lahore squad with US overlap hours, your GitHub, and no fake New York office.",
    metaTitle: "Software Development Company for USA Clients | WordbitX",
    metaDescription:
      "Hire a software development company for US projects: overlap hours, client-owned repos and milestone delivery from WordbitX in Pakistan.",
    keywords: ["software development company USA", "hire software developers US", "offshore development USA", "software company for American startups"],
    overview: [
      "US teams hire us when they want a named remote squad, not a body shop. Work lands in your GitHub, Vercel and AWS accounts. Overlap hours are booked, not hoped for.",
      "We do not invent a US street address. The US number on the site is for calls. Delivery is from Pakistan unless a trip is scoped.",
    ],
    useCases: ["SaaS MVPs", "Internal tools", "Storefronts on Stripe"],
    services: ["custom-software-development", "saas-application-development", "web-development"],
    posts: ["offshore-software-development-company", "saas-mvp-development-cost"],
    faqs: [
      { question: "Do you have a US entity?", answer: "We invoice in USD and work in your US cloud accounts. Incorporation in the US is your lawyer’s job, not a page on our site." },
    ],
  },
  {
    slug: "software-development-company-uk",
    title: "Software Development Company for the UK",
    h1: "Software Development Company for UK Product and Agency Teams",
    category: "Global",
    summary: "GMT-friendly stand-ups, written English, and code you own — from Lahore.",
    metaTitle: "Software Development Company for UK Clients | WordbitX",
    metaDescription:
      "Software development company for UK clients: GMT overlap, milestone billing and repositories under your organisation.",
    keywords: ["software development company UK", "hire developers UK offshore", "software house for British companies", "Pakistan software company UK"],
    overview: [
      "UK clients usually want clear written updates and a demo they can show a stakeholder the same week. We work in English, in your tools, with a GMT overlap window when the project needs it.",
      "VAT and UK company filings stay with you. We are a Pakistani software company, not a UK regulated firm.",
    ],
    useCases: ["Agency overflow", "SaaS features", "Ecommerce rebuilds"],
    services: ["web-development", "custom-software-development", "ecommerce-shopify"],
    posts: ["offshore-software-development-company", "how-to-choose-a-web-development-company"],
    faqs: [
      { question: "Can you sign a UK MSA?", answer: "We can work under a written MSA you provide. Local UK employment law does not apply to our team in Lahore." },
    ],
  },
  {
    slug: "software-development-company-uae",
    title: "Software Development Company for the UAE",
    h1: "Software Development Company for UAE and GCC Businesses",
    category: "Global",
    summary: "Arabic/English products, GST-style invoices and Gulf working hours when booked.",
    metaTitle: "Software Development Company UAE & GCC | WordbitX",
    metaDescription:
      "Software development for UAE and GCC: bilingual sites, commerce and ops tools from WordbitX, with Gulf-friendly call windows.",
    keywords: ["software development company UAE", "software company Dubai", "IT company GCC", "hire developers UAE"],
    overview: [
      "UAE and GCC work often means bilingual UI, local payment habits and a calendar that respects Gulf hours. We do not pretend to hold a Dubai mainland trade licence unless you hire us to build software — not to sponsor visas.",
      "Marketplace and classifieds rules differ by emirate. We will not scrape portals or invent listings.",
    ],
    useCases: ["Bilingual marketing sites", "Retail POS groups", "Property portals"],
    services: ["web-development", "ecommerce-development", "real-estate-portals"],
    posts: ["how-to-choose-a-web-development-company", "ecommerce-website-cost-pakistan"],
    faqs: [
      { question: "Do you have an office in Dubai?", answer: "No. We deliver remotely from Pakistan. On-site visits are scoped as travel, not as a fake address." },
    ],
  },
  {
    slug: "software-development-company-canada",
    title: "Software Development Company for Canada",
    h1: "Software Development Company for Canadian Teams",
    category: "Global",
    summary: "English delivery into Canadian Git and cloud accounts, with ET/PT overlap on request.",
    metaTitle: "Software Development Company for Canada | WordbitX",
    metaDescription:
      "Software development for Canadian startups and operators: remote delivery, your repos, bilingual UI when the product needs French.",
    keywords: ["software development company Canada", "hire developers Canada offshore", "software company for Canadian startups"],
    overview: [
      "Canadian product teams hire the same way US teams do: ownership of the repo, a Slack they already use, and no surprise subcontractors. We can ship French/English UI when that is in the scope — we do not claim to be a Quebec law firm.",
      "PIPEDA and provincial privacy stay your counsel’s job. We implement the technical controls you specify.",
    ],
    useCases: ["SaaS", "Public-sector-adjacent ops tools (non-classified)", "Stores"],
    services: ["custom-software-development", "saas-application-development", "web-development"],
    posts: ["offshore-software-development-company", "saas-mvp-development-cost"],
    faqs: [
      { question: "Can you work only in French?", answer: "Product UI yes, if scoped. Day-to-day project English is our default so engineering notes stay precise." },
    ],
  },
  {
    slug: "software-development-company-australia",
    title: "Software Development Company for Australia",
    h1: "Software Development Company for Australian Businesses",
    category: "Global",
    summary: "AEST-friendly check-ins and stores that speak Australian payments — built from Lahore.",
    metaTitle: "Software Development Company for Australia | WordbitX",
    metaDescription:
      "Software development for Australian companies: remote squads, your cloud accounts and commerce that can use local payment methods.",
    keywords: ["software development company Australia", "hire developers Australia", "offshore software Sydney Melbourne"],
    overview: [
      "Australian clients usually want a stand-up that does not sit at 2am their time. We book AEST/AEDT windows when the project needs them and keep decisions in writing.",
      "We integrate the gateways you already use. We do not hold an Australian Financial Services licence.",
    ],
    useCases: ["Shopify Plus brands", "Field apps", "Internal admin"],
    services: ["ecommerce-shopify", "mobile-app-development", "custom-software-development"],
    posts: ["offshore-software-development-company", "how-to-launch-a-shopify-store"],
    faqs: [
      { question: "GST on invoices?", answer: "You handle tax with your accountant. We invoice as a Pakistani company unless a different structure is agreed in writing." },
    ],
  },
  {
    slug: "hire-flutter-developers",
    title: "Hire Flutter Developers",
    h1: "Hire Flutter Developers for Android and iOS from One Codebase",
    category: "Mobile",
    summary: "Named Flutter engineers in your repo — not a resume farm.",
    metaTitle: "Hire Flutter Developers | Android & iOS Team",
    metaDescription:
      "Hire Flutter developers from WordbitX: one Dart codebase for Android and iOS, store publishing and a maintenance path.",
    keywords: ["hire Flutter developers", "Flutter developers Pakistan", "Flutter development team", "Flutter app developers"],
    overview: [
      "Hiring Flutter only works if the people who estimate also ship. We staff named developers, a weekly build you can install, and store accounts you own.",
      "If the product needs heavy native modules, we say so before you hire a three-month Flutter-only bench.",
    ],
    useCases: ["MVPs", "Business apps", "Takeovers of inherited repos"],
    services: ["flutter-app-development", "mobile-app-development", "app-maintenance"],
    posts: ["flutter-vs-react-native", "flutter-app-development-benefits"],
    faqs: [
      { question: "Hourly or milestone?", answer: "Milestones for a defined app. Monthly dedicated if you have a backlog. We write which one in the proposal." },
    ],
  },
  {
    slug: "hire-react-developers",
    title: "Hire React Developers",
    h1: "Hire React and Next.js Developers for Product Front Ends",
    category: "Software",
    summary: "React people who ship server-rendered pages, not only a create-react-app demo.",
    metaTitle: "Hire React Developers | Next.js Front-End Team",
    metaDescription:
      "Hire React and Next.js developers from WordbitX for marketing sites and product UIs that search engines can crawl.",
    keywords: ["hire React developers", "React development team", "Next.js developers", "hire frontend developers"],
    overview: [
      "React is easy to staff badly. We hire for Next.js, accessibility and the metadata work SEO needs — not only component theatre.",
      "You get pull requests in your repo. We do not keep a secret copy of the app.",
    ],
    useCases: ["Dashboards", "Marketing sites", "Headless storefronts"],
    services: ["web-development", "custom-web-application-development", "ui-ux-design"],
    posts: ["how-to-choose-a-web-development-company", "website-speed-and-seo"],
    faqs: [
      { question: "Remote only?", answer: "Yes, from Lahore, with overlap hours you book." },
    ],
  },
  {
    slug: "mvp-development-company",
    title: "MVP Development Company",
    h1: "MVP Development Company — The Smallest Product a Stranger Will Use",
    category: "Software",
    summary: "One job, one release, written scope. Not a 40-screen fantasy deck.",
    metaTitle: "MVP Development Company | Web & Mobile First Release",
    metaDescription:
      "MVP development company: the smallest web or mobile product that can take a real user live, scoped by WordbitX before you spend the rest of the round.",
    keywords: ["MVP development company", "build an MVP", "startup MVP development", "minimum viable product developers"],
    overview: [
      "An MVP is the smallest thing that tests the riskiest assumption. It is not half of the final product randomly cut. We write the one job and refuse the rest until someone uses it.",
      "Stores, payments and admin are included only if the job cannot exist without them.",
    ],
    useCases: ["SaaS trials", "Marketplace tests", "Internal pilots"],
    services: ["saas-application-development", "mobile-app-development", "custom-web-application-development"],
    posts: ["saas-mvp-development-cost", "website-or-mobile-app-first"],
    faqs: [
      { question: "How long?", answer: "A focused web MVP is often 6–12 weeks after discovery. Marketplaces take longer. We will not quote a date without a scope." },
    ],
  },
  {
    slug: "staff-augmentation",
    title: "Staff Augmentation",
    h1: "Staff Augmentation — Engineers Who Join Your Board",
    category: "Software",
    summary: "People in your Slack and Git, billed monthly, with a handover clause.",
    metaTitle: "Staff Augmentation | Dedicated Engineers Pakistan",
    metaDescription:
      "Staff augmentation from WordbitX: named engineers in your tools, monthly billing and a written handover if you stop.",
    keywords: ["staff augmentation", "IT staff augmentation", "hire dedicated developers", "software staff augmentation"],
    overview: [
      "Augmentation is not a project with a launch party. It is capacity: a developer or a small pod that takes tickets from your backlog under your PM.",
      "If you have no backlog and no owner, buy a fixed-scope project instead. We will say which.",
    ],
    useCases: ["Peak load", "Missing mobile skill", "Covering parental leave on a product team"],
    services: ["custom-software-development", "it-consulting", "flutter-app-development"],
    posts: ["offshore-software-development-company", "software-company-lahore"],
    faqs: [
      { question: "Can we interview them?", answer: "Yes. We do not send anonymous CVs and swap the person after kickoff." },
    ],
  },
  {
    slug: "ai-chatbot-development",
    title: "AI Chatbot Development",
    h1: "AI Chatbot Development Grounded in Your Documents",
    category: "AI",
    summary: "Answers from your files, with a human fallback — not a bot that invents prices.",
    metaTitle: "AI Chatbot Development | Document-Grounded Assistants",
    metaDescription:
      "AI chatbot development from WordbitX: assistants grounded in your documents, with logging and a human handoff. No fake medical or legal advice.",
    keywords: ["AI chatbot development", "custom chatbot", "ChatGPT for business", "document chatbot"],
    overview: [
      "A useful chatbot cites your help centre, policies and product docs. An unbounded model will invent discounts and medical claims. We retrieve, we log, and we escalate.",
      "We will not ship a bot that pretends to be a doctor or a lawyer.",
    ],
    useCases: ["Support deflection", "Internal policy Q&A", "Lead qualification"],
    services: ["ai-solutions", "custom-software-development", "api-development"],
    posts: ["how-ai-automation-helps-businesses", "custom-software-vs-ready-made-software"],
    faqs: [
      { question: "Do you train a foundation model?", answer: "Almost never. We retrieve over your content and call an API you pay for. Training is a different, much larger project." },
    ],
  },
  {
    slug: "document-ai-automation",
    title: "Document AI Automation",
    h1: "Document AI Automation for Invoices, IDs and Forms",
    category: "AI",
    summary: "Extraction with a confidence score and a human review queue.",
    metaTitle: "Document AI Automation | Invoice & Form Extraction",
    metaDescription:
      "Document AI automation: invoices, IDs and forms extracted with review queues. WordbitX builds the workflow — not a magic 100% accuracy claim.",
    keywords: ["document AI", "invoice OCR automation", "intelligent document processing", "form extraction AI"],
    overview: [
      "Document AI is a queue: extract, score, send low-confidence rows to a person, then push to the ERP. Accuracy without a review path is how finance disasters start.",
      "We measure against a labelled set you provide. We do not promise 100%.",
    ],
    useCases: ["AP invoices", "KYC packets (under your compliance)", "Application forms"],
    services: ["ai-solutions", "custom-software-development", "crm-erp-solutions"],
    posts: ["how-ai-automation-helps-businesses", "crm-vs-erp-which-one-does-your-business-need"],
    faqs: [
      { question: "Can it read every invoice layout?", answer: "No. We start with your top suppliers and expand. Edge cases stay human." },
    ],
  },
  {
    slug: "shopify-plus-development",
    title: "Shopify Plus Development",
    h1: "Shopify Plus Development for High-Volume Stores",
    category: "Commerce",
    summary: "Checkout customisation, orgs and scripts — when Plus is actually justified.",
    metaTitle: "Shopify Plus Development | High-Volume Shopify",
    metaDescription:
      "Shopify Plus development: checkout extensibility, organisation accounts and integrations for brands that have outgrown basic Shopify.",
    keywords: ["Shopify Plus development", "Shopify Plus developers", "Shopify Plus agency", "Shopify Plus checkout"],
    overview: [
      "Plus is a licence you pay for volume, B2B or checkout control. It is wasted money if you only wanted a prettier theme. We say so if you are not there yet.",
      "Checkout extensibility and org structure are the usual reasons we recommend Plus — not a logo on a pitch deck.",
    ],
    useCases: ["High GMV DTC", "B2B catalogues", "Multi-brand orgs"],
    services: ["ecommerce-shopify", "api-development", "conversion-rate-optimization"],
    posts: ["how-to-launch-a-shopify-store", "shopify-vs-custom-ecommerce-website"],
    faqs: [
      { question: "Do you sell Plus licences?", answer: "Shopify sells Plus. We implement on the store you already pay for." },
    ],
  },
  {
    slug: "b2b-ecommerce-portal",
    title: "B2B Ecommerce Portal",
    h1: "B2B Ecommerce Portal with Price Lists and Account Login",
    category: "Commerce",
    summary: "Logged-in prices, quotes and reorder — not a consumer theme with “wholesale” in the footer.",
    metaTitle: "B2B Ecommerce Portal | Wholesale Login & Price Lists",
    metaDescription:
      "B2B ecommerce portal development: account login, price lists, quotes and reorders for wholesale and dealer networks.",
    keywords: ["B2B ecommerce portal", "wholesale ecommerce", "dealer portal", "B2B online store"],
    overview: [
      "B2B commerce is permissioned catalogues. A guest store that shows retail prices and a PDF price list on the side is not a portal.",
      "We start with login, lists and reorder. Punchout and EDI wait until those work.",
    ],
    useCases: ["Distributors", "Dealer networks", "Internal procurement"],
    services: ["ecommerce-development", "custom-web-application-development", "crm-erp-solutions"],
    posts: ["ecommerce-website-cost-pakistan", "shopify-vs-woocommerce"],
    faqs: [
      { question: "Shopify B2B or custom?", answer: "Shopify B2B if your rules fit Plus. Custom if every dealer has a unique matrix Shopify cannot express." },
    ],
  },
  {
    slug: "subscription-ecommerce",
    title: "Subscription Ecommerce",
    h1: "Subscription Ecommerce: Boxes, Refills and Dunning",
    category: "Commerce",
    summary: "Recurring orders with skip, swap and failed-payment recovery.",
    metaTitle: "Subscription Ecommerce | Recurring Orders & Dunning",
    metaDescription:
      "Subscription ecommerce development: boxes, refills, skips and dunning. Shopify apps or custom — chosen after we see the offer.",
    keywords: ["subscription ecommerce", "subscription box website", "recurring payments store", "Shopify subscriptions"],
    overview: [
      "Subscriptions fail on dunning and on inventory you promised monthly. The pretty landing page is the easy part.",
      "We pick a Shopify subscription app or a custom billing flow after we see how often people skip. We do not lock you into an app that owns the customer.",
    ],
    useCases: ["Refill consumables", "Boxes", "Membership merch"],
    services: ["ecommerce-shopify", "saas-application-development", "email-marketing"],
    posts: ["how-to-launch-a-shopify-store", "saas-mvp-development-cost"],
    faqs: [
      { question: "Which subscription app?", answer: "The one whose contract you can leave. We recommend after seeing churn and SKU count, not from an affiliate link." },
    ],
  },
  {
    slug: "amazon-seller-central-guide",
    title: "Amazon Seller Central",
    h1: "Amazon Seller Central Setup You Actually Own",
    category: "Marketplaces",
    summary: "Account, listings and brand store under your login — not a rented storefront.",
    metaTitle: "Amazon Seller Central Setup | Listings & Brand Store",
    metaDescription:
      "Amazon Seller Central setup from WordbitX: your account, listings and A+ content. No guaranteed Buy Box.",
    keywords: ["Amazon Seller Central", "Amazon seller account setup", "Amazon listing optimization", "Amazon brand store"],
    overview: [
      "Seller Central is only an asset if you hold the login. Agencies that “keep the password” own your reviews. We work as staff in your account.",
      "Listings follow Amazon’s style guides. We do not sell guaranteed ranks or fake reviews.",
    ],
    useCases: ["Brand launches", "Catalogue cleanup", "A+ content"],
    services: ["amazon-store-setup", "graphic-design", "google-merchant-center"],
    posts: ["sell-on-amazon-from-pakistan", "how-to-launch-a-shopify-store"],
    faqs: [
      { question: "FBA required?", answer: "No. We recommend FBA only if margin survives inbound freight." },
    ],
  },
  {
    slug: "ebay-store-management",
    title: "eBay Store Management",
    h1: "eBay Store Management: Templates, Policies and Listings",
    category: "Marketplaces",
    summary: "A store subscription and listing templates — not one-off HTML experiments.",
    metaTitle: "eBay Store Management | Listings & Policies",
    metaDescription:
      "eBay store management: seller hub, listing templates and policies so every SKU is not a one-off.",
    keywords: ["eBay store management", "eBay listing service", "eBay store setup", "sell on eBay"],
    overview: [
      "eBay still converts for parts, refurbished and cross-border leftovers. Templates and policies matter more than a banner.",
      "Promoted Listings wait until the catalogue is complete. Fulfilment stays with you.",
    ],
    useCases: ["Secondary inventory", "Parts", "Cross-border sellers"],
    services: ["ebay-store-setup", "graphic-design", "ecommerce-development"],
    posts: ["sell-on-amazon-from-pakistan", "ecommerce-website-cost-pakistan"],
    faqs: [
      { question: "Do you ship parcels?", answer: "No. We set the store. You or your warehouse dispatch." },
    ],
  },
  {
    slug: "etsy-shop-seo",
    title: "Etsy Shop SEO",
    h1: "Etsy Shop SEO: Titles, Tags and a Shop That Is Allowed",
    category: "Marketplaces",
    summary: "Search terms buyers use — and an honest handmade or vintage story.",
    metaTitle: "Etsy Shop SEO | Titles, Tags & Shop Setup",
    metaDescription:
      "Etsy shop SEO and setup: titles, tags and policies that follow Etsy’s handmade and vintage rules. No dropshipping theatre.",
    keywords: ["Etsy shop SEO", "Etsy listing SEO", "Etsy store setup", "Etsy tags"],
    overview: [
      "Etsy search is closer to Google than to Amazon. Titles and tags have to match how buyers type. Policy violations close shops.",
      "We will not list prohibited production models. If the catalogue is not Etsy-eligible, we stop before you pay for 200 listings.",
    ],
    useCases: ["Makers", "Vintage", "Craft brands"],
    services: ["etsy-store-setup", "graphic-design", "seo-services"],
    posts: ["how-to-launch-a-shopify-store", "shopify-vs-woocommerce"],
    faqs: [
      { question: "Guaranteed page one?", answer: "No. Reviews, price and Etsy’s algorithm sit outside a title rewrite." },
    ],
  },
  {
    slug: "tiktok-shop-for-brands",
    title: "TikTok Shop for Brands",
    h1: "TikTok Shop for Brands — Catalogue, Not Just a Viral Video",
    category: "Marketplaces",
    summary: "A shop that can check out the SKU in the video, in a country where Shop exists.",
    metaTitle: "TikTok Shop for Brands | Catalogue & Ads Pairing",
    metaDescription:
      "TikTok Shop setup for brands: catalogue sync, shipping and pairing with TikTok ads. Availability is country-specific.",
    keywords: ["TikTok Shop", "TikTok Shop setup", "TikTok Shop for brands", "sell on TikTok Shop"],
    overview: [
      "TikTok Shop is useless if the video SKU 404s. We connect a real catalogue — often Shopify — and set processing times you can fulfil.",
      "Shop is not live in every country. We confirm eligibility before you spend on creatives.",
    ],
    useCases: ["DTC brands", "Shopify catalogues", "Creator samples later"],
    services: ["tiktok-shop-setup", "tiktok-ads", "ecommerce-shopify"],
    posts: ["how-to-launch-a-shopify-store", "digital-marketing-for-software-companies"],
    faqs: [
      { question: "Available in Pakistan?", answer: "It changes. We check the entity and market before we start. If Shop is closed, we say so." },
    ],
  },
  {
    slug: "google-shopping-ads",
    title: "Google Shopping Ads",
    h1: "Google Shopping Ads That Start from a Clean Merchant Feed",
    category: "Growth",
    summary: "Feed first, then Shopping or PMax — not ads on a lie about price or stock.",
    metaTitle: "Google Shopping Ads | Merchant Center & Feed",
    metaDescription:
      "Google Shopping ads: Merchant Center feed, diagnostics and campaigns. WordbitX fixes the feed before you scale spend.",
    keywords: ["Google Shopping ads", "Google Shopping campaign", "Merchant Center feed", "Shopping ads setup"],
    overview: [
      "Shopping ads fail when the feed lies. We verify the domain, fix identifiers and only then attach Google Ads.",
      "PMax without query control is a choice we explain. Brand terms in PMax can look like genius and hide waste.",
    ],
    useCases: ["Shopify stores", "WooCommerce", "Large catalogues"],
    services: ["google-merchant-center", "google-ads", "ecommerce-shopify"],
    posts: ["seo-vs-google-ads", "how-to-launch-a-shopify-store"],
    faqs: [
      { question: "Do you guarantee ROAS?", answer: "No. We guarantee a feed you can audit and reporting you can read." },
    ],
  },
  {
    slug: "react-native-app-development",
    title: "React Native App Development",
    h1: "React Native App Development When Your Team Already Ships React",
    category: "Mobile",
    summary: "One JavaScript team, two stores — when the shared web skill is the reason, not fashion.",
    metaTitle: "React Native App Development | Cross-Platform Apps",
    metaDescription:
      "React Native app development from WordbitX: shared JS with a web team, or Flutter if that is the better default. Honest stack choice.",
    keywords: ["React Native app development", "React Native developers", "React Native vs Flutter", "cross platform React Native"],
    overview: [
      "React Native wins when the same people already own a React web app and you want shared logic. It loses when you have no JS bench and Flutter would ship faster.",
      "We recommend Flutter more often. We still staff RN when that is the honest fit.",
    ],
    useCases: ["JS-heavy companies", "Shared design systems", "Takeovers"],
    services: ["mobile-app-development", "flutter-app-development", "web-development"],
    posts: ["flutter-vs-react-native", "mobile-app-development-guide"],
    faqs: [
      { question: "Expo or bare?", answer: "Expo until a native module forces bare. We do not start bare for sport." },
    ],
  },
  {
    slug: "cross-platform-app-development",
    title: "Cross-Platform App Development",
    h1: "Cross-Platform App Development — Flutter, React Native or Neither",
    category: "Mobile",
    summary: "One codebase when the product allows it. Native when you can name why.",
    metaTitle: "Cross-Platform App Development | Flutter & React Native",
    metaDescription:
      "Cross-platform app development: Flutter or React Native for both stores, or native when hardware or graphics demand it.",
    keywords: ["cross platform app development", "cross platform mobile development", "Flutter React Native", "hybrid app development"],
    overview: [
      "Cross-platform is a budget and maintenance decision. It is not “less professional”. Native is for named platform reasons, not prestige.",
      "We write the recommendation in the proposal so you are not sold a stack in a LinkedIn ad.",
    ],
    useCases: ["Business apps", "Marketplaces (later native modules)", "Internal tools"],
    services: ["mobile-app-development", "flutter-app-development", "ios-app-development"],
    posts: ["flutter-vs-react-native", "android-vs-ios-which-to-build-first"],
    faqs: [
      { question: "Is a WebView an app?", answer: "It is a website in a chrome frame. We will not sell it as native quality." },
    ],
  },
  {
    slug: "in-app-purchase-development",
    title: "In-App Purchase Development",
    h1: "In-App Purchase and Subscription Development for iOS and Android",
    category: "Mobile",
    summary: "StoreKit and Play Billing that restore, receipt-check and pass review.",
    metaTitle: "In-App Purchase Development | iOS & Google Play Billing",
    metaDescription:
      "In-app purchase and subscription development: StoreKit, Play Billing, restore purchases and paywalls that pass store review.",
    keywords: ["in-app purchase development", "iOS subscriptions", "Google Play billing", "mobile app IAP"],
    overview: [
      "IAP fails in restore, grace periods and receipt validation — not in the paywall screenshot. We implement store-compliant billing under your developer accounts.",
      "We do not route around store fees with a shady web checkout when the guideline forbids it.",
    ],
    useCases: ["Subscriptions", "Consumables", "Unlocks"],
    services: ["app-monetization", "ios-app-development", "android-app-development"],
    posts: ["complete-guide-to-app-store-optimization", "mobile-app-development-guide"],
    faqs: [
      { question: "Can we take payment only on the website?", answer: "Sometimes for multi-platform SaaS. For digital goods inside the app, stores have rules. We follow them." },
    ],
  },
  {
    slug: "admob-mediation-setup",
    title: "AdMob Mediation",
    h1: "AdMob and Mediation Setup That Does Not Wreck Retention",
    category: "Mobile",
    summary: "Ad units, consent and a frequency the session can bear.",
    metaTitle: "AdMob Mediation Setup | Mobile App Ads",
    metaDescription:
      "AdMob and mediation setup from WordbitX: units, UMP/consent and placements that do not destroy day-one retention.",
    keywords: ["AdMob mediation", "AdMob setup", "mobile app ads", "AdMob optimization"],
    overview: [
      "Mediation is how you add networks without five SDKs fighting. Placement still matters more than the network list. A wall of interstitials on first open is how reviews die.",
      "Accounts stay in your AdMob. We do not promise an eCPM number.",
    ],
    useCases: ["Free utilities", "Content apps", "Casual games"],
    services: ["google-admob", "app-monetization", "flutter-app-development"],
    posts: ["complete-guide-to-app-store-optimization", "how-to-get-google-adsense-approval"],
    faqs: [
      { question: "Will you guarantee $X / day?", answer: "No. Revenue follows traffic quality and retention." },
    ],
  },
  {
    slug: "unity-game-development",
    title: "Unity Game Development",
    h1: "Unity Game Development for Mobile and Lightweight 3D",
    category: "Mobile",
    summary: "A playable loop first — then stores, IAP and live-ops if the loop holds.",
    metaTitle: "Unity Game Development | Mobile & Cross-Platform",
    metaDescription:
      "Unity game development from WordbitX: gameplay loop, mobile ports, monetisation and store publishing. No AAA promises.",
    keywords: ["Unity game development", "mobile game development", "Unity developers", "casual game studio"],
    overview: [
      "Unity is a tool. The product is a loop people repeat. We prototype that before art armies and live-ops dashboards.",
      "We do not claim to ship a Fortnite competitor on a brochure-site budget.",
    ],
    useCases: ["Casual mobile", "Hyper-casual tests", "Lightweight 3D"],
    services: ["game-development", "app-monetization", "app-store-optimization"],
    posts: ["complete-guide-to-app-store-optimization", "mobile-app-development-guide"],
    faqs: [
      { question: "Unreal or Unity?", answer: "Unity for most mobile and small 3D. Unreal when you have a reason and a budget. We will say which." },
    ],
  },
  {
    slug: "facebook-ads-for-ecommerce",
    title: "Facebook Ads for Ecommerce",
    h1: "Facebook and Instagram Ads for Ecommerce Catalogues",
    category: "Growth",
    summary: "A pixel you trust and creatives that match stock — not a boost from a personal profile.",
    metaTitle: "Facebook Ads for Ecommerce | Meta Catalogue Ads",
    metaDescription:
      "Facebook and Instagram ads for ecommerce: pixel, catalogue and creative tests under your Business Manager.",
    keywords: ["Facebook ads for ecommerce", "Instagram ads for shops", "Meta catalogue ads", "DPA Facebook"],
    overview: [
      "Ecommerce Meta ads need a catalogue that matches the site and an event that is a purchase, not a view. Boosts from a personal profile are not a programme.",
      "You own Business Manager. We report cost per purchase against the event you chose.",
    ],
    useCases: ["Shopify", "WooCommerce", "Advantage+ shopping"],
    services: ["facebook-instagram-ads", "facebook-instagram-shop", "graphic-design"],
    posts: ["digital-marketing-for-software-companies", "how-to-launch-a-shopify-store"],
    faqs: [
      { question: "Do you boost posts?", answer: "Only if that is the right tool. Most stores need a conversion campaign." },
    ],
  },
  {
    slug: "linkedin-ads-for-b2b",
    title: "LinkedIn Ads for B2B",
    h1: "LinkedIn Ads for B2B Software and Service Firms",
    category: "Growth",
    summary: "Job-title targeting and an offer sales can take — expensive clicks, used carefully.",
    metaTitle: "LinkedIn Ads for B2B | Lead Gen & Sponsored Content",
    metaDescription:
      "LinkedIn ads for B2B: job titles, lead gen forms or website conversions. WordbitX will not spray “all employees in a country”.",
    keywords: ["LinkedIn ads for B2B", "LinkedIn advertising", "B2B lead gen ads", "LinkedIn Campaign Manager"],
    overview: [
      "LinkedIn CPCs are high on purpose. They pay when the audience is a buyer and the landing page asks for one action. Wide country targeting is how budgets vanish.",
      "Lead gen forms vs website is a trade-off we explain before you spend.",
    ],
    useCases: ["SaaS demos", "Webinars", "Agency retainers"],
    services: ["linkedin-ads", "content-marketing", "seo-services"],
    posts: ["digital-marketing-for-software-companies", "seo-vs-google-ads"],
    faqs: [
      { question: "Cheaper than Google?", answer: "Usually no. Use LinkedIn when job title is the advantage." },
    ],
  },
  {
    slug: "email-automation-for-stores",
    title: "Email Automation for Stores",
    h1: "Email Automation for Stores: Welcome, Abandon and Flows You Own",
    category: "Growth",
    summary: "Lists you own and DNS that passes — no bought databases.",
    metaTitle: "Email Automation for Ecommerce | Klaviyo & Flows",
    metaDescription:
      "Email automation for stores: welcome, abandoned cart and post-purchase flows on an ESP you own. WordbitX does not mail bought lists.",
    keywords: ["email automation ecommerce", "abandoned cart email", "Klaviyo flows", "ecommerce email marketing"],
    overview: [
      "Store email pays when the list opted in and the domain authenticates. Bought lists get the domain blocked and we will not send them.",
      "We connect the ESP, build two or three flows, and leave templates your marketer can reuse.",
    ],
    useCases: ["Shopify", "WooCommerce", "SaaS trials"],
    services: ["email-marketing", "ecommerce-shopify", "conversion-rate-optimization"],
    posts: ["how-to-launch-a-shopify-store", "digital-marketing-for-software-companies"],
    faqs: [
      { question: "Klaviyo or Mailchimp?", answer: "Klaviyo if you are a serious store. Mailchimp or Brevo if the list is small. Your choice, your bill." },
    ],
  },
  {
    slug: "core-web-vitals-guide",
    title: "Core Web Vitals",
    h1: "Core Web Vitals: LCP, INP and CLS on Real Mobiles",
    category: "Growth",
    summary: "Field data first. A Lighthouse 100 on office wifi is not the goal.",
    metaTitle: "Core Web Vitals Guide | LCP, INP, CLS",
    metaDescription:
      "Core Web Vitals guide: LCP, INP and CLS for real users. How WordbitX budgets weight instead of chasing a lab 100.",
    keywords: ["Core Web Vitals", "LCP optimization", "INP optimization", "improve Core Web Vitals"],
    overview: [
      "Core Web Vitals are how Google and users feel the page. We treat CrUX and Search Console as truth, then cut images, fonts and third-party scripts.",
      "A 900 KB homepage will not pass on Pakistani or Gulf mobile networks. More blog posts will not fix that.",
    ],
    useCases: ["Marketing sites", "Stores", "Landing pages for ads"],
    services: ["website-speed-optimization", "technical-seo", "web-development"],
    posts: ["website-speed-and-seo", "seo-guide-for-businesses"],
    faqs: [
      { question: "Can every site hit 100?", answer: "No, and chasing 100 often breaks analytics. We target “good” CWV for real users." },
    ],
  },
  {
    slug: "conversion-rate-optimization-guide",
    title: "Conversion Rate Optimization",
    h1: "Conversion Rate Optimization for Sites That Already Have Traffic",
    category: "Growth",
    summary: "Forms, checkout and one action per screen — measured, not argued.",
    metaTitle: "Conversion Rate Optimization Guide | CRO for Services & Stores",
    metaDescription:
      "Conversion rate optimization: events, forms and checkout friction. WordbitX will not guarantee a lift percentage without your data.",
    keywords: ["conversion rate optimization", "CRO guide", "landing page optimization", "checkout optimization"],
    overview: [
      "CRO starts when you can name the conversion. Then we remove fields, clarify shipping and put proof next to pay. Button-colour debates wait.",
      "If you have no traffic, buy SEO or ads first. Optimising an empty room is theatre.",
    ],
    useCases: ["Lead-gen sites", "Stores", "SaaS trials"],
    services: ["conversion-rate-optimization", "ui-ux-design", "google-ads"],
    posts: ["seo-vs-google-ads", "how-to-choose-a-web-development-company"],
    faqs: [
      { question: "Guarantee +20% conversions?", answer: "No. Anyone who guarantees a number without seeing your funnel is guessing." },
    ],
  },
  {
    slug: "devops-for-startups",
    title: "DevOps for Startups",
    h1: "DevOps for Startups: CI/CD, Previews and a Rollback You Can Run",
    category: "Cloud",
    summary: "Pipelines and preview URLs — not Kubernetes because a blog said so.",
    metaTitle: "DevOps for Startups | CI/CD and Preview Deploys",
    metaDescription:
      "DevOps for startups: CI/CD, preview environments and monitoring. WordbitX recommends Kubernetes only when you actually need it.",
    keywords: ["DevOps for startups", "CI CD setup", "startup DevOps", "preview deployments"],
    overview: [
      "Startup DevOps is a pipeline that deploys what passed tests, a preview per pull request, and a way to roll back. It is not a 40-service mesh.",
      "We work in your AWS, GCP or Vercel org. Secrets stay out of the repo.",
    ],
    useCases: ["Next.js apps", "APIs", "Mobile backends"],
    services: ["devops-cloud-solutions", "web-hosting", "website-security"],
    posts: ["custom-software-vs-ready-made-software", "website-speed-and-seo"],
    faqs: [
      { question: "Do we need Kubernetes?", answer: "Usually no. Managed containers or Vercel/Cloud Run are enough until they are not." },
    ],
  },
  {
    slug: "website-security-hardening",
    title: "Website Security Hardening",
    h1: "Website Security Hardening, SSL and Malware Cleanup",
    category: "Cloud",
    summary: "Updates, 2FA and a backup you have restored once — not a “military grade” badge.",
    metaTitle: "Website Security Hardening | SSL, WAF & Cleanup",
    metaDescription:
      "Website security hardening: SSL, access control, malware cleanup and WAF rules. WordbitX does not sell fake security stickers.",
    keywords: ["website security hardening", "WordPress malware cleanup", "SSL installation", "website WAF"],
    overview: [
      "Most hacks are old plugins and shared passwords. We close those, rotate secrets and put backups you have actually restored.",
      "We cannot promise you will never be hacked. We can make the obvious doors shut.",
    ],
    useCases: ["WordPress", "WooCommerce", "Custom apps"],
    services: ["website-security", "website-maintenance", "web-hosting"],
    posts: ["wordpress-vs-custom-website", "website-speed-and-seo"],
    faqs: [
      { question: "Lifetime hack-proof?", answer: "No vendor can sell that. Keep the retainer or the same hole returns." },
    ],
  },
  {
    slug: "logo-and-brand-kit",
    title: "Logo and Brand Kit",
    h1: "Logo and Brand Kit That Works at 16 Pixels",
    category: "Design",
    summary: "A mark, type and rules your developer can use — not 40 unused mockups.",
    metaTitle: "Logo and Brand Kit | Identity for Software Companies",
    metaDescription:
      "Logo and brand kit design: wordmark, colour, type and usage rules that survive a favicon and a dark nav.",
    keywords: ["logo and brand kit", "logo design for startups", "brand identity design", "software company branding"],
    overview: [
      "A logo that dies in the tab is not a brand. We test favicon and app-icon crops before you fall in love with detail.",
      "Trademark filing is a lawyer. We deliver files they can use.",
    ],
    useCases: ["New companies", "Renames", "Product + company split"],
    services: ["logo-brand-identity", "graphic-design", "ui-ux-design"],
    posts: ["how-to-choose-a-web-development-company", "digital-marketing-for-software-companies"],
    faqs: [
      { question: "Unlimited concepts?", answer: "Two or three directions, then refine. Unlimited random concepts slow the work." },
    ],
  },
  {
    slug: "design-system-for-products",
    title: "Design System for Products",
    h1: "Design System for Products — Components Engineering Can Ship",
    category: "Design",
    summary: "Tokens and components that match the repo, not a Figma graveyard.",
    metaTitle: "Design System for Products | UI Kits That Ship",
    metaDescription:
      "Product design systems from WordbitX: tokens, components and states that match what Next.js or Flutter will actually ship.",
    keywords: ["design system", "UI kit for SaaS", "component library design", "product design system"],
    overview: [
      "A design system is a contract between design and code. If engineering never opens it, it is art. We sit with the repo and name tokens the same way.",
      "We do not deliver 400 unused variants to look busy.",
    ],
    useCases: ["SaaS", "Multi-surface brands", "White-label UIs"],
    services: ["ui-ux-design", "web-development", "flutter-app-development"],
    posts: ["saas-mvp-development-cost", "how-to-choose-a-web-development-company"],
    faqs: [
      { question: "Storybook included?", answer: "When the team will maintain it. Otherwise the system lives in Figma plus the running app." },
    ],
  },
  {
    slug: "landing-page-design",
    title: "Landing Page Design",
    h1: "Landing Page Design for Ads and Launches",
    category: "Design",
    summary: "One offer, one action, speed budget — not a homepage clone with the logo swapped.",
    metaTitle: "Landing Page Design | Ads & Launch Pages",
    metaDescription:
      "Landing page design for paid traffic and launches: one offer, message match and a performance budget.",
    keywords: ["landing page design", "ad landing page", "launch page design", "high converting landing page"],
    overview: [
      "A landing page has one job. If it links to seven services, it is a homepage. We write the offer first, then layout, then ship with a weight budget ads can survive.",
      "Message match with the ad is a ranking and Quality Score issue, not a decoration.",
    ],
    useCases: ["Google Ads", "Meta", "Product launches"],
    services: ["ui-ux-design", "web-development", "conversion-rate-optimization"],
    posts: ["seo-vs-google-ads", "digital-marketing-for-software-companies"],
    faqs: [
      { question: "Can you A/B test?", answer: "Yes, after events exist. Testing two pretty versions with no conversion event is noise." },
    ],
  },
  {
    slug: "patient-portal-software",
    title: "Patient Portal Software",
    h1: "Patient Portal Software for Appointments, Reports and Bills",
    category: "Healthcare software",
    summary: "A login for results and invoices — not a diagnosis engine.",
    metaTitle: "Patient Portal Software | Appointments, Reports & Bills",
    metaDescription:
      "Patient portal software: appointments, reports and bills. WordbitX builds the portal; clinicians own the medicine.",
    keywords: ["patient portal software", "patient login portal", "medical reports portal", "clinic patient app"],
    overview: [
      "A patient portal is access: bookings, reports the lab already released, and bills. It is not a chatbot that diagnoses a rash.",
      "Access control and audit logs are the product. We do not publish health news or treatment plans.",
    ],
    useCases: ["Clinics", "Labs", "Small hospitals"],
    services: ["hospital-medical-portals", "custom-web-application-development", "mobile-app-development"],
    posts: ["custom-software-vs-ready-made-software", "website-or-mobile-app-first"],
    faqs: [
      { question: "HIPAA / local privacy?", answer: "We implement the controls you specify. Certification and legal sign-off stay with the provider." },
    ],
  },
  {
    slug: "lab-information-system",
    title: "Lab Information System",
    h1: "Lab Information System (LIS) Software for Orders and Reports",
    category: "Healthcare software",
    summary: "Sample in, report out, with IDs you can audit — not clinical interpretation.",
    metaTitle: "Lab Information System Software | Orders & Reports",
    metaDescription:
      "Lab information system software: orders, sample IDs and report delivery. WordbitX builds LIS workflows; pathologists interpret results.",
    keywords: ["lab information system", "LIS software", "laboratory management software", "lab report software"],
    overview: [
      "An LIS tracks a sample from order to a report the clinician can open. Reference ranges and interpretation belong to the lab’s licensed staff.",
      "We will not generate fake medical news or “normal/abnormal” claims as a marketing blog.",
    ],
    useCases: ["Diagnostic labs", "Hospital labs", "Collection points"],
    services: ["hospital-medical-portals", "custom-software-development", "api-development"],
    posts: ["how-ai-automation-helps-businesses", "custom-software-vs-ready-made-software"],
    faqs: [
      { question: "Do you read lab results?", answer: "No. Software moves data. Clinicians interpret it." },
    ],
  },
  {
    slug: "university-portal-software",
    title: "University Portal Software",
    h1: "University Portal Software for Admissions, LMS and Fees",
    category: "Education software",
    summary: "Applicants, students and finance in roles that do not leak grades.",
    metaTitle: "University Portal Software | Admissions, LMS & Fees",
    metaDescription:
      "University portal software: admissions, student records, fees and course access with role-based logins.",
    keywords: ["university portal software", "campus portal", "university management system", "higher education ERP"],
    overview: [
      "A campus portal is several products: admissions, SIS, fees and sometimes an LMS. Shipping all four in one go is how projects die. We phase.",
      "Grade integrity and who can see a transcript is an access problem, not a theme.",
    ],
    useCases: ["Universities", "Colleges", "Distance programmes"],
    services: ["education-portals", "custom-software-development", "crm-erp-solutions"],
    posts: ["school-management-system-software", "custom-software-vs-ready-made-software"],
    faqs: [
      { question: "Moodle plus custom?", answer: "Often yes. We do not rewrite an LMS for sport if Moodle already teaches the course." },
    ],
  },
  {
    slug: "jewellery-pos-software",
    title: "Jewellery POS Software",
    h1: "Jewellery POS Software for Weight, Purity and Making Charges",
    category: "Operations",
    summary: "Gold is not an SKU. Weight, purity and making have to live on the line.",
    metaTitle: "Jewellery POS Software | Weight, Purity & Tagging",
    metaDescription:
      "Jewellery POS software: weight-based billing, purity, making charges and tag printing for jewellers.",
    keywords: ["jewellery POS software", "gold POS", "jewelry store software", "weight based POS"],
    overview: [
      "Jewellery POS fails when it treats a ring like a T-shirt. Weight, purity, making and old-gold exchange are the line items. We have built this pattern; we do not invent a client name to prove it.",
      "Barcode tags and a day-end that matches the tray are day-one requirements.",
    ],
    useCases: ["Retail jewellers", "Wholesale gold", "Multi-branch showrooms"],
    services: ["pos-software", "inventory-management-software", "ecommerce-development"],
    posts: ["pos-software-for-retail-pakistan", "inventory-management-software-guide"],
    faqs: [
      { question: "Karat and scrap?", answer: "Yes, if that is how you buy and sell. We model your book, not a generic fashion SKU." },
    ],
  },
  {
    slug: "field-service-management",
    title: "Field Service Management",
    h1: "Field Service Management Software for Jobs, Techs and Proof",
    category: "Operations",
    summary: "A job, a technician, a timestamp and a photo — not a WhatsApp group called “jobs”.",
    metaTitle: "Field Service Management Software | Dispatch & Proof",
    metaDescription:
      "Field service management software: job dispatch, technician apps and proof of visit for maintenance and installation teams.",
    keywords: ["field service management", "field service software", "technician dispatch app", "job management software"],
    overview: [
      "Field service is dispatch plus proof. If you cannot show a customer when someone arrived, you will argue. Offline on the phone matters more than a pretty map.",
      "We launch one job type in one city. Routing AI can wait.",
    ],
    useCases: ["AC / appliance", "Install teams", "Warranty visits"],
    services: ["mobile-app-development", "custom-software-development", "api-development"],
    posts: ["mobile-app-development-guide", "custom-software-vs-ready-made-software"],
    faqs: [
      { question: "Do you provide technicians?", answer: "No. We build the system your technicians use." },
    ],
  },
  {
    slug: "helpdesk-ticketing-system",
    title: "Helpdesk Ticketing System",
    h1: "Helpdesk Ticketing System for Support Teams",
    category: "Operations",
    summary: "One queue, SLAs and an audit trail — email is not a ticket system.",
    metaTitle: "Helpdesk Ticketing System | SLAs & Shared Inbox",
    metaDescription:
      "Helpdesk ticketing system: shared queues, SLAs and customer history. Buy Zendesk or build — WordbitX will say which.",
    keywords: ["helpdesk ticketing system", "support ticket software", "shared inbox support", "SLA helpdesk"],
    overview: [
      "A helpdesk is assignment, SLA clocks and a history the next agent can read. A shared Gmail label is how tickets disappear.",
      "Buy Zendesk/Freshdesk if your process is standard. Build when the ticket is a plot file, a batch or a campus ID.",
    ],
    useCases: ["SaaS support", "Internal IT", "Agency retainers"],
    services: ["custom-web-application-development", "crm-erp-solutions", "it-consulting"],
    posts: ["custom-crm-for-growing-businesses", "custom-software-vs-ready-made-software"],
    faqs: [
      { question: "Chat + tickets?", answer: "Yes, if chat creates a ticket. Chat that evaporates is not support." },
    ],
  },
  {
    slug: "hr-payroll-software",
    title: "HR and Payroll Software",
    h1: "HR and Payroll Software for Attendance, Leaves and Payslips",
    category: "Operations",
    summary: "Attendance in, payslip out — we are not your labour lawyer.",
    metaTitle: "HR and Payroll Software | Attendance & Payslips",
    metaDescription:
      "HR and payroll software: attendance, leaves and payslips. WordbitX builds the system; statutory rules stay with your accountant.",
    keywords: ["HR payroll software", "attendance payroll system", "payslip software", "HRMS development"],
    overview: [
      "HR software is a ledger of time and pay. Tax tables and labour law change. We implement the rules you (or your accountant) sign off. We do not practise employment law.",
      "Biometric devices are integrations, not a lock-in we sell.",
    ],
    useCases: ["SMEs", "Multi-branch staff", "Contract + permanent mix"],
    services: ["custom-software-development", "api-development", "it-consulting"],
    posts: ["custom-software-vs-ready-made-software", "crm-vs-erp-which-one-does-your-business-need"],
    faqs: [
      { question: "Do you file taxes?", answer: "No. We generate data. Filing stays with your finance team." },
    ],
  },
];
